# CIC IIoT Dataset 2025 Intrusion Detection - GWO

In [ ]:
!pip install scikit-learn
!pip install mealpy
!pip install Boruta
!pip install lightgbm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
from typing import List, Tuple, Dict, Optional
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, make_scorer, confusion_matrix, ConfusionMatrixDisplay, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.feature_selection import VarianceThreshold
_HAS_MEALPY = False
_HAS_BORUTA = False
try:
    from boruta import BorutaPy
    _HAS_BORUTA = True
    print('BorutaPy available')
except Exception:
    _HAS_BORUTA = False
    print('BorutaPy not available yet. Run the install cell, then re-run this cell.')
try:
    from mealpy.swarm_based import GWO, BA
    _HAS_MEALPY = True
    print("Mealpy available: GWO/BA")
except Exception:
    _HAS_MEALPY = False
    print("Mealpy not available. Using fallback feature selection.")

_HAS_FLOATVAR = False
try:
    from mealpy import FloatVar
    _HAS_FLOATVAR = True
except Exception:
    _HAS_FLOATVAR = False

plt.style.use('seaborn-v0_8-darkgrid')

Requirement already satisfied: scikit-learn in /root/iiot-run/.venv/lib/python3.12/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in /root/iiot-run/.venv/lib/python3.12/site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /root/iiot-run/.venv/lib/python3.12/site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from scikit-learn) (3.6.0)

Requirement already satisfied: mealpy in /root/iiot-run/.venv/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.17.5 in /root/iiot-run/.venv/lib/python3.12/site-packages (from mealpy) (2.4.6)
Requirement already satisfied: matplotlib>=3.3.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from mealpy) (3.10.9)
Requirement already satisfied: scipy>=1.7.1 in /root/iiot-run/.venv/lib/python3.12/site-packages (from mealpy) (1.17.1)
Requirement already satisfied: pandas>=1.2.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from mealpy) (3.0.3)
Requirement already satisfied: opfunu>=1.0.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from mealpy) (1.0.1)

Requirement already satisfied: contourpy>=1.0.1 in /root/iiot-run/.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /root/iiot-run/.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /root/iiot-run/.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (26.2)
Requirement already satisfied: pillow>=8 in /root/iiot-run/.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /root/iiot-run/.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /root/iiot-run/.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (2.9.0.post0)
Requirement already satisfied: requests>=2.27.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from opfunu>=1.0.0->mealpy) (2.34.2)

Requirement already satisfied: six>=1.5 in /root/iiot-run/.venv/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->mealpy) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /root/iiot-run/.venv/lib/python3.12/site-packages (from requests>=2.27.0->opfunu>=1.0.0->mealpy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /root/iiot-run/.venv/lib/python3.12/site-packages (from requests>=2.27.0->opfunu>=1.0.0->mealpy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /root/iiot-run/.venv/lib/python3.12/site-packages (from requests>=2.27.0->opfunu>=1.0.0->mealpy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /root/iiot-run/.venv/lib/python3.12/site-packages (from requests>=2.27.0->opfunu>=1.0.0->mealpy) (2026.5.20)

Requirement already satisfied: Boruta in /root/iiot-run/.venv/lib/python3.12/site-packages (0.4.3)

Requirement already satisfied: numpy>=1.10.4 in /root/iiot-run/.venv/lib/python3.12/site-packages (from Boruta) (2.4.6)
Requirement already satisfied: scikit-learn>=0.17.1 in /root/iiot-run/.venv/lib/python3.12/site-packages (from Boruta) (1.9.0)
Requirement already satisfied: scipy>=0.17.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from Boruta) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from scikit-learn>=0.17.1->Boruta) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /root/iiot-run/.venv/lib/python3.12/site-packages (from scikit-learn>=0.17.1->Boruta) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from scikit-learn>=0.17.1->Boruta) (3.6.0)

Requirement already satisfied: lightgbm in /root/iiot-run/.venv/lib/python3.12/site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in /root/iiot-run/.venv/lib/python3.12/site-packages (from lightgbm) (2.4.6)
Requirement already satisfied: scipy in /root/iiot-run/.venv/lib/python3.12/site-packages (from lightgbm) (1.17.1)

BorutaPy available
Mealpy available: GWO/BA

## Feature Selection Functions (GWO + Original BorutaPy + Optional BA Helpers + Without FS)

In [ ]:
def _evaluate_subset(
    X: np.ndarray, y: np.ndarray, idx: List[int],
    clf=None, cv: int = 3, scoring: str = 'accuracy',
    lam: float = 0.01,
    alpha_fp: float = 0.0,   # set >0 later if you want explicit false-positive penalty
    benign_id: Optional[int] = None
) -> float:
    if len(idx) == 0:
        return 0.0

    # CHANGED: default classifier now class-weighted for robustness
    if clf is None:
        clf = DecisionTreeClassifier(random_state=42, class_weight='balanced')

    pipe = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler(with_mean=True)),
        ('clf', clf)
    ])

    X_sub = X[:, idx]
    cvk = StratifiedKFold(n_splits=cv, shuffle=True, random_state=42)

    scorer = 'accuracy' if scoring == 'accuracy' else make_scorer(f1_score, average='macro')

    # Base CV score
    scores = cross_val_score(pipe, X_sub, y, scoring=scorer, cv=cvk, n_jobs=None)
    base = float(np.mean(scores))

    # Compactness penalty
    size_penalty = lam * (len(idx) / X.shape[1])

    # Optional false-positive penalty (OFF by default)
    fp_penalty = 0.0
    if alpha_fp > 0.0 and benign_id is not None:
        fprs = []
        for tr, te in cvk.split(X_sub, y):
            pipe.fit(X_sub[tr], y[tr])
            p = pipe.predict(X_sub[te])
            y_te = y[te]
            benign = (y_te == benign_id)
            fp = np.sum((p != benign_id) & benign)
            tn = np.sum((p == benign_id) & benign)
            fprs.append(fp / (fp + tn + 1e-12))
        fp_penalty = alpha_fp * float(np.mean(fprs))

    return base - size_penalty - fp_penalty

# =========================================
# Convergence History Storage (Global)
# =========================================
convergence_history = {}

def _optimize_continuous(
    OptimizerClass, X: np.ndarray, y: np.ndarray, k: int,
    clf=None, epochs: int = 30, pop_size: int = 30,
    cv: int = 3, scoring: str = 'accuracy', seed: int = 42
) -> Tuple[List[int], float]:

    dim = X.shape[1]
    lb_vec = [0.0] * dim
    ub_vec = [1.0] * dim

    lambda_max = 0.05
    lambda_min = 0.005

    total_calls = epochs * pop_size
    call_counter = {'n': 0}

    history = []

    def fitness(w):
        call_counter['n'] += 1
        progress = min(call_counter['n'] / total_calls, 1.0)
        t = progress * epochs

        a_t = 2 - 2 * (t / epochs)
        lam_dynamic = lambda_min + (lambda_max - lambda_min) * (a_t / 2)

        w = np.asarray(w)
        idx = list(range(dim)) if k >= dim else list(np.argsort(-w)[:k])

        score = _evaluate_subset(
            X, y, idx,
            clf=clf,
            cv=cv,
            scoring=scoring,
            lam=lam_dynamic
        )

        history.append(score)
        return score

    random.seed(int(seed))
    np.random.seed(int(seed))

    problem_mealpy = {
        'obj_func': fitness,
        'minmax': 'max',
        'lb': lb_vec,
        'ub': ub_vec,
        'seed': int(seed)
    }

    if _HAS_FLOATVAR:
        problem_mealpy['bounds'] = FloatVar(lb=lb_vec, ub=ub_vec)

    if isinstance(OptimizerClass, type):
        opt = OptimizerClass(epoch=epochs, pop_size=pop_size)
        res = opt.solve(problem_mealpy)
        algo_name = OptimizerClass.__name__
    else:
        if hasattr(OptimizerClass, 'OriginalGWO'):
            opt = OptimizerClass.OriginalGWO(epoch=epochs, pop_size=pop_size)
            algo_name = "GWO"
        elif hasattr(OptimizerClass, 'OriginalBA'):
            opt = OptimizerClass.OriginalBA(epoch=epochs, pop_size=pop_size)
            algo_name = "BA"
        else:
            raise TypeError('Unsupported optimizer type')
        res = opt.solve(problem_mealpy)

    best_pos = res[0] if isinstance(res, tuple) else res.solution
    # Save convergence history
    convergence_history[f"{algo_name}_k{k}"] = history

    w = np.asarray(best_pos)
    idx = list(range(dim)) if k >= dim else list(np.argsort(-w)[:k])

    final_lambda = lambda_min
    score = _evaluate_subset(
        X, y, idx,
        clf=clf,
        cv=cv,
        scoring=scoring,
        lam=final_lambda
    )

    return idx, score


def select_features_gwo(X, y, k, clf=None, epochs=30, pop_size=30, cv=3, scoring='accuracy', seed: int = 42):
    if _HAS_MEALPY:
        return _optimize_continuous(GWO, X, y, k, clf, epochs, pop_size, cv, scoring, seed=seed)

    from sklearn.feature_selection import mutual_info_classif
    mi = mutual_info_classif(X, y, random_state=42)
    idx = list(np.argsort(-mi)[:k])

    # CHANGED: apply penalty in fallback too
    return idx, _evaluate_subset(X, y, idx, clf=clf, cv=cv, scoring=scoring, lam=0.01)


def select_features_ba(X, y, k, clf=None, epochs=30, pop_size=30, cv=3, scoring='accuracy'):
    if _HAS_MEALPY:
        return _optimize_continuous(BA, X, y, k, clf, epochs, pop_size, cv, scoring)

    from sklearn.feature_selection import mutual_info_classif
    mi = mutual_info_classif(X, y, random_state=42)
    idx = list(np.argsort(-mi)[:k])

    # CHANGED: apply penalty in fallback too
    return idx, _evaluate_subset(X, y, idx, clf=clf, cv=cv, scoring=scoring, lam=0.01)


def select_features_boruta(X, y, k=None, clf=None, cv=3, scoring='accuracy', seed: int = 42):
    if not _HAS_BORUTA:
        raise ImportError("BorutaPy is not available. Install Boruta, then rerun the imports cell.")

    X_imp = SimpleImputer(strategy='median').fit_transform(X)
    y_arr = np.asarray(y)
    dim = int(X_imp.shape[1])

    rf = RandomForestClassifier(
   n_estimators=800,
    max_depth=30,
    min_samples_split=3,
    min_samples_leaf=1,
    max_features='sqrt',
    class_weight='balanced',
    max_samples=0.8,
    n_jobs=-1,
    random_state=42
    )

    boruta = BorutaPy(
        estimator=rf,
        n_estimators='auto',
        perc=100,
        alpha=0.05,
        two_step=True,
        max_iter=15,
        random_state=int(seed),
        verbose=0
    )
    boruta.fit(X_imp, y_arr)

    idx = list(np.where(np.asarray(boruta.support_, dtype=bool))[0])
    if len(idx) == 0:
        ranking = np.asarray(getattr(boruta, 'ranking_', np.ones(dim)), dtype=float)
        idx = [int(np.argmin(ranking))]

    return idx, _evaluate_subset(X, y_arr, idx, clf=clf, cv=cv, scoring=scoring, lam=0.0)


def select_features_hybrid_boruta(X, y, k, clf=None, cv=3, scoring='accuracy', seed: int = 42):
    X_imp = SimpleImputer(strategy='median').fit_transform(X)
    y_arr = np.asarray(y)
    dim = int(X_imp.shape[1])
    kk = int(min(max(int(k), 1), dim))

    rng = np.random.default_rng(int(seed))
    n_iter = int(max(10, int(cv) * 3))
    wins = np.zeros(dim, dtype=float)
    imp_sum = np.zeros(dim, dtype=float)

    for _ in range(n_iter):
        X_shadow = X_imp.copy()
        for j in range(dim):
            rng.shuffle(X_shadow[:, j])
        X_aug = np.hstack([X_imp, X_shadow])

        rf = RandomForestClassifier(
       n_estimators=800,
    max_depth=30,
    min_samples_split=3,
    min_samples_leaf=1,
    max_features='sqrt',
    class_weight='balanced',
    max_samples=0.8,
    n_jobs=-1,
    random_state=42
        )
        rf.fit(X_aug, y_arr)
        imp = np.asarray(getattr(rf, 'feature_importances_', None), dtype=float)
        if imp is None or imp.size != (2 * dim):
            raise RuntimeError('rf importances not available')

        real_imp = imp[:dim]
        shadow_imp = imp[dim:]
        thr = float(np.max(shadow_imp))
        wins += (real_imp > thr).astype(float)
        imp_sum += real_imp

    score = wins + 1e-3 * (imp_sum / float(n_iter))
    idx = list(np.argsort(-score)[:kk])
    return idx, _evaluate_subset(X, y_arr, idx, clf=clf, cv=cv, scoring=scoring, lam=0.01)


def select_features_without_fs(X, y, clf=None, cv=3, scoring='accuracy'):
    idx = list(range(X.shape[1]))
    return idx, _evaluate_subset(X, y, idx, clf=clf, cv=cv, scoring=scoring, lam=0.0)


def select_features_lightgbm(X, y, k, clf=None, cv=3, scoring='accuracy', seed: int = 42):
    try:
        from lightgbm import LGBMClassifier
    except ImportError:
        raise ImportError('lightgbm is not available.')
    X_imp = SimpleImputer(strategy='median').fit_transform(X)
    y_arr = np.asarray(y)
    kk = int(min(max(int(k), 1), X_imp.shape[1]))
    n_classes = len(np.unique(y_arr))
    objective = 'binary' if n_classes <= 2 else 'multiclass'
    model = LGBMClassifier(
        n_estimators=800,
        learning_rate=0.05,
        num_leaves=31,
        subsample=0.8,
        colsample_bytree=0.8,
        objective=objective,
        class_weight='balanced',
        random_state=int(seed),
        verbosity=-1
    )
    model.fit(X_imp, y_arr)
    imp = np.asarray(getattr(model, 'feature_importances_', np.zeros(X_imp.shape[1])), dtype=float)
    if imp.size != X_imp.shape[1] or np.all(imp == 0):
        raise RuntimeError('LightGBM importances not available')
    idx = list(np.argsort(-imp)[:kk])
    return idx, _evaluate_subset(X, y_arr, idx, clf=clf, cv=cv, scoring=scoring, lam=0.01)


def run_all_algorithms(X, y, ks: List[int], clf=None, epochs=30, pop_size=30, cv=3, feature_names: Optional[List[str]] = None, scoring='accuracy') -> Dict[str, Dict[int, Dict]]:
    results = {'GWO': {}, 'BA': {}, 'LightGBM': {}, 'Boruta': {}}
    for k in ks:
        idx_gwo, s_gwo = select_features_gwo(X, y, k, clf, epochs, pop_size, cv, scoring)
        idx_ba, s_ba = select_features_ba(X, y, k, clf, epochs, pop_size, cv, scoring)
        idx_lgbm, s_lgbm = select_features_lightgbm(X, y, k, clf, cv=cv, scoring=scoring)
        idx_boruta, s_boruta = select_features_boruta(X, y, None, clf, cv=cv, scoring=scoring, seed=42)

        for algo, idx, score in [('GWO', idx_gwo, s_gwo), ('BA', idx_ba, s_ba), ('LightGBM', idx_lgbm, s_lgbm), ('Boruta', idx_boruta, s_boruta)]:
            feats = [feature_names[i] for i in idx] if feature_names else None
            results[algo][k] = {'indices': idx, 'score': score, 'features': feats}

    return results

## Load Data + Cleaning + Dimensionality Reduction

In [ ]:
print('Loading and preprocessing dataset...')
all_data = r"/root/iiot-run/data/cleaned_merged_full.csv"

print('Loading data...')
combined_data = pd.read_csv(all_data, on_bad_lines='skip')
#combined_data = pd.read_csv(all_data, on_bad_lines='skip').sample(n=3000, random_state=42)

print(f"Dataset loaded successfully!")
print(f"   - Total samples: {len(combined_data)}")
print(f"   - Features: {combined_data.shape[1] - 1}")

# -------- Detect label column (label2 preferred, else label1)
label_col_src = None
for col in combined_data.columns:
    cl = col.lower()
    if 'label2' in cl:
        label_col_src = col
        break
    if 'label1' in cl and label_col_src is None:
        label_col_src = col

if label_col_src:
    label_percent = (combined_data[label_col_src].value_counts(normalize=True) * 100).round(2)
    print('\nLabel distribution (%):')
    print(label_percent)

# -------- Drop non-numeric string columns but keep label columns
string_columns = combined_data.select_dtypes(include=['object']).columns.tolist()
for keep in ['label2', 'label1', label_col_src]:
    if keep in string_columns:
        string_columns.remove(keep)

print(f"   - Dropping {len(string_columns)} string columns for ML processing")
combined_data_numeric = combined_data.drop(columns=string_columns)

target_col = 'label2' if 'label2' in combined_data_numeric.columns else ('label1' if 'label1' in combined_data_numeric.columns else None)
if target_col is None:
    raise ValueError('No label2/label1 column found in dataset')

X_raw = combined_data_numeric.drop(target_col, axis=1)
y_raw = combined_data_numeric[target_col]

# -------- Multiclass encoding
y_clean = y_raw.astype(str).str.strip()
classes = sorted(y_clean.unique())
class_to_id = {c: i for i, c in enumerate(classes)}
y = y_clean.map(class_to_id).astype(int)
print(f'Encoding used (multiclass): {class_to_id}')

# -------- Fill numeric NaNs with column mean
numeric_columns = X_raw.select_dtypes(include=[np.number]).columns
X_raw[numeric_columns] = X_raw[numeric_columns].fillna(X_raw[numeric_columns].mean())

# -------- Build df for cleaning
df = X_raw.copy()
df['label'] = y
label_col = 'label'
print(f'Dataset: {df.shape[0]} rows, {df.shape[1]} cols')
print('Target column:', label_col)

# -------- Robust time/order split (use Timestamp if present; else use row order)
use_time_split = ('Timestamp' in df.columns)

if use_time_split:
    df['__ts'] = pd.to_datetime(df['Timestamp'], errors='coerce')
    df = df.sort_values('__ts')
else:
    df = df.reset_index(drop=True)

# -------- Drop identifiers (keep Timestamp only for sorting; do not use it as a feature)
drop_cols = ['Protocol', 'Flow_ID', 'Src_IP', 'Dst_IP', 'Src_Port', 'Dst_Port', 'Timestamp']
df = df.drop(columns=[c for c in drop_cols if c in df.columns], errors='ignore')

# -------- Feature matrix and target
X_df = df.drop(columns=[label_col]).copy()
y = df[label_col].values

# -------- Convert to numeric + clean inf/nan
for col in X_df.columns:
    X_df[col] = pd.to_numeric(X_df[col], errors='coerce')

X_df.replace([np.inf, -np.inf], np.nan, inplace=True)

# -------- Fix special columns if present
for special in ['Flow_Duration', 'Fwd_Header_Length']:
    if special in X_df.columns:
        bad = (X_df[special] <= 0) | pd.isna(X_df[special])
        med = X_df[special][X_df[special] > 0].median()
        X_df.loc[bad, special] = med if not np.isnan(med) else 0

# -------- Drop columns with too many NaNs
missing_ratio = X_df.isna().mean()
X_df = X_df.loc[:, missing_ratio <= 0.4]

# -------- Fill remaining NaNs
X_df = X_df.apply(lambda c: c.fillna(c.median()))
X_df = X_df.fillna(0)

# -------- Remove zero-variance features
vt = VarianceThreshold(threshold=0.0)
vt.fit(X_df.values)
X_df = X_df.iloc[:, vt.get_support(indices=True)]

# -------- Final valid rows
valid = ~pd.isna(y)
X_df, y = X_df.loc[valid], y[valid]

feature_names = list(X_df.columns)

# -------- Split: train first 80%, test last 20% (robust generalisation test)
# split_point = int(len(X_df) * 0.8)
# X_train_df = X_df.iloc[:split_point].copy()
# X_test_df  = X_df.iloc[split_point:].copy()
# y_train = y[:split_point]
# y_test  = y[split_point:]

#new
from sklearn.model_selection import train_test_split

X_train_df, X_test_df, y_train, y_test = train_test_split(
    X_df,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)




X = X_train_df.values.astype(float)
y = y_train
X_test = X_test_df.values.astype(float)

print(f'After cleaning:')
print(f'   - Train: {X.shape[0]} rows, {X.shape[1]} columns')
print(f'   - Test:  {X_test.shape[0]} rows, {X_test.shape[1]} columns')
print(f'   - NaNs in X_train: {np.isnan(X).sum()}')
print(f'   - NaNs in X_test:  {np.isnan(X_test).sum()}')

print(np.bincount(y_train))
print(np.bincount(y_test))

Loading and preprocessing dataset...
Loading data...

Dataset loaded successfully!
   - Total samples: 685671
   - Features: 93

Label distribution (%):
label2
benign        58.44
recon         15.44
dos            8.42
ddos           8.27
mitm           3.72
malware        3.53
web            1.32
bruteforce     0.88
Name: proportion, dtype: float64
   - Dropping 21 string columns for ML processing

/tmp/ipykernel_15863/4105004487.py:28: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  string_columns = combined_data.select_dtypes(include=['object']).columns.tolist()

Encoding used (multiclass): {'benign': 0, 'bruteforce': 1, 'ddos': 2, 'dos': 3, 'malware': 4, 'mitm': 5, 'recon': 6, 'web': 7}

Dataset: 685671 rows, 73 cols
Target column: label

After cleaning:
   - Train: 548536 rows, 51 columns
   - Test:  137135 rows, 51 columns
   - NaNs in X_train: 0
   - NaNs in X_test:  0
[320537   4813  45353  46189  19342  20392  84678   7232]
[80135  1203 11339 11547  4835  5098 21170  1808]

## Classification, Feature Count, Time, and Stability Evaluation

In [ ]:
import random
import time
import tracemalloc
from itertools import combinations
from sklearn.base import clone
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, f1_score, matthews_corrcoef, precision_score, recall_score
from sklearn.model_selection import StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

N_RUNS = 10
RUN_SEEDS = list(range(N_RUNS))
K_SUP = 10
N_FEATURES_TOTAL = int(X.shape[1])

FS_MAX_SAMPLES = 50000
FS_EPOCHS = 30
FS_POP_SIZE = 10
FS_CV_FOLDS = 3

FS_FITNESS_MODEL = 'DecisionTree'
FS_FITNESS_SCORING = 'f1_macro'

EVAL_CV_FOLDS = 3

def _subsample_for_fs_local(X_in: np.ndarray, y_in: np.ndarray, max_samples: int, seed: int):
    if (max_samples is None) or (X_in.shape[0] <= int(max_samples)):
        return X_in, y_in
    rng = np.random.default_rng(int(seed))
    idx = rng.choice(X_in.shape[0], size=int(max_samples), replace=False)
    return X_in[idx], y_in[idx]

def evaluate_cv_eff(clf, X_sub: np.ndarray, y_sub: np.ndarray, cv_folds: int, seed: int):
    cvk = StratifiedKFold(n_splits=int(cv_folds), shuffle=True, random_state=int(seed))

    accs, precs, recs, f1s, mccs = [], [], [], [], []
    train_time_s = 0.0
    infer_time_ms = 0.0

    tracemalloc.start()
    for tr, te in cvk.split(X_sub, y_sub):
        model = Pipeline([
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', StandardScaler(with_mean=True)),
            ('clf', clone(clf))
        ])

        t0 = time.perf_counter()
        model.fit(X_sub[tr], y_sub[tr])
        train_time_s += (time.perf_counter() - t0)

        t1 = time.perf_counter()
        p = model.predict(X_sub[te])
        infer_time_ms += (time.perf_counter() - t1) * 1000.0

        accs.append(accuracy_score(y_sub[te], p))
        precs.append(precision_score(y_sub[te], p, average='macro', zero_division=0))
        recs.append(recall_score(y_sub[te], p, average='macro', zero_division=0))
        f1s.append(f1_score(y_sub[te], p, average='macro', zero_division=0))
        mccs.append(matthews_corrcoef(y_sub[te], p))

    current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    return {
        'accuracy': float(np.mean(accs)),
        'precision_macro': float(np.mean(precs)),
        'recall_macro': float(np.mean(recs)),
        'f1_macro': float(np.mean(f1s)),
        'mcc': float(np.mean(mccs)),
        'train_time_s': float(train_time_s),
        'inference_time_ms': float(infer_time_ms),
        'peak_mem_mb': float(peak) / (1024.0 * 1024.0)
    }

methods = ['GWO', 'BA', 'LightGBM', 'Boruta']

clf_factories = {
    'RandomForest': lambda s: RandomForestClassifier(
        n_estimators=800,
        max_depth=30,
        min_samples_split=3,
        min_samples_leaf=1,
        max_features='sqrt',
        class_weight='balanced',
        max_samples=0.8,
        n_jobs=-1,
        random_state=42
    ),
    'DecisionTree': lambda s: DecisionTreeClassifier(random_state=int(s), class_weight='balanced'),
    'LogisticRegression': lambda s: LogisticRegression(max_iter=1000, class_weight='balanced', random_state=int(s)),
    'GaussianNB': lambda s: GaussianNB(),
    'HistGradientBoosting': lambda s: HistGradientBoostingClassifier(random_state=int(s), learning_rate=0.1),
    'MLP': lambda s: MLPClassifier(
        random_state=int(s),
        hidden_layer_sizes=(128, 64),
        max_iter=200,
        early_stopping=True,
        n_iter_no_change=10,
        validation_fraction=0.1
    )
}

fs_cache = {}

def make_fs_base(seed: int):
    if str(FS_FITNESS_MODEL).lower() in ['rf', 'randomforest', 'random_forest']:
        return RandomForestClassifier(
            n_estimators=120,
            max_depth=18,
            min_samples_split=4,
            min_samples_leaf=2,
            max_features='sqrt',
            bootstrap=True,
            max_samples=0.7,
            class_weight='balanced_subsample',
            n_jobs=-1,
            random_state=int(seed)
        )
    return DecisionTreeClassifier(random_state=int(seed), class_weight='balanced')

def _serialize_idx(idx):
    return ','.join(str(int(i)) for i in idx)

def _mean_pairwise_jaccard(index_sets):
    sets = [set(int(i) for i in s) for s in index_sets if len(s) > 0]
    if len(sets) < 2:
        return np.nan, np.nan, 0
    vals = []
    for a, b in combinations(sets, 2):
        union = len(a | b)
        vals.append(len(a & b) / union if union else 1.0)
    return float(np.mean(vals)), float(np.std(vals)), int(len(vals))

def get_idx_and_time(seed: int, method: str, X_fs: np.ndarray, y_fs: np.ndarray):
    key = (int(seed), str(method))
    if key in fs_cache:
        return fs_cache[key]

    random.seed(int(seed))
    np.random.seed(int(seed))

    base = make_fs_base(int(seed))
    t0 = time.perf_counter()
    if str(method) == 'GWO':
        idx, _ = select_features_gwo(X_fs, y_fs, K_SUP, clf=base, epochs=FS_EPOCHS, pop_size=FS_POP_SIZE, cv=FS_CV_FOLDS, scoring=str(FS_FITNESS_SCORING), seed=int(seed))
    elif str(method) == 'BA':
        idx, _ = select_features_ba(X_fs, y_fs, K_SUP, clf=base, epochs=FS_EPOCHS, pop_size=FS_POP_SIZE, cv=FS_CV_FOLDS, scoring=str(FS_FITNESS_SCORING))
    elif str(method) == 'LightGBM':
        idx, _ = select_features_lightgbm(X_fs, y_fs, K_SUP, clf=base, cv=FS_CV_FOLDS, scoring=str(FS_FITNESS_SCORING), seed=int(seed))
    elif str(method) == 'Boruta':
        idx, _ = select_features_boruta(X_fs, y_fs, None, clf=base, cv=FS_CV_FOLDS, scoring=str(FS_FITNESS_SCORING), seed=int(seed))
    else:
        raise ValueError(f'Unknown method: {method}')

    fs_time_s = float(time.perf_counter() - t0)
    fs_cache[key] = (idx, fs_time_s)
    return idx, fs_time_s

rows = []
for seed in RUN_SEEDS:
    X_fs, y_fs = _subsample_for_fs_local(X, y, FS_MAX_SAMPLES, seed)
    for method in methods:
        idx, fs_time_s = get_idx_and_time(seed, method, X_fs, y_fs)
        X_sub = X[:, idx]
        for clf_name, make_clf in clf_factories.items():
            m = evaluate_cv_eff(make_clf(seed), X_sub, y, cv_folds=EVAL_CV_FOLDS, seed=seed)
            rows.append({
                'seed': int(seed),
                'method': str(method),
                'classifier': str(clf_name),
                'k_target': int(K_SUP) if method in ['GWO', 'BA', 'LightGBM'] else np.nan,
                'n_selected': int(len(idx)),
                'selected_features': _serialize_idx(idx),
                'fs_time_s': float(fs_time_s),
                **m
            })

fs_rows = []
for (s, m), (idx, fs_time_s) in fs_cache.items():
    fs_rows.append({
        'seed': int(s),
        'method': str(m),
        'k_target': int(K_SUP) if str(m) in ['GWO', 'BA', 'LightGBM'] else np.nan,
        'n_selected': int(len(idx)),
        'selected_features': _serialize_idx(idx),
        'fs_time_s': float(fs_time_s)
    })
fs_df = pd.DataFrame(fs_rows)
fs_df = fs_df.sort_values(['seed', 'method']).reset_index(drop=True)
display(fs_df)
display(fs_df.groupby('method', as_index=False)[['fs_time_s', 'n_selected']].agg(['mean', 'std']).reset_index())

stability_rows = []
for method_name, sub_df in fs_df.groupby('method'):
    sets = []
    for txt in sub_df['selected_features'].astype(str):
        sets.append([int(x) for x in txt.split(',') if str(x).strip() != ''])
    mean_j, std_j, n_pairs = _mean_pairwise_jaccard(sets)
    stability_rows.append({
        'method': str(method_name),
        'mean_pairwise_jaccard': mean_j,
        'std_pairwise_jaccard': std_j,
        'n_pairs': n_pairs
    })
stability_df = pd.DataFrame(stability_rows).sort_values('mean_pairwise_jaccard', ascending=False).reset_index(drop=True)
print('Feature-selection stability across runs')
display(stability_df)

raw_df = pd.DataFrame(rows)
display(raw_df)
print('Rows:', len(raw_df))

metrics_cols = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro', 'mcc', 'fs_time_s', 'train_time_s', 'inference_time_ms', 'peak_mem_mb', 'n_selected']

means = raw_df.groupby(['method', 'classifier'])[metrics_cols].mean().reset_index()
means = means.rename(columns={
    'method': 'Algorithm',
    'classifier': 'Classifier',
    'accuracy': 'Accuracy',
    'precision_macro': 'Precision',
    'recall_macro': 'Recall',
    'f1_macro': 'F1_macro',
    'mcc': 'MCC',
    'n_selected': 'N_Selected'
})

eval_df = means[['Algorithm', 'Classifier', 'Accuracy', 'Precision', 'Recall', 'F1_macro', 'MCC', 'N_Selected', 'fs_time_s', 'train_time_s', 'inference_time_ms', 'peak_mem_mb']].copy()
eval_df = eval_df.sort_values(['F1_macro', 'MCC', 'Accuracy'], ascending=[False, False, False]).reset_index(drop=True)
display(eval_df)

print('Deployment-oriented summary (lower downstream cost is better)')
deployment_df = eval_df[['Algorithm', 'Classifier', 'N_Selected', 'train_time_s', 'inference_time_ms', 'peak_mem_mb']].copy()
deployment_df = deployment_df.sort_values(['N_Selected', 'peak_mem_mb', 'inference_time_ms', 'train_time_s'], ascending=[True, True, True, True]).reset_index(drop=True)
display(deployment_df)

agg = raw_df.groupby(['method', 'classifier'])[metrics_cols].agg(['mean', 'std'])
agg.columns = [f"{m}_{s}" for (m, s) in agg.columns]
agg = agg.reset_index()

def fmt_pair(m, s, is_time=False):
    if pd.isna(m):
        return ''
    if pd.isna(s):
        return f"{m:.4f}" if not is_time else f"{m:.3f}"
    return (f"{m:.4f} +- {s:.4f}" if not is_time else f"{m:.3f} +- {s:.3f}")

final_table = pd.DataFrame({
    'Method': agg['method'].astype(str),
    'Classifier': agg['classifier'].astype(str),
})

for src, dst in {
    'accuracy': 'accuracy',
    'precision_macro': 'precision_macro',
    'recall_macro': 'recall_macro',
    'f1_macro': 'f1_macro',
    'mcc': 'mcc',
    'n_selected': 'n_selected',
    'fs_time_s': 'fs_time_s',
    'train_time_s': 'train_time_s',
    'inference_time_ms': 'inference_time_ms',
    'peak_mem_mb': 'peak_mem_mb'
}.items():
    mcol = f"{src}_mean"
    scol = f"{src}_std"
    is_time = src in ['fs_time_s', 'train_time_s', 'inference_time_ms', 'peak_mem_mb']
    final_table[dst] = [fmt_pair(m, s, is_time=is_time) for m, s in zip(agg[mcol], agg[scol])]

final_table = final_table.sort_values(['Classifier', 'Method']).reset_index(drop=True)
display(final_table)

2026/06/08 05:06:45 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/08 05:06:56 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8342468959884574, Global best: 0.8342468959884574, Runtime: 4.70012 seconds

2026/06/08 05:07:01 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8443930702359732, Global best: 0.8443930702359732, Runtime: 5.70769 seconds

2026/06/08 05:07:07 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8529790693294942, Global best: 0.8529790693294942, Runtime: 5.26384 seconds

2026/06/08 05:07:12 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8529790693294942, Global best: 0.8529790693294942, Runtime: 5.57213 seconds

2026/06/08 05:07:18 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8558015546511424, Global best: 0.8558015546511424, Runtime: 5.46516 seconds

2026/06/08 05:07:23 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8654252548711727, Global best: 0.8654252548711727, Runtime: 4.93269 seconds

2026/06/08 05:07:28 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8669244357107458, Global best: 0.8669244357107458, Runtime: 5.14106 seconds

2026/06/08 05:07:32 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8669244357107458, Global best: 0.8669244357107458, Runtime: 4.68155 seconds

2026/06/08 05:07:37 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8669244357107458, Global best: 0.8669244357107458, Runtime: 4.86748 seconds

2026/06/08 05:07:43 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8697078601850912, Global best: 0.8697078601850912, Runtime: 5.28238 seconds

2026/06/08 05:07:48 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8724284618845755, Global best: 0.8724284618845755, Runtime: 5.07282 seconds

2026/06/08 05:07:53 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8724284618845755, Global best: 0.8724284618845755, Runtime: 4.80273 seconds

2026/06/08 05:07:58 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.872460998130424, Global best: 0.872460998130424, Runtime: 5.40861 seconds

2026/06/08 05:08:04 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8740891986586611, Global best: 0.8740891986586611, Runtime: 5.88809 seconds

2026/06/08 05:08:09 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8795953668757719, Global best: 0.8795953668757719, Runtime: 5.26192 seconds

2026/06/08 05:08:14 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8795953668757719, Global best: 0.8795953668757719, Runtime: 4.65752 seconds

2026/06/08 05:08:18 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8795953668757719, Global best: 0.8795953668757719, Runtime: 4.72760 seconds

2026/06/08 05:08:23 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8795953668757719, Global best: 0.8795953668757719, Runtime: 4.29256 seconds

2026/06/08 05:08:28 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8796363067750386, Global best: 0.8796363067750386, Runtime: 4.85201 seconds

2026/06/08 05:08:33 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8808421229831647, Global best: 0.8808421229831647, Runtime: 4.90112 seconds

2026/06/08 05:08:37 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8808421229831647, Global best: 0.8808421229831647, Runtime: 4.56724 seconds

2026/06/08 05:08:42 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8808421229831647, Global best: 0.8808421229831647, Runtime: 4.55937 seconds

2026/06/08 05:08:46 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8817479219541664, Global best: 0.8817479219541664, Runtime: 4.39367 seconds

2026/06/08 05:08:52 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8837197321907815, Global best: 0.8837197321907815, Runtime: 5.76291 seconds

2026/06/08 05:08:59 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8837197321907815, Global best: 0.8837197321907815, Runtime: 7.00736 seconds

2026/06/08 05:09:07 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8837197321907815, Global best: 0.8837197321907815, Runtime: 8.28971 seconds

2026/06/08 05:09:12 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8837197321907815, Global best: 0.8837197321907815, Runtime: 5.32271 seconds

2026/06/08 05:09:18 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8837197321907815, Global best: 0.8837197321907815, Runtime: 5.17603 seconds

2026/06/08 05:09:23 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8837197321907815, Global best: 0.8837197321907815, Runtime: 5.32995 seconds

2026/06/08 05:09:28 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8837197321907815, Global best: 0.8837197321907815, Runtime: 5.16376 seconds

2026/06/08 06:10:33 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/08 06:10:42 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8425954768537888, Global best: 0.8425954768537888, Runtime: 4.12416 seconds

2026/06/08 06:10:47 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.84330135920673, Global best: 0.84330135920673, Runtime: 4.50195 seconds

2026/06/08 06:10:53 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.84330135920673, Global best: 0.84330135920673, Runtime: 6.29244 seconds

2026/06/08 06:10:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.84330135920673, Global best: 0.84330135920673, Runtime: 4.64149 seconds

2026/06/08 06:11:02 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.84330135920673, Global best: 0.84330135920673, Runtime: 3.82024 seconds

2026/06/08 06:11:06 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8441487554979885, Global best: 0.8441487554979885, Runtime: 4.08130 seconds

2026/06/08 06:11:10 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.844578685834484, Global best: 0.844578685834484, Runtime: 4.26357 seconds

2026/06/08 06:11:14 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.844578685834484, Global best: 0.844578685834484, Runtime: 3.88879 seconds

2026/06/08 06:11:18 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.844578685834484, Global best: 0.844578685834484, Runtime: 4.23618 seconds

2026/06/08 06:11:22 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.844578685834484, Global best: 0.844578685834484, Runtime: 4.19814 seconds

2026/06/08 06:11:27 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.844578685834484, Global best: 0.844578685834484, Runtime: 5.11038 seconds

2026/06/08 06:11:33 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.844578685834484, Global best: 0.844578685834484, Runtime: 5.26111 seconds

2026/06/08 06:11:39 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.844578685834484, Global best: 0.844578685834484, Runtime: 6.56619 seconds

2026/06/08 06:11:45 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.844578685834484, Global best: 0.844578685834484, Runtime: 5.49356 seconds

2026/06/08 06:11:50 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.844578685834484, Global best: 0.844578685834484, Runtime: 4.83041 seconds

2026/06/08 06:11:54 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.844578685834484, Global best: 0.844578685834484, Runtime: 4.60624 seconds

2026/06/08 06:11:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.844578685834484, Global best: 0.844578685834484, Runtime: 3.92420 seconds

2026/06/08 06:12:03 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8459902516949644, Global best: 0.8459902516949644, Runtime: 4.43278 seconds

2026/06/08 06:12:07 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8459902516949644, Global best: 0.8459902516949644, Runtime: 4.33630 seconds

2026/06/08 06:12:11 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8459902516949644, Global best: 0.8459902516949644, Runtime: 4.10171 seconds

2026/06/08 06:12:15 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8493488320639356, Global best: 0.8493488320639356, Runtime: 4.38495 seconds

2026/06/08 06:12:19 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8494008248657413, Global best: 0.8494008248657413, Runtime: 4.03598 seconds

2026/06/08 06:12:24 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8494008248657413, Global best: 0.8494008248657413, Runtime: 4.99652 seconds

2026/06/08 06:12:29 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8494008248657413, Global best: 0.8494008248657413, Runtime: 4.91523 seconds

2026/06/08 06:12:34 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8494008248657413, Global best: 0.8494008248657413, Runtime: 4.48968 seconds

2026/06/08 06:12:38 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8494008248657413, Global best: 0.8494008248657413, Runtime: 4.59427 seconds

2026/06/08 06:12:42 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8494008248657413, Global best: 0.8494008248657413, Runtime: 3.88060 seconds

2026/06/08 06:12:46 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8494008248657413, Global best: 0.8494008248657413, Runtime: 4.11593 seconds

2026/06/08 06:12:51 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8494008248657413, Global best: 0.8494008248657413, Runtime: 4.81741 seconds

2026/06/08 06:12:56 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8494008248657413, Global best: 0.8494008248657413, Runtime: 4.42915 seconds

2026/06/09 12:25:26 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/09 12:25:38 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8542300036252246, Global best: 0.8542300036252246, Runtime: 6.46401 seconds

2026/06/09 12:25:44 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8542300036252246, Global best: 0.8542300036252246, Runtime: 5.73196 seconds

2026/06/09 12:25:49 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8727846878482324, Global best: 0.8727846878482324, Runtime: 5.02909 seconds

2026/06/09 12:25:54 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8731452129634535, Global best: 0.8731452129634535, Runtime: 5.12470 seconds

2026/06/09 12:25:59 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8761773143032312, Global best: 0.8761773143032312, Runtime: 5.31109 seconds

2026/06/09 12:26:09 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8761773143032312, Global best: 0.8761773143032312, Runtime: 9.46591 seconds

2026/06/09 12:26:16 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8762790601881705, Global best: 0.8762790601881705, Runtime: 7.24314 seconds

2026/06/09 12:26:22 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8774199333114875, Global best: 0.8774199333114875, Runtime: 6.11947 seconds

2026/06/09 12:26:29 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8803515438256041, Global best: 0.8803515438256041, Runtime: 6.54600 seconds

2026/06/09 12:26:34 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8803515438256041, Global best: 0.8803515438256041, Runtime: 5.65479 seconds

2026/06/09 12:26:41 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8834853706122521, Global best: 0.8834853706122521, Runtime: 6.84935 seconds

2026/06/09 12:26:49 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8834853706122521, Global best: 0.8834853706122521, Runtime: 7.24080 seconds

2026/06/09 12:26:55 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.885625482325001, Global best: 0.885625482325001, Runtime: 5.99157 seconds

2026/06/09 12:27:03 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.885625482325001, Global best: 0.885625482325001, Runtime: 8.22694 seconds

2026/06/09 12:27:13 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8874372611586432, Global best: 0.8874372611586432, Runtime: 10.51238 seconds

2026/06/09 12:27:19 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8876584915941891, Global best: 0.8876584915941891, Runtime: 5.94323 seconds

2026/06/09 12:27:25 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8876584915941891, Global best: 0.8876584915941891, Runtime: 5.42288 seconds

2026/06/09 12:27:30 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.888957753732153, Global best: 0.888957753732153, Runtime: 5.29864 seconds

2026/06/09 12:27:36 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.888957753732153, Global best: 0.888957753732153, Runtime: 5.87646 seconds

2026/06/09 12:27:41 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.888993321657445, Global best: 0.888993321657445, Runtime: 5.37606 seconds

2026/06/09 12:27:47 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.888993321657445, Global best: 0.888993321657445, Runtime: 5.76872 seconds

2026/06/09 12:27:53 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8897141519435858, Global best: 0.8897141519435858, Runtime: 5.87238 seconds

2026/06/09 12:27:59 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8903214329712488, Global best: 0.8903214329712488, Runtime: 6.32588 seconds

2026/06/09 12:28:05 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8903943482339212, Global best: 0.8903943482339212, Runtime: 5.56999 seconds

2026/06/09 12:28:10 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8903943482339212, Global best: 0.8903943482339212, Runtime: 5.63288 seconds

2026/06/09 12:28:18 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8908794896586749, Global best: 0.8908794896586749, Runtime: 7.72905 seconds

2026/06/09 12:28:24 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.891963264100165, Global best: 0.891963264100165, Runtime: 6.04372 seconds

2026/06/09 12:28:30 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.891963264100165, Global best: 0.891963264100165, Runtime: 5.89511 seconds

2026/06/09 12:28:36 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8924926758648709, Global best: 0.8924926758648709, Runtime: 5.73882 seconds

2026/06/09 12:28:43 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8926397346884003, Global best: 0.8926397346884003, Runtime: 7.27062 seconds

2026/06/09 01:40:32 AM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/09 01:40:43 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8643915466715061, Global best: 0.8643915466715061, Runtime: 5.55527 seconds

2026/06/09 01:40:50 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8643915466715061, Global best: 0.8643915466715061, Runtime: 7.37218 seconds

2026/06/09 01:40:57 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8643915466715061, Global best: 0.8643915466715061, Runtime: 6.48352 seconds

2026/06/09 01:41:01 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8643915466715061, Global best: 0.8643915466715061, Runtime: 4.54361 seconds

2026/06/09 01:41:06 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8659834288395455, Global best: 0.8659834288395455, Runtime: 5.05578 seconds

2026/06/09 01:41:11 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8659834288395455, Global best: 0.8659834288395455, Runtime: 4.40106 seconds

2026/06/09 01:41:17 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8659834288395455, Global best: 0.8659834288395455, Runtime: 6.38217 seconds

2026/06/09 01:41:22 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8660173099778421, Global best: 0.8660173099778421, Runtime: 4.99707 seconds

2026/06/09 01:41:27 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.45838 seconds

2026/06/09 01:41:31 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.63391 seconds

2026/06/09 01:41:36 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.38716 seconds

2026/06/09 01:41:41 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 5.24116 seconds

2026/06/09 01:41:45 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.51780 seconds

2026/06/09 01:41:50 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.19516 seconds

2026/06/09 01:41:54 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.38315 seconds

2026/06/09 01:41:58 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.40239 seconds

2026/06/09 01:42:05 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 6.63639 seconds

2026/06/09 01:42:09 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.02559 seconds

2026/06/09 01:42:13 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.33032 seconds

2026/06/09 01:42:18 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.49484 seconds

2026/06/09 01:42:22 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.09192 seconds

2026/06/09 01:42:26 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.34442 seconds

2026/06/09 01:42:30 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.16019 seconds

2026/06/09 01:42:35 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.16713 seconds

2026/06/09 01:42:39 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.06551 seconds

2026/06/09 01:42:43 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.35012 seconds

2026/06/09 01:42:47 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 3.77627 seconds

2026/06/09 01:42:51 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.44489 seconds

2026/06/09 01:42:55 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.05395 seconds

2026/06/09 01:43:00 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8672465911892634, Global best: 0.8672465911892634, Runtime: 4.17625 seconds

2026/06/09 07:50:47 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/09 07:50:59 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.875493403335075, Global best: 0.875493403335075, Runtime: 5.95475 seconds

2026/06/09 07:51:06 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8766555663571325, Global best: 0.8766555663571325, Runtime: 7.23045 seconds

2026/06/09 07:51:13 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8780939348541135, Global best: 0.8780939348541135, Runtime: 7.14384 seconds

2026/06/09 07:51:22 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8780939348541135, Global best: 0.8780939348541135, Runtime: 9.14056 seconds

2026/06/09 07:51:29 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8817586607982185, Global best: 0.8817586607982185, Runtime: 7.01150 seconds

2026/06/09 07:51:36 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8817586607982185, Global best: 0.8817586607982185, Runtime: 6.94278 seconds

2026/06/09 07:51:43 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8817586607982185, Global best: 0.8817586607982185, Runtime: 7.00257 seconds

2026/06/09 07:51:49 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8856609335797123, Global best: 0.8856609335797123, Runtime: 5.20053 seconds

2026/06/09 07:51:54 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8872993939837359, Global best: 0.8872993939837359, Runtime: 5.41485 seconds

2026/06/09 07:52:00 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8872993939837359, Global best: 0.8872993939837359, Runtime: 5.54576 seconds

2026/06/09 07:52:05 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8872993939837359, Global best: 0.8872993939837359, Runtime: 5.56789 seconds

2026/06/09 07:52:11 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8877026180873253, Global best: 0.8877026180873253, Runtime: 6.00622 seconds

2026/06/09 07:52:16 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8877026180873253, Global best: 0.8877026180873253, Runtime: 5.25302 seconds

2026/06/09 07:52:22 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8877026180873253, Global best: 0.8877026180873253, Runtime: 5.27523 seconds

2026/06/09 07:52:27 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8877026180873253, Global best: 0.8877026180873253, Runtime: 5.31887 seconds

2026/06/09 07:52:32 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8877026180873253, Global best: 0.8877026180873253, Runtime: 5.31748 seconds

2026/06/09 07:52:38 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8885618124582061, Global best: 0.8885618124582061, Runtime: 5.28156 seconds

2026/06/09 07:52:43 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8890748922224091, Global best: 0.8890748922224091, Runtime: 5.32716 seconds

2026/06/09 07:52:48 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8896840049770105, Global best: 0.8896840049770105, Runtime: 5.02955 seconds

2026/06/09 07:52:54 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8896840049770105, Global best: 0.8896840049770105, Runtime: 5.66306 seconds

2026/06/09 07:52:59 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8905539624557977, Global best: 0.8905539624557977, Runtime: 5.11477 seconds

2026/06/09 07:53:04 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8905539624557977, Global best: 0.8905539624557977, Runtime: 5.49217 seconds

2026/06/09 07:53:10 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8907306135885613, Global best: 0.8907306135885613, Runtime: 5.23082 seconds

2026/06/09 07:53:15 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8907306135885613, Global best: 0.8907306135885613, Runtime: 4.99497 seconds

2026/06/09 07:53:19 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8912126675604052, Global best: 0.8912126675604052, Runtime: 4.87204 seconds

2026/06/09 07:53:25 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8917403172004489, Global best: 0.8917403172004489, Runtime: 5.22734 seconds

2026/06/09 07:53:29 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8921271016926536, Global best: 0.8921271016926536, Runtime: 4.82375 seconds

2026/06/09 07:53:35 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8929068933674793, Global best: 0.8929068933674793, Runtime: 5.36169 seconds

2026/06/09 07:53:40 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8930454095348324, Global best: 0.8930454095348324, Runtime: 5.09755 seconds

2026/06/09 07:53:45 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8930454095348324, Global best: 0.8930454095348324, Runtime: 5.13568 seconds

2026/06/09 09:12:18 AM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/09 09:12:26 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8226726145719343, Global best: 0.8226726145719343, Runtime: 4.02710 seconds

2026/06/09 09:12:30 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8226726145719343, Global best: 0.8226726145719343, Runtime: 3.97123 seconds

2026/06/09 09:12:34 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8241514740821047, Global best: 0.8241514740821047, Runtime: 4.03123 seconds

2026/06/09 09:12:38 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8241514740821047, Global best: 0.8241514740821047, Runtime: 4.02673 seconds

2026/06/09 09:12:42 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8241514740821047, Global best: 0.8241514740821047, Runtime: 3.69340 seconds

2026/06/09 09:12:46 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8241514740821047, Global best: 0.8241514740821047, Runtime: 4.40751 seconds

2026/06/09 09:12:51 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8241514740821047, Global best: 0.8241514740821047, Runtime: 4.58492 seconds

2026/06/09 09:12:57 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8241514740821047, Global best: 0.8241514740821047, Runtime: 5.85084 seconds

2026/06/09 09:13:01 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8249520009871745, Global best: 0.8249520009871745, Runtime: 3.80005 seconds

2026/06/09 09:13:05 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8249520009871745, Global best: 0.8249520009871745, Runtime: 4.17764 seconds

2026/06/09 09:13:09 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8249520009871745, Global best: 0.8249520009871745, Runtime: 3.86035 seconds

2026/06/09 09:13:13 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8249520009871745, Global best: 0.8249520009871745, Runtime: 4.39936 seconds

2026/06/09 09:13:17 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 3.70904 seconds

2026/06/09 09:13:21 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 3.85370 seconds

2026/06/09 09:13:25 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 4.08619 seconds

2026/06/09 09:13:29 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 4.40884 seconds

2026/06/09 09:13:33 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 3.89072 seconds

2026/06/09 09:13:37 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 3.52440 seconds

2026/06/09 09:13:41 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 4.33158 seconds

2026/06/09 09:13:45 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 4.16549 seconds

2026/06/09 09:13:49 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 3.75751 seconds

2026/06/09 09:13:53 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 3.69259 seconds

2026/06/09 09:13:57 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 3.87747 seconds

2026/06/09 09:14:00 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 3.72233 seconds

2026/06/09 09:14:04 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 3.55081 seconds

2026/06/09 09:14:08 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 4.26402 seconds

2026/06/09 09:14:12 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 3.99848 seconds

2026/06/09 09:14:16 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 4.21176 seconds

2026/06/09 09:14:21 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 4.90963 seconds

2026/06/09 09:14:25 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8274208429060788, Global best: 0.8274208429060788, Runtime: 4.21556 seconds

2026/06/09 02:16:55 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/09 02:17:07 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.85684997091715, Global best: 0.85684997091715, Runtime: 6.70274 seconds

2026/06/09 02:17:14 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8579121483705515, Global best: 0.8579121483705515, Runtime: 6.95797 seconds

2026/06/09 02:17:20 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8579121483705515, Global best: 0.8579121483705515, Runtime: 6.28669 seconds

2026/06/09 02:17:26 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8684314928763941, Global best: 0.8684314928763941, Runtime: 5.78066 seconds

2026/06/09 02:17:32 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8777587451069564, Global best: 0.8777587451069564, Runtime: 6.03342 seconds

2026/06/09 02:17:41 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8783598898501361, Global best: 0.8783598898501361, Runtime: 9.37847 seconds

2026/06/09 02:17:49 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8790744131109772, Global best: 0.8790744131109772, Runtime: 7.25627 seconds

2026/06/09 02:17:56 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8790744131109772, Global best: 0.8790744131109772, Runtime: 7.26027 seconds

2026/06/09 02:18:03 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8812735241257009, Global best: 0.8812735241257009, Runtime: 7.31449 seconds

2026/06/09 02:18:10 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8812735241257009, Global best: 0.8812735241257009, Runtime: 7.13499 seconds

2026/06/09 02:18:17 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8812735241257009, Global best: 0.8812735241257009, Runtime: 6.55416 seconds

2026/06/09 02:18:25 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8812735241257009, Global best: 0.8812735241257009, Runtime: 8.04716 seconds

2026/06/09 02:18:32 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8812735241257009, Global best: 0.8812735241257009, Runtime: 6.75507 seconds

2026/06/09 02:18:38 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8812735241257009, Global best: 0.8812735241257009, Runtime: 6.59094 seconds

2026/06/09 02:18:45 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8812735241257009, Global best: 0.8812735241257009, Runtime: 6.88727 seconds

2026/06/09 02:18:52 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8862462256103075, Global best: 0.8862462256103075, Runtime: 6.71636 seconds

2026/06/09 02:18:59 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8862462256103075, Global best: 0.8862462256103075, Runtime: 6.50192 seconds

2026/06/09 02:19:05 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8862462256103075, Global best: 0.8862462256103075, Runtime: 6.27681 seconds

2026/06/09 02:19:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8873406509295475, Global best: 0.8873406509295475, Runtime: 8.63496 seconds

2026/06/09 02:19:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8874297178291072, Global best: 0.8874297178291072, Runtime: 7.83833 seconds

2026/06/09 02:19:27 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8874323217664795, Global best: 0.8874323217664795, Runtime: 5.89764 seconds

2026/06/09 02:19:35 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8883623779199196, Global best: 0.8883623779199196, Runtime: 7.50298 seconds

2026/06/09 02:19:42 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8897387868197211, Global best: 0.8897387868197211, Runtime: 7.20521 seconds

2026/06/09 02:19:48 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8898451857311697, Global best: 0.8898451857311697, Runtime: 6.06667 seconds

2026/06/09 02:19:54 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8906649660791335, Global best: 0.8906649660791335, Runtime: 6.06238 seconds

2026/06/09 02:20:00 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8906649660791335, Global best: 0.8906649660791335, Runtime: 5.65848 seconds

2026/06/09 02:20:06 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8907341488542756, Global best: 0.8907341488542756, Runtime: 6.24082 seconds

2026/06/09 02:20:12 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8916055983204514, Global best: 0.8916055983204514, Runtime: 6.47079 seconds

2026/06/09 02:20:20 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8925510704758305, Global best: 0.8925510704758305, Runtime: 8.03957 seconds

2026/06/09 02:20:27 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8925510704758305, Global best: 0.8925510704758305, Runtime: 6.63235 seconds

2026/06/09 04:18:26 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/09 04:18:36 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8485428210117373, Global best: 0.8485428210117373, Runtime: 3.97315 seconds

2026/06/09 04:18:41 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8485428210117373, Global best: 0.8485428210117373, Runtime: 4.33519 seconds

2026/06/09 04:18:45 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8500284355333584, Global best: 0.8500284355333584, Runtime: 4.23004 seconds

2026/06/09 04:18:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8500284355333584, Global best: 0.8500284355333584, Runtime: 4.19594 seconds

2026/06/09 04:18:54 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8500284355333584, Global best: 0.8500284355333584, Runtime: 4.41255 seconds

2026/06/09 04:18:59 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 4.91745 seconds

2026/06/09 04:19:04 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 5.42702 seconds

2026/06/09 04:19:08 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 4.40714 seconds

2026/06/09 04:19:13 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 4.12435 seconds

2026/06/09 04:19:18 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 5.15458 seconds

2026/06/09 04:19:22 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 4.57403 seconds

2026/06/09 04:19:27 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 4.91664 seconds

2026/06/09 04:19:32 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 5.02998 seconds

2026/06/09 04:19:37 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 5.03685 seconds

2026/06/09 04:19:43 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 5.44753 seconds

2026/06/09 04:19:48 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 5.24245 seconds

2026/06/09 04:19:53 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 5.52234 seconds

2026/06/09 04:19:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 4.34518 seconds

2026/06/09 04:20:03 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 4.85802 seconds

2026/06/09 04:20:08 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 4.83293 seconds

2026/06/09 04:20:14 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 6.31069 seconds

2026/06/09 04:20:19 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 5.22821 seconds

2026/06/09 04:20:25 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 6.05620 seconds

2026/06/09 04:20:30 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 4.42061 seconds

2026/06/09 04:20:35 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 5.79676 seconds

2026/06/09 04:20:40 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 4.40209 seconds

2026/06/09 04:20:47 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 7.34722 seconds

2026/06/09 04:20:53 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8512265565981988, Global best: 0.8512265565981988, Runtime: 5.63971 seconds

2026/06/09 04:21:01 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8513403220493552, Global best: 0.8513403220493552, Runtime: 7.80834 seconds

2026/06/09 04:21:06 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8513403220493552, Global best: 0.8513403220493552, Runtime: 5.88030 seconds

2026/06/09 11:23:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/09 11:23:22 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8591611425727689, Global best: 0.8591611425727689, Runtime: 4.84712 seconds

2026/06/09 11:23:29 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8591611425727689, Global best: 0.8591611425727689, Runtime: 6.14986 seconds

2026/06/09 11:23:33 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8651026507526174, Global best: 0.8651026507526174, Runtime: 4.81514 seconds

2026/06/09 11:23:39 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8703803318948543, Global best: 0.8703803318948543, Runtime: 5.11854 seconds

2026/06/09 11:23:44 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8703803318948543, Global best: 0.8703803318948543, Runtime: 5.66405 seconds

2026/06/09 11:23:51 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8826870759563314, Global best: 0.8826870759563314, Runtime: 6.83823 seconds

2026/06/09 11:23:57 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8826870759563314, Global best: 0.8826870759563314, Runtime: 5.76256 seconds

2026/06/09 11:24:03 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8826870759563314, Global best: 0.8826870759563314, Runtime: 6.31570 seconds

2026/06/09 11:24:10 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8826870759563314, Global best: 0.8826870759563314, Runtime: 7.04729 seconds

2026/06/09 11:24:16 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8841805537322277, Global best: 0.8841805537322277, Runtime: 5.40109 seconds

2026/06/09 11:24:23 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8845194357487793, Global best: 0.8845194357487793, Runtime: 7.66310 seconds

2026/06/09 11:24:29 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8845194357487793, Global best: 0.8845194357487793, Runtime: 5.93502 seconds

2026/06/09 11:24:35 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8846469974560985, Global best: 0.8846469974560985, Runtime: 6.25073 seconds

2026/06/09 11:24:43 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8881765776041557, Global best: 0.8881765776041557, Runtime: 7.92379 seconds

2026/06/09 11:24:53 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8881765776041557, Global best: 0.8881765776041557, Runtime: 9.58346 seconds

2026/06/09 11:25:00 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8881765776041557, Global best: 0.8881765776041557, Runtime: 7.46050 seconds

2026/06/09 11:25:09 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8903354421995929, Global best: 0.8903354421995929, Runtime: 8.63547 seconds

2026/06/09 11:25:18 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8903354421995929, Global best: 0.8903354421995929, Runtime: 8.51744 seconds

2026/06/09 11:25:27 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8903354421995929, Global best: 0.8903354421995929, Runtime: 8.94690 seconds

2026/06/09 11:25:34 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8903354421995929, Global best: 0.8903354421995929, Runtime: 7.72244 seconds

2026/06/09 11:25:42 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8905778332717788, Global best: 0.8905778332717788, Runtime: 7.54389 seconds

2026/06/09 11:25:48 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8907798338686065, Global best: 0.8907798338686065, Runtime: 6.29593 seconds

2026/06/09 11:25:56 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8907798338686065, Global best: 0.8907798338686065, Runtime: 7.45566 seconds

2026/06/09 11:26:04 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8918337279214487, Global best: 0.8918337279214487, Runtime: 8.53366 seconds

2026/06/09 11:26:11 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8918606758477774, Global best: 0.8918606758477774, Runtime: 6.43222 seconds

2026/06/09 11:26:18 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8918606758477774, Global best: 0.8918606758477774, Runtime: 7.15218 seconds

2026/06/09 11:26:25 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8924251001244554, Global best: 0.8924251001244554, Runtime: 7.23806 seconds

2026/06/09 11:26:32 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8926723107524632, Global best: 0.8926723107524632, Runtime: 6.68942 seconds

2026/06/09 11:26:39 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.892758579056973, Global best: 0.892758579056973, Runtime: 7.43213 seconds

2026/06/09 11:26:47 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.892758579056973, Global best: 0.892758579056973, Runtime: 7.69461 seconds

2026/06/10 12:51:49 AM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/10 12:52:01 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8556227601097136, Global best: 0.8556227601097136, Runtime: 5.06502 seconds

2026/06/10 12:52:07 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8556227601097136, Global best: 0.8556227601097136, Runtime: 5.68480 seconds

2026/06/10 12:52:11 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8556227601097136, Global best: 0.8556227601097136, Runtime: 4.19874 seconds

2026/06/10 12:52:16 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8568874659920666, Global best: 0.8568874659920666, Runtime: 4.94617 seconds

2026/06/10 12:52:20 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8570639365803019, Global best: 0.8570639365803019, Runtime: 4.55168 seconds

2026/06/10 12:52:25 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8570639365803019, Global best: 0.8570639365803019, Runtime: 4.25293 seconds

2026/06/10 12:52:29 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8570639365803019, Global best: 0.8570639365803019, Runtime: 4.50907 seconds

2026/06/10 12:52:34 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8570639365803019, Global best: 0.8570639365803019, Runtime: 4.90248 seconds

2026/06/10 12:52:40 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8570639365803019, Global best: 0.8570639365803019, Runtime: 5.62985 seconds

2026/06/10 12:52:46 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8570639365803019, Global best: 0.8570639365803019, Runtime: 6.31495 seconds

2026/06/10 12:52:50 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8570639365803019, Global best: 0.8570639365803019, Runtime: 4.17330 seconds

2026/06/10 12:52:54 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8570639365803019, Global best: 0.8570639365803019, Runtime: 4.21868 seconds

2026/06/10 12:52:58 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8570639365803019, Global best: 0.8570639365803019, Runtime: 4.00472 seconds

2026/06/10 12:53:03 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8570639365803019, Global best: 0.8570639365803019, Runtime: 4.40462 seconds

2026/06/10 12:53:07 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8598545558532402, Global best: 0.8598545558532402, Runtime: 4.10884 seconds

2026/06/10 12:53:11 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8598545558532402, Global best: 0.8598545558532402, Runtime: 3.99855 seconds

2026/06/10 12:53:16 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8598545558532402, Global best: 0.8598545558532402, Runtime: 4.91937 seconds

2026/06/10 12:53:20 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8599695542477916, Global best: 0.8599695542477916, Runtime: 4.33289 seconds

2026/06/10 12:53:25 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8599695542477916, Global best: 0.8599695542477916, Runtime: 4.73159 seconds

2026/06/10 12:53:30 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8599695542477916, Global best: 0.8599695542477916, Runtime: 4.58825 seconds

2026/06/10 12:53:35 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8599695542477916, Global best: 0.8599695542477916, Runtime: 4.98854 seconds

2026/06/10 12:53:39 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8599695542477916, Global best: 0.8599695542477916, Runtime: 4.03016 seconds

2026/06/10 12:53:42 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8603704686623256, Global best: 0.8603704686623256, Runtime: 3.86109 seconds

2026/06/10 12:53:47 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8603704686623256, Global best: 0.8603704686623256, Runtime: 4.75103 seconds

2026/06/10 12:53:51 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8603704686623256, Global best: 0.8603704686623256, Runtime: 4.08445 seconds

2026/06/10 12:53:55 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8603704686623256, Global best: 0.8603704686623256, Runtime: 4.00070 seconds

2026/06/10 12:54:00 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8603704686623256, Global best: 0.8603704686623256, Runtime: 4.26163 seconds

2026/06/10 12:54:04 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8603704686623256, Global best: 0.8603704686623256, Runtime: 4.18101 seconds

2026/06/10 12:54:08 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8603704686623256, Global best: 0.8603704686623256, Runtime: 4.37895 seconds

2026/06/10 12:54:12 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8603704686623256, Global best: 0.8603704686623256, Runtime: 4.34112 seconds

2026/06/10 06:00:52 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/10 06:01:02 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8548802014411815, Global best: 0.8548802014411815, Runtime: 5.51048 seconds

2026/06/10 06:01:07 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8548802014411815, Global best: 0.8548802014411815, Runtime: 4.91763 seconds

2026/06/10 06:01:14 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8548802014411815, Global best: 0.8548802014411815, Runtime: 6.20259 seconds

2026/06/10 06:01:18 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8548802014411815, Global best: 0.8548802014411815, Runtime: 4.93293 seconds

2026/06/10 06:01:23 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8548802014411815, Global best: 0.8548802014411815, Runtime: 4.33984 seconds

2026/06/10 06:01:28 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8548802014411815, Global best: 0.8548802014411815, Runtime: 4.71767 seconds

2026/06/10 06:01:33 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8689753731433567, Global best: 0.8689753731433567, Runtime: 5.48135 seconds

2026/06/10 06:01:39 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.871636945069601, Global best: 0.871636945069601, Runtime: 6.28795 seconds

2026/06/10 06:01:46 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.871636945069601, Global best: 0.871636945069601, Runtime: 6.36768 seconds

2026/06/10 06:01:51 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8738732488573075, Global best: 0.8738732488573075, Runtime: 5.14441 seconds

2026/06/10 06:01:56 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8738732488573075, Global best: 0.8738732488573075, Runtime: 4.89792 seconds

2026/06/10 06:02:02 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8757192954840815, Global best: 0.8757192954840815, Runtime: 5.91700 seconds

2026/06/10 06:02:08 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8796299465171344, Global best: 0.8796299465171344, Runtime: 5.91165 seconds

2026/06/10 06:02:13 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8796299465171344, Global best: 0.8796299465171344, Runtime: 5.07773 seconds

2026/06/10 06:02:18 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8796299465171344, Global best: 0.8796299465171344, Runtime: 5.07037 seconds

2026/06/10 06:02:23 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8810991387098096, Global best: 0.8810991387098096, Runtime: 5.38876 seconds

2026/06/10 06:02:29 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8810991387098096, Global best: 0.8810991387098096, Runtime: 5.43336 seconds

2026/06/10 06:02:33 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8835087994045326, Global best: 0.8835087994045326, Runtime: 4.84333 seconds

2026/06/10 06:02:39 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8874867133040955, Global best: 0.8874867133040955, Runtime: 5.10533 seconds

2026/06/10 06:02:44 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8883016796411707, Global best: 0.8883016796411707, Runtime: 5.04917 seconds

2026/06/10 06:02:49 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8895295595751471, Global best: 0.8895295595751471, Runtime: 5.40412 seconds

2026/06/10 06:02:54 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8904138710846585, Global best: 0.8904138710846585, Runtime: 5.40181 seconds

2026/06/10 06:03:00 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8904138710846585, Global best: 0.8904138710846585, Runtime: 5.50706 seconds

2026/06/10 06:03:05 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8916174140651376, Global best: 0.8916174140651376, Runtime: 5.58252 seconds

2026/06/10 06:03:12 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8918039602365527, Global best: 0.8918039602365527, Runtime: 6.63105 seconds

2026/06/10 06:03:18 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.89248833203816, Global best: 0.89248833203816, Runtime: 5.44488 seconds

2026/06/10 06:03:24 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.89248833203816, Global best: 0.89248833203816, Runtime: 6.51318 seconds

2026/06/10 06:03:29 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.89248833203816, Global best: 0.89248833203816, Runtime: 4.97790 seconds

2026/06/10 06:03:35 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.89248833203816, Global best: 0.89248833203816, Runtime: 6.02014 seconds

2026/06/10 06:03:40 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.89248833203816, Global best: 0.89248833203816, Runtime: 5.02782 seconds

2026/06/10 07:14:25 AM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/10 07:14:36 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8487284431797456, Global best: 0.8487284431797456, Runtime: 4.13719 seconds

2026/06/10 07:14:40 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8487284431797456, Global best: 0.8487284431797456, Runtime: 4.53977 seconds

2026/06/10 07:14:44 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8487284431797456, Global best: 0.8487284431797456, Runtime: 4.00273 seconds

2026/06/10 07:14:49 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8487284431797456, Global best: 0.8487284431797456, Runtime: 4.27049 seconds

2026/06/10 07:14:53 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8503977236890919, Global best: 0.8503977236890919, Runtime: 4.80444 seconds

2026/06/10 07:14:58 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8503977236890919, Global best: 0.8503977236890919, Runtime: 4.42320 seconds

2026/06/10 07:15:02 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8503977236890919, Global best: 0.8503977236890919, Runtime: 4.36932 seconds

2026/06/10 07:15:08 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8513797932911819, Global best: 0.8513797932911819, Runtime: 5.76256 seconds

2026/06/10 07:15:15 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8515268521147112, Global best: 0.8515268521147112, Runtime: 6.94662 seconds

2026/06/10 07:15:19 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8515268521147112, Global best: 0.8515268521147112, Runtime: 4.34253 seconds

2026/06/10 07:15:24 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8515268521147112, Global best: 0.8515268521147112, Runtime: 4.45218 seconds

2026/06/10 07:15:29 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8515268521147112, Global best: 0.8515268521147112, Runtime: 4.76776 seconds

2026/06/10 07:15:33 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8533513300194782, Global best: 0.8533513300194782, Runtime: 4.52087 seconds

2026/06/10 07:15:38 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8533513300194782, Global best: 0.8533513300194782, Runtime: 4.86592 seconds

2026/06/10 07:15:43 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8533513300194782, Global best: 0.8533513300194782, Runtime: 4.89583 seconds

2026/06/10 07:15:51 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8533513300194782, Global best: 0.8533513300194782, Runtime: 8.02138 seconds

2026/06/10 07:15:58 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8533513300194782, Global best: 0.8533513300194782, Runtime: 7.39517 seconds

2026/06/10 07:16:03 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8533513300194782, Global best: 0.8533513300194782, Runtime: 4.81658 seconds

2026/06/10 07:16:08 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8533513300194782, Global best: 0.8533513300194782, Runtime: 4.56852 seconds

2026/06/10 07:16:12 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8533513300194782, Global best: 0.8533513300194782, Runtime: 4.27386 seconds

2026/06/10 07:16:17 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8533513300194782, Global best: 0.8533513300194782, Runtime: 4.53160 seconds

2026/06/10 07:16:21 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8533513300194782, Global best: 0.8533513300194782, Runtime: 4.74771 seconds

2026/06/10 07:16:26 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8533513300194782, Global best: 0.8533513300194782, Runtime: 4.67234 seconds

2026/06/10 07:16:31 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8536212613540684, Global best: 0.8536212613540684, Runtime: 4.86454 seconds

2026/06/10 07:16:37 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8536212613540684, Global best: 0.8536212613540684, Runtime: 6.04987 seconds

2026/06/10 07:16:42 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8536212613540684, Global best: 0.8536212613540684, Runtime: 5.44450 seconds

2026/06/10 07:16:47 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8536212613540684, Global best: 0.8536212613540684, Runtime: 4.94628 seconds

2026/06/10 07:16:53 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8648061566630124, Global best: 0.8648061566630124, Runtime: 5.38446 seconds

2026/06/10 07:16:58 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8648061566630124, Global best: 0.8648061566630124, Runtime: 5.66870 seconds

2026/06/10 07:17:04 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8648061566630124, Global best: 0.8648061566630124, Runtime: 5.75772 seconds

2026/06/10 01:03:03 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/10 01:03:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8265066591581994, Global best: 0.8265066591581994, Runtime: 4.36427 seconds

2026/06/10 01:03:19 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8554861598644431, Global best: 0.8554861598644431, Runtime: 6.00417 seconds

2026/06/10 01:03:25 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8554861598644431, Global best: 0.8554861598644431, Runtime: 6.32178 seconds

2026/06/10 01:03:30 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8602967286368677, Global best: 0.8602967286368677, Runtime: 5.31241 seconds

2026/06/10 01:03:36 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8660764784696591, Global best: 0.8660764784696591, Runtime: 5.77658 seconds

2026/06/10 01:03:43 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8675775926161295, Global best: 0.8675775926161295, Runtime: 6.33716 seconds

2026/06/10 01:03:49 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8696959859123793, Global best: 0.8696959859123793, Runtime: 6.04939 seconds

2026/06/10 01:03:55 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8696959859123793, Global best: 0.8696959859123793, Runtime: 6.46053 seconds

2026/06/10 01:04:01 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8696959859123793, Global best: 0.8696959859123793, Runtime: 5.91125 seconds

2026/06/10 01:04:07 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8727029074113696, Global best: 0.8727029074113696, Runtime: 6.06499 seconds

2026/06/10 01:04:14 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8727029074113696, Global best: 0.8727029074113696, Runtime: 6.74374 seconds

2026/06/10 01:04:20 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8727029074113696, Global best: 0.8727029074113696, Runtime: 6.56807 seconds

2026/06/10 01:04:28 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8742570087348096, Global best: 0.8742570087348096, Runtime: 7.36342 seconds

2026/06/10 01:04:37 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8749096907176035, Global best: 0.8749096907176035, Runtime: 8.75337 seconds

2026/06/10 01:04:44 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8761959606181301, Global best: 0.8761959606181301, Runtime: 7.83196 seconds

2026/06/10 01:04:51 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8787991356981315, Global best: 0.8787991356981315, Runtime: 7.07815 seconds

2026/06/10 01:04:58 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8794144550972337, Global best: 0.8794144550972337, Runtime: 6.20059 seconds

2026/06/10 01:05:06 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8801177339442828, Global best: 0.8801177339442828, Runtime: 8.38998 seconds

2026/06/10 01:05:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.880437338789787, Global best: 0.880437338789787, Runtime: 6.46549 seconds

2026/06/10 01:05:19 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8813429360456242, Global best: 0.8813429360456242, Runtime: 6.54701 seconds

2026/06/10 01:05:27 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8819429961327088, Global best: 0.8819429961327088, Runtime: 8.39806 seconds

2026/06/10 01:05:36 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8835760614905672, Global best: 0.8835760614905672, Runtime: 8.11239 seconds

2026/06/10 01:05:43 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8835760614905672, Global best: 0.8835760614905672, Runtime: 7.73850 seconds

2026/06/10 01:05:51 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8837411773777718, Global best: 0.8837411773777718, Runtime: 7.74865 seconds

2026/06/10 01:05:59 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8839990639217788, Global best: 0.8839990639217788, Runtime: 8.08395 seconds

2026/06/10 01:06:07 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.884120436198985, Global best: 0.884120436198985, Runtime: 7.40010 seconds

2026/06/10 01:06:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.884533110539733, Global best: 0.884533110539733, Runtime: 6.82712 seconds

2026/06/10 01:06:22 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8845401729925192, Global best: 0.8845401729925192, Runtime: 8.28992 seconds

2026/06/10 01:06:29 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8855161277853412, Global best: 0.8855161277853412, Runtime: 7.52611 seconds

2026/06/10 01:06:36 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8857808336676941, Global best: 0.8857808336676941, Runtime: 6.54295 seconds

2026/06/10 02:27:44 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/10 02:27:53 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8502887450951061, Global best: 0.8502887450951061, Runtime: 4.09982 seconds

2026/06/10 02:27:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8502887450951061, Global best: 0.8502887450951061, Runtime: 4.70399 seconds

2026/06/10 02:28:03 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8502887450951061, Global best: 0.8502887450951061, Runtime: 4.44623 seconds

2026/06/10 02:28:07 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.851318156859812, Global best: 0.851318156859812, Runtime: 4.79977 seconds

2026/06/10 02:28:11 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.851318156859812, Global best: 0.851318156859812, Runtime: 4.02349 seconds

2026/06/10 02:28:16 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.851318156859812, Global best: 0.851318156859812, Runtime: 4.78595 seconds

2026/06/10 02:28:20 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.851318156859812, Global best: 0.851318156859812, Runtime: 4.18624 seconds

2026/06/10 02:28:26 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8524946274480473, Global best: 0.8524946274480473, Runtime: 5.15687 seconds

2026/06/10 02:28:30 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8536281352115875, Global best: 0.8536281352115875, Runtime: 4.88458 seconds

2026/06/10 02:28:36 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8536281352115875, Global best: 0.8536281352115875, Runtime: 5.10480 seconds

2026/06/10 02:28:40 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8536281352115875, Global best: 0.8536281352115875, Runtime: 4.54379 seconds

2026/06/10 02:28:45 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8536281352115875, Global best: 0.8536281352115875, Runtime: 4.57420 seconds

2026/06/10 02:28:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8549311379178539, Global best: 0.8549311379178539, Runtime: 4.62912 seconds

2026/06/10 02:28:55 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8549311379178539, Global best: 0.8549311379178539, Runtime: 5.44861 seconds

2026/06/10 02:28:59 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.56710 seconds

2026/06/10 02:29:04 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.49345 seconds

2026/06/10 02:29:09 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.74862 seconds

2026/06/10 02:29:14 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 5.58585 seconds

2026/06/10 02:29:20 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 5.71858 seconds

2026/06/10 02:29:25 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 5.28448 seconds

2026/06/10 02:29:29 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.25908 seconds

2026/06/10 02:29:34 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.15540 seconds

2026/06/10 02:29:38 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.15292 seconds

2026/06/10 02:29:42 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.61217 seconds

2026/06/10 02:29:46 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.13731 seconds

2026/06/10 02:29:51 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.45442 seconds

2026/06/10 02:29:55 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.00366 seconds

2026/06/10 02:29:59 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.01692 seconds

2026/06/10 02:30:04 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.74817 seconds

2026/06/10 02:30:08 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8562577410650982, Global best: 0.8562577410650982, Runtime: 4.38024 seconds

2026/06/10 07:28:20 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/10 07:28:29 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8681702326967107, Global best: 0.8681702326967107, Runtime: 4.83392 seconds

2026/06/10 07:28:35 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8697457974836427, Global best: 0.8697457974836427, Runtime: 5.47034 seconds

2026/06/10 07:28:40 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8697457974836427, Global best: 0.8697457974836427, Runtime: 5.04145 seconds

2026/06/10 07:28:46 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8718113729955173, Global best: 0.8718113729955173, Runtime: 6.20370 seconds

2026/06/10 07:28:52 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8762338155966597, Global best: 0.8762338155966597, Runtime: 5.73453 seconds

2026/06/10 07:28:58 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8779912734535439, Global best: 0.8779912734535439, Runtime: 5.83082 seconds

2026/06/10 07:29:04 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8779912734535439, Global best: 0.8779912734535439, Runtime: 5.82255 seconds

2026/06/10 07:29:10 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8779912734535439, Global best: 0.8779912734535439, Runtime: 6.57864 seconds

2026/06/10 07:29:17 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8779912734535439, Global best: 0.8779912734535439, Runtime: 6.55890 seconds

2026/06/10 07:29:23 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8780030409827302, Global best: 0.8780030409827302, Runtime: 5.88086 seconds

2026/06/10 07:29:28 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8804418919585064, Global best: 0.8804418919585064, Runtime: 5.77626 seconds

2026/06/10 07:29:34 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8846586724811416, Global best: 0.8846586724811416, Runtime: 5.49889 seconds

2026/06/10 07:29:40 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8846586724811416, Global best: 0.8846586724811416, Runtime: 5.75326 seconds

2026/06/10 07:29:46 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8850444129344566, Global best: 0.8850444129344566, Runtime: 6.30136 seconds

2026/06/10 07:29:52 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8885091472166861, Global best: 0.8885091472166861, Runtime: 6.39891 seconds

2026/06/10 07:29:59 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8892474132704061, Global best: 0.8892474132704061, Runtime: 6.69601 seconds

2026/06/10 07:30:05 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8913349986141362, Global best: 0.8913349986141362, Runtime: 6.28290 seconds

2026/06/10 07:30:11 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8913349986141362, Global best: 0.8913349986141362, Runtime: 5.99208 seconds

2026/06/10 07:30:18 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8913349986141362, Global best: 0.8913349986141362, Runtime: 7.14807 seconds

2026/06/10 07:30:26 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8913349986141362, Global best: 0.8913349986141362, Runtime: 7.20948 seconds

2026/06/10 07:30:33 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8913349986141362, Global best: 0.8913349986141362, Runtime: 7.50905 seconds

2026/06/10 07:30:40 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8922905830987822, Global best: 0.8922905830987822, Runtime: 7.14910 seconds

2026/06/10 07:30:47 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8922905830987822, Global best: 0.8922905830987822, Runtime: 6.46551 seconds

2026/06/10 07:30:53 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8927650682870848, Global best: 0.8927650682870848, Runtime: 6.44495 seconds

2026/06/10 07:31:00 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8943389739287493, Global best: 0.8943389739287493, Runtime: 6.33627 seconds

2026/06/10 07:31:07 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8943389739287493, Global best: 0.8943389739287493, Runtime: 7.03096 seconds

2026/06/10 07:31:15 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8943389739287493, Global best: 0.8943389739287493, Runtime: 8.21451 seconds

2026/06/10 07:31:22 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8947336995026766, Global best: 0.8947336995026766, Runtime: 6.95874 seconds

2026/06/10 07:31:28 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8947336995026766, Global best: 0.8947336995026766, Runtime: 6.64511 seconds

2026/06/10 07:31:36 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8947336995026766, Global best: 0.8947336995026766, Runtime: 7.68010 seconds

2026/06/10 08:23:39 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/10 08:23:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8486480300151261, Global best: 0.8486480300151261, Runtime: 4.38957 seconds

2026/06/10 08:23:53 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8486480300151261, Global best: 0.8486480300151261, Runtime: 4.07758 seconds

2026/06/10 08:23:57 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.06607 seconds

2026/06/10 08:24:01 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 3.89858 seconds

2026/06/10 08:24:05 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.61131 seconds

2026/06/10 08:24:09 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.28092 seconds

2026/06/10 08:24:14 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.28152 seconds

2026/06/10 08:24:18 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.29670 seconds

2026/06/10 08:24:22 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.26319 seconds

2026/06/10 08:24:26 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.07012 seconds

2026/06/10 08:24:31 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.39369 seconds

2026/06/10 08:24:35 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.17474 seconds

2026/06/10 08:24:40 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.94730 seconds

2026/06/10 08:24:44 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.17917 seconds

2026/06/10 08:24:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.96344 seconds

2026/06/10 08:24:54 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.71599 seconds

2026/06/10 08:24:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.52773 seconds

2026/06/10 08:25:04 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 6.00620 seconds

2026/06/10 08:25:09 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.49301 seconds

2026/06/10 08:25:13 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.55948 seconds

2026/06/10 08:25:18 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.87970 seconds

2026/06/10 08:25:23 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 5.16530 seconds

2026/06/10 08:25:28 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.66624 seconds

2026/06/10 08:25:32 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 3.94658 seconds

2026/06/10 08:25:37 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.81721 seconds

2026/06/10 08:25:41 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.60906 seconds

2026/06/10 08:25:46 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.56533 seconds

2026/06/10 08:25:50 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.26507 seconds

2026/06/10 08:25:55 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 4.52083 seconds

2026/06/10 08:26:01 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8489684071305859, Global best: 0.8489684071305859, Runtime: 6.24039 seconds

2026/06/11 12:37:29 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/11 12:37:40 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8645055685292203, Global best: 0.8645055685292203, Runtime: 4.63358 seconds

2026/06/11 12:37:45 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8665294964485881, Global best: 0.8665294964485881, Runtime: 4.95877 seconds

2026/06/11 12:37:49 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8745650807446765, Global best: 0.8745650807446765, Runtime: 4.45093 seconds

2026/06/11 12:37:54 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8764557585636453, Global best: 0.8764557585636453, Runtime: 5.27314 seconds

2026/06/11 12:37:59 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8815786550486061, Global best: 0.8815786550486061, Runtime: 4.82566 seconds

2026/06/11 12:38:04 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8815786550486061, Global best: 0.8815786550486061, Runtime: 5.24380 seconds

2026/06/11 12:38:11 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8815786550486061, Global best: 0.8815786550486061, Runtime: 6.61530 seconds

2026/06/11 12:38:17 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8815786550486061, Global best: 0.8815786550486061, Runtime: 5.97200 seconds

2026/06/11 12:38:23 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8815786550486061, Global best: 0.8815786550486061, Runtime: 5.65057 seconds

2026/06/11 12:38:28 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8815786550486061, Global best: 0.8815786550486061, Runtime: 5.08413 seconds

2026/06/11 12:38:36 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.881774030062716, Global best: 0.881774030062716, Runtime: 7.90509 seconds

2026/06/11 12:38:42 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8822129492855549, Global best: 0.8822129492855549, Runtime: 5.94687 seconds

2026/06/11 12:38:47 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8833359881289764, Global best: 0.8833359881289764, Runtime: 5.62242 seconds

2026/06/11 12:38:53 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8855978484441502, Global best: 0.8855978484441502, Runtime: 5.95133 seconds

2026/06/11 12:38:59 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8855978484441502, Global best: 0.8855978484441502, Runtime: 5.60308 seconds

2026/06/11 12:39:04 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8860817279387895, Global best: 0.8860817279387895, Runtime: 5.51170 seconds

2026/06/11 12:39:10 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8860817279387895, Global best: 0.8860817279387895, Runtime: 5.29317 seconds

2026/06/11 12:39:14 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8863805811989858, Global best: 0.8863805811989858, Runtime: 4.94168 seconds

2026/06/11 12:39:20 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.886884855040839, Global best: 0.886884855040839, Runtime: 5.10321 seconds

2026/06/11 12:39:26 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8873220758886546, Global best: 0.8873220758886546, Runtime: 6.34799 seconds

2026/06/11 12:39:31 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8878814538620723, Global best: 0.8878814538620723, Runtime: 5.21337 seconds

2026/06/11 12:39:37 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8882444838965383, Global best: 0.8882444838965383, Runtime: 5.68350 seconds

2026/06/11 12:39:43 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8890220175857404, Global best: 0.8890220175857404, Runtime: 6.44096 seconds

2026/06/11 12:39:51 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8890220175857404, Global best: 0.8890220175857404, Runtime: 7.53006 seconds

2026/06/11 12:39:56 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8890220175857404, Global best: 0.8890220175857404, Runtime: 5.46547 seconds

2026/06/11 12:40:02 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8891696244852415, Global best: 0.8891696244852415, Runtime: 5.76940 seconds

2026/06/11 12:40:08 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8899018295878727, Global best: 0.8899018295878727, Runtime: 6.05577 seconds

2026/06/11 12:40:14 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8899018295878727, Global best: 0.8899018295878727, Runtime: 5.60203 seconds

2026/06/11 12:40:20 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8907547707643433, Global best: 0.8907547707643433, Runtime: 6.26186 seconds

2026/06/11 12:40:26 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8907547707643433, Global best: 0.8907547707643433, Runtime: 5.76662 seconds

2026/06/11 01:26:02 AM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/11 01:26:12 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8305642203131413, Global best: 0.8305642203131413, Runtime: 4.48973 seconds

2026/06/11 01:26:17 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8305642203131413, Global best: 0.8305642203131413, Runtime: 4.51178 seconds

2026/06/11 01:26:22 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8305642203131413, Global best: 0.8305642203131413, Runtime: 5.46608 seconds

2026/06/11 01:26:28 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8305642203131413, Global best: 0.8305642203131413, Runtime: 6.22327 seconds

2026/06/11 01:26:33 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8305642203131413, Global best: 0.8305642203131413, Runtime: 5.18240 seconds

2026/06/11 01:26:39 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8305642203131413, Global best: 0.8305642203131413, Runtime: 5.03149 seconds

2026/06/11 01:26:43 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8305642203131413, Global best: 0.8305642203131413, Runtime: 4.15236 seconds

2026/06/11 01:26:47 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8307139875900621, Global best: 0.8307139875900621, Runtime: 4.57340 seconds

2026/06/11 01:26:52 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8326689354902286, Global best: 0.8326689354902286, Runtime: 4.40110 seconds

2026/06/11 01:26:56 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8326689354902286, Global best: 0.8326689354902286, Runtime: 4.56127 seconds

2026/06/11 01:27:01 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8326689354902286, Global best: 0.8326689354902286, Runtime: 4.53676 seconds

2026/06/11 01:27:05 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.72038 seconds

2026/06/11 01:27:10 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.37345 seconds

2026/06/11 01:27:14 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.12490 seconds

2026/06/11 01:27:18 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.35958 seconds

2026/06/11 01:27:22 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.12727 seconds

2026/06/11 01:27:27 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.32452 seconds

2026/06/11 01:27:31 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.42925 seconds

2026/06/11 01:27:36 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.35583 seconds

2026/06/11 01:27:40 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.15861 seconds

2026/06/11 01:27:44 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.11560 seconds

2026/06/11 01:27:48 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.20183 seconds

2026/06/11 01:27:53 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 5.07422 seconds

2026/06/11 01:27:57 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 3.97035 seconds

2026/06/11 01:28:02 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.50555 seconds

2026/06/11 01:28:08 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 6.12262 seconds

2026/06/11 01:28:12 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.40267 seconds

2026/06/11 01:28:17 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 4.90129 seconds

2026/06/11 01:28:22 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 5.25387 seconds

2026/06/11 01:28:26 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8333318339745173, Global best: 0.8333318339745173, Runtime: 3.92855 seconds

2026/06/11 04:14:53 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/11 04:15:02 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8602574523995064, Global best: 0.8602574523995064, Runtime: 4.33982 seconds

2026/06/11 04:15:07 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8602574523995064, Global best: 0.8602574523995064, Runtime: 5.09626 seconds

2026/06/11 04:15:13 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8623473062847892, Global best: 0.8623473062847892, Runtime: 5.89950 seconds

2026/06/11 04:15:18 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8627293650352054, Global best: 0.8627293650352054, Runtime: 5.45189 seconds

2026/06/11 04:15:24 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8627293650352054, Global best: 0.8627293650352054, Runtime: 5.56336 seconds

2026/06/11 04:15:29 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8627293650352054, Global best: 0.8627293650352054, Runtime: 5.05983 seconds

2026/06/11 04:15:35 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8627293650352054, Global best: 0.8627293650352054, Runtime: 6.28859 seconds

2026/06/11 04:15:40 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8627293650352054, Global best: 0.8627293650352054, Runtime: 5.17230 seconds

2026/06/11 04:15:46 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8627293650352054, Global best: 0.8627293650352054, Runtime: 6.08381 seconds

2026/06/11 04:15:52 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8627293650352054, Global best: 0.8627293650352054, Runtime: 5.67444 seconds

2026/06/11 04:15:58 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.863478746435169, Global best: 0.863478746435169, Runtime: 5.52832 seconds

2026/06/11 04:16:03 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8674215979341695, Global best: 0.8674215979341695, Runtime: 5.44298 seconds

2026/06/11 04:16:09 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8674215979341695, Global best: 0.8674215979341695, Runtime: 6.03652 seconds

2026/06/11 04:16:15 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8674215979341695, Global best: 0.8674215979341695, Runtime: 5.65772 seconds

2026/06/11 04:16:20 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8674737976552646, Global best: 0.8674737976552646, Runtime: 5.43135 seconds

2026/06/11 04:16:26 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8674737976552646, Global best: 0.8674737976552646, Runtime: 5.62230 seconds

2026/06/11 04:16:31 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8676384769364031, Global best: 0.8676384769364031, Runtime: 5.49424 seconds

2026/06/11 04:16:37 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8688735116458521, Global best: 0.8688735116458521, Runtime: 6.01369 seconds

2026/06/11 04:16:43 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8692416879104266, Global best: 0.8692416879104266, Runtime: 5.79583 seconds

2026/06/11 04:16:49 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8693557176489339, Global best: 0.8693557176489339, Runtime: 5.85605 seconds

2026/06/11 04:16:55 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8700609949256638, Global best: 0.8700609949256638, Runtime: 6.06002 seconds

2026/06/11 04:17:01 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8700609949256638, Global best: 0.8700609949256638, Runtime: 5.96726 seconds

2026/06/11 04:17:09 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8711589942253846, Global best: 0.8711589942253846, Runtime: 7.49429 seconds

2026/06/11 04:17:16 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8712226722043479, Global best: 0.8712226722043479, Runtime: 7.19574 seconds

2026/06/11 04:17:22 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8722666531811887, Global best: 0.8722666531811887, Runtime: 6.68408 seconds

2026/06/11 04:17:29 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8722666531811887, Global best: 0.8722666531811887, Runtime: 6.52768 seconds

2026/06/11 04:17:35 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8722666531811887, Global best: 0.8722666531811887, Runtime: 6.19794 seconds

2026/06/11 04:17:42 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8724166194334634, Global best: 0.8724166194334634, Runtime: 6.81430 seconds

2026/06/11 04:17:48 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8727107370805223, Global best: 0.8727107370805223, Runtime: 6.08200 seconds

2026/06/11 04:17:55 AM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8727401488452281, Global best: 0.8727401488452281, Runtime: 6.64039 seconds

2026/06/11 04:43:45 AM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/11 04:43:54 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8578652728438958, Global best: 0.8578652728438958, Runtime: 4.10789 seconds

2026/06/11 04:43:59 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8578652728438958, Global best: 0.8578652728438958, Runtime: 4.37484 seconds

2026/06/11 04:44:03 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8578652728438958, Global best: 0.8578652728438958, Runtime: 4.31271 seconds

2026/06/11 04:44:07 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8578652728438958, Global best: 0.8578652728438958, Runtime: 3.98868 seconds

2026/06/11 04:44:11 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8578652728438958, Global best: 0.8578652728438958, Runtime: 4.31010 seconds

2026/06/11 04:44:16 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8596593904909546, Global best: 0.8596593904909546, Runtime: 4.61202 seconds

2026/06/11 04:44:20 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8596593904909546, Global best: 0.8596593904909546, Runtime: 3.97487 seconds

2026/06/11 04:44:24 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8600153831588563, Global best: 0.8600153831588563, Runtime: 4.50256 seconds

2026/06/11 04:44:29 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.66416 seconds

2026/06/11 04:44:33 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.36413 seconds

2026/06/11 04:44:38 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.67060 seconds

2026/06/11 04:44:42 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.01280 seconds

2026/06/11 04:44:46 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.02533 seconds

2026/06/11 04:44:50 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.30677 seconds

2026/06/11 04:44:55 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.22625 seconds

2026/06/11 04:44:59 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.05544 seconds

2026/06/11 04:45:03 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.10828 seconds

2026/06/11 04:45:07 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.07271 seconds

2026/06/11 04:45:11 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.24417 seconds

2026/06/11 04:45:15 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.11941 seconds

2026/06/11 04:45:20 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.49204 seconds

2026/06/11 04:45:24 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.31623 seconds

2026/06/11 04:45:28 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.21015 seconds

2026/06/11 04:45:32 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.18287 seconds

2026/06/11 04:45:36 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.06024 seconds

2026/06/11 04:45:41 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.27641 seconds

2026/06/11 04:45:45 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.19924 seconds

2026/06/11 04:45:49 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.12632 seconds

2026/06/11 04:45:53 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 3.95411 seconds

2026/06/11 04:45:57 AM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8611594056090982, Global best: 0.8611594056090982, Runtime: 4.41492 seconds

,seed,method,k_target,n_selected,selected_features,fs_time_s
0,0,BA,10.0,10,"9,18,17,16,20,41,36,34,40,50",143.428390
1,0,Boruta,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",19.668009
2,0,GWO,10.0,10,"14,50,32,46,19,29,39,38,10,27",163.456477
3,0,LightGBM,10.0,10,"40,39,42,3,41,50,17,21,23,47",1244.787356
5,1,BA,10.0,10,"0,2,6,15,29,28,42,34,48,50",148.439191
6,1,Boruta,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",29.408812
7,1,GWO,10.0,10,"49,45,27,16,50,39,8,47,7,43",197.353610
8,1,LightGBM,10.0,10,"40,39,42,3,41,50,17,47,23,21",962.049874
10,2,BA,10.0,10,"1,5,9,8,47,39,34,32,44,43",128.011592
11,2,Boruta,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",21.670698
12,2,GWO,10.0,10,"50,4,39,35,47,28,14,19,8,15",178.060506
13,2,LightGBM,10.0,10,"40,39,42,3,41,50,17,47,21,23",809.733633
15,3,BA,10.0,10,"7,4,9,26,25,42,43,38,41,50",161.249397
16,3,Boruta,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",24.400988
17,3,GWO,10.0,10,"50,47,41,16,39,27,48,4,18,43",213.291762
18,3,LightGBM,10.0,10,"40,39,42,3,41,50,47,17,23,49",1773.177506
20,4,BA,10.0,10,"11,8,21,50,49,44,36,35,23,43",143.776046
21,4,Boruta,NaN,42,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",21.856989
22,4,GWO,10.0,10,"28,43,39,45,18,15,50,40,49,4",215.120092
23,4,LightGBM,10.0,10,"40,39,42,3,41,50,17,23,47,21",667.858511
25,5,BA,10.0,10,"2,4,23,28,24,27,16,39,49,47",159.429747
26,5,Boruta,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",23.669424
27,5,GWO,10.0,10,"45,50,42,28,16,9,41,49,17,46",168.803830
28,5,LightGBM,10.0,10,"40,39,42,3,41,50,17,47,21,43",1027.787836
30,6,BA,10.0,10,"13,8,20,44,40,47,46,32,50,10",144.941211
31,6,Boruta,NaN,42,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",27.008563
32,6,GWO,10.0,10,"50,28,47,40,42,49,22,10,15,19",213.559059
33,6,LightGBM,10.0,10,"40,39,42,3,41,50,17,47,23,21",905.719486
35,7,BA,10.0,10,"6,12,10,11,18,19,36,38,50,45",142.618414
36,7,Boruta,NaN,40,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",17.674438
37,7,GWO,10.0,10,"50,39,41,7,4,15,45,28,40,43",197.097512
38,7,LightGBM,10.0,10,"40,39,42,3,41,50,17,47,21,23",597.244102
40,8,BA,10.0,10,"5,14,15,19,27,22,21,44,43,50",144.771810
41,8,Boruta,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",13.981905
42,8,GWO,10.0,10,"39,15,50,17,49,10,46,14,45,1",177.436956
43,8,LightGBM,10.0,10,"40,39,42,3,41,50,17,23,47,21",143.704583
45,9,BA,10.0,10,"2,15,22,50,40,42,44,38,48,47",133.481996
46,9,Boruta,NaN,42,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",14.517284
47,9,GWO,10.0,10,"10,40,35,7,50,16,46,31,47,41",182.030905
48,9,LightGBM,10.0,10,"40,39,42,3,41,50,17,47,23,21",73.666778

  index    method   fs_time_s             n_selected
                         mean         std       mean       std
0     0        BA  145.014779   10.083277       10.0  0.000000
1     1    Boruta   21.385711    5.047693       41.2  0.632456
2     2       GWO  190.621071   19.284051       10.0  0.000000
3     3  LightGBM  820.572967  499.661168       10.0  0.000000

Feature-selection stability across runs

     method  mean_pairwise_jaccard  std_pairwise_jaccard  n_pairs
0    Boruta               0.969261              0.017814       45
1  LightGBM               0.927946              0.095033       45
3       GWO               0.248921              0.101118       45
4        BA               0.123380              0.068218       45

,seed,method,classifier,k_target,n_selected,selected_features,fs_time_s,accuracy,precision_macro,recall_macro,f1_macro,mcc,train_time_s,inference_time_ms,peak_mem_mb
0,0,GWO,RandomForest,10.0,10,"14,50,32,46,19,29,39,38,10,27",163.456477,0.947582,0.941749,0.918328,0.929387,0.914514,315.962471,34208.926906,258.390052
1,0,GWO,DecisionTree,10.0,10,"14,50,32,46,19,29,39,38,10,27",163.456477,0.954479,0.959412,0.910744,0.933873,0.925739,9.069251,150.068428,164.703757
2,0,GWO,LogisticRegression,10.0,10,"14,50,32,46,19,29,39,38,10,27",163.456477,0.725283,0.556845,0.667697,0.573163,0.601877,119.894534,239.684269,164.707154
3,0,GWO,GaussianNB,10.0,10,"14,50,32,46,19,29,39,38,10,27",163.456477,0.752315,0.583949,0.502797,0.490811,0.587049,1.851110,377.524028,164.699820
4,0,GWO,HistGradientBoosting,10.0,10,"14,50,32,46,19,29,39,38,10,27",163.456477,0.944562,0.957927,0.887006,0.919625,0.909809,768.902742,17784.545728,164.790689
5,0,GWO,MLP,10.0,10,"14,50,32,46,19,29,39,38,10,27",163.456477,0.925919,0.920440,0.842297,0.876416,0.878604,2390.442406,992.316080,307.874106
6,0,BA,RandomForest,10.0,10,"9,18,17,16,20,41,36,34,40,50",143.428390,0.949247,0.936427,0.915233,0.925237,0.917268,347.849069,40035.060567,262.831811
7,0,BA,DecisionTree,10.0,10,"9,18,17,16,20,41,36,34,40,50",143.428390,0.955290,0.949449,0.902940,0.925031,0.927060,10.476400,149.156645,164.704454
8,0,BA,LogisticRegression,10.0,10,"9,18,17,16,20,41,36,34,40,50",143.428390,0.663245,0.500719,0.599714,0.507431,0.519958,38.763075,711.398230,164.704345
9,0,BA,GaussianNB,10.0,10,"9,18,17,16,20,41,36,34,40,50",143.428390,0.693550,0.480214,0.463100,0.436865,0.510232,1.779391,320.744211,164.697594
10,0,BA,HistGradientBoosting,10.0,10,"9,18,17,16,20,41,36,34,40,50",143.428390,0.942290,0.944372,0.881937,0.910810,0.905836,1094.999753,31824.715248,164.766702
11,0,BA,MLP,10.0,10,"9,18,17,16,20,41,36,34,40,50",143.428390,0.923234,0.899770,0.818900,0.854120,0.873998,2156.424775,2028.674951,307.863264
18,0,LightGBM,RandomForest,10.0,10,"40,39,42,3,41,50,17,21,23,47",1244.787356,0.953894,0.952372,0.920322,0.935624,0.924793,384.665104,47128.248113,262.902403
19,0,LightGBM,DecisionTree,10.0,10,"40,39,42,3,41,50,17,21,23,47",1244.787356,0.953296,0.951634,0.904448,0.926882,0.923763,21.865741,159.271400,164.704310
20,0,LightGBM,LogisticRegression,10.0,10,"40,39,42,3,41,50,17,21,23,47",1244.787356,0.661836,0.415409,0.554920,0.424322,0.497188,37.680901,161.896008,164.706159
21,0,LightGBM,GaussianNB,10.0,10,"40,39,42,3,41,50,17,21,23,47",1244.787356,0.715760,0.389831,0.395716,0.343225,0.529877,1.829544,379.521360,164.698763
22,0,LightGBM,HistGradientBoosting,10.0,10,"40,39,42,3,41,50,17,21,23,47",1244.787356,0.942465,0.947061,0.883564,0.913068,0.906177,1223.150738,16638.599044,164.769795
23,0,LightGBM,MLP,10.0,10,"40,39,42,3,41,50,17,21,23,47",1244.787356,0.904065,0.871557,0.797666,0.830366,0.841863,4522.087152,1253.996906,307.864013
24,0,Boruta,RandomForest,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",19.668009,0.959955,0.968980,0.931889,0.949552,0.934755,440.729089,49720.371187,629.628984
25,0,Boruta,DecisionTree,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",19.668009,0.962385,0.971777,0.924983,0.947261,0.938760,40.038033,467.149869,629.589664
26,0,Boruta,LogisticRegression,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",19.668009,0.846037,0.692665,0.805131,0.723506,0.760542,758.776770,480.582594,629.588413
27,0,Boruta,GaussianNB,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",19.668009,0.811061,0.629241,0.636838,0.616619,0.690295,7.308907,947.706861,629.582962
28,0,Boruta,HistGradientBoosting,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",19.668009,0.953245,0.954290,0.907785,0.927188,0.924097,2191.864343,33165.555656,629.653568
29,0,Boruta,MLP,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",19.668009,0.943570,0.942727,0.881868,0.910189,0.907784,2940.305316,2320.853515,629.592036
30,1,GWO,RandomForest,10.0,10,"49,45,27,16,50,39,8,47,7,43",197.353610,0.947710,0.942224,0.922986,0.932044,0.914737,383.034134,38451.243339,260.614424
31,1,GWO,DecisionTree,10.0,10,"49,45,27,16,50,39,8,47,7,43",197.353610,0.955724,0.961379,0.917726,0.938473,0.927808,10.093949,145.468894,164.703349
32,1,GWO,LogisticRegression,10.0,10,"49,45,27,16,50,39,8,47,7,43",197.353610,0.723353,0.560369,0.655364,0.571055,0.596625,62.019117,780.023821,164.705025
33,1,GWO,GaussianNB,10.0,10,"49,45,27,16,50,39,8,47,7,43",197.353610,0.790654,0.633309,0.582101,0.574665,0.652132,1.869256,575.535396,164.697849
34,1,GWO,HistGradientBoosting,10.0,10,"49,45,27,16,50,39,8,47,7,43",197.353610,0.944374,0.960784,0.893343,0.924579,0.909457,1643.704897,30936.649650,164.771799
35,1,GWO,MLP,10.0,10,"49,45,27,16,50,39,8,47,7,43",197.353610,0.925671,0.932946,0.851212,0.888306,0.878124,2129.247412,1040.563713,307.862399
36,1,BA,RandomForest,10.0,10,"0,2,6,15,29,28,42,34,48,50",148.439191,0.939094,0.930680,0.906055,0.917495,0.900550,352.593203,42111.812734,256.813782
37,1,BA,DecisionTree,10.0,10,"0,2,6,15,29,28,42,34,48,50",148.439191,0.944241,0.948817,0.895327,0.920530,0.908933,11.843392,197.957734,164.702402
38,1,BA,LogisticRegression,10.0,10,"0,2,6,15,29,28,42,34,48,50",148.439191,0.685880,0.534774,0.612893,0.541353,0.543768,86.160864,219.846832,164.704203
39,1,BA,GaussianNB,10.0,10,"0,2,6,15,29,28,42,34,48,50",148.439191,0.687705,0.528043,0.440210,0.416804,0.501365,2.136744,356.401422,164.699776
40,1,BA,HistGradientBoosting,10.0,10,"0,2,6,15,29,28,42,34,48,50",148.439191,0.932818,0.944469,0.862270,0.899718,0.890444,1105.171221,25553.789610,164.756101
41,1,BA,MLP,10.0,10,"0,2,6,15,29,28,42,34,48,50",148.439191,0.914073,0.910688,0.811210,0.854893,0.858869,2649.870571,949.695923,307.864254
48,1,LightGBM,RandomForest,10.0,10,"40,39,42,3,41,50,17,47,23,21",962.049874,0.954222,0.953755,0.920302,0.936276,0.925327,442.695209,50521.307326,262.743976
49,1,LightGBM,DecisionTree,10.0,10,"40,39,42,3,41,50,17,47,23,21",962.049874,0.953462,0.952211,0.905406,0.927683,0.924041,18.860892,153.088607,164.703323
50,1,LightGBM,LogisticRegression,10.0,10,"40,39,42,3,41,50,17,47,23,21",962.049874,0.661752,0.415243,0.555261,0.424344,0.497104,39.077393,313.438615,164.704209
51,1,LightGBM,GaussianNB,10.0,10,"40,39,42,3,41,50,17,47,23,21",962.049874,0.716066,0.389334,0.396155,0.343313,0.530472,3.256213,686.747348,164.699576
52,1,LightGBM,HistGradientBoosting,10.0,10,"40,39,42,3,41,50,17,47,23,21",962.049874,0.943821,0.950258,0.886885,0.916381,0.908421,1552.504899,32189.751980,164.770827
53,1,LightGBM,MLP,10.0,10,"40,39,42,3,41,50,17,47,23,21",962.049874,0.900262,0.868610,0.790038,0.823251,0.835683,4279.395221,1006.208646,307.899764
54,1,Boruta,RandomForest,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",29.408812,0.960130,0.969487,0.931799,0.949743,0.935043,449.087340,60318.959207,629.627509
55,1,Boruta,DecisionTree,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",29.408812,0.962637,0.972598,0.924688,0.947481,0.939179,38.310476,437.514098,629.590246
56,1,Boruta,LogisticRegression,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",29.408812,0.846282,0.691953,0.802576,0.722677,0.760461,814.676126,469.989406,629.586556
57,1,Boruta,GaussianNB,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",29.408812,0.811932,0.635405,0.639633,0.623627,0.691982,7.174193,1107.696803,629.582881
58,1,Boruta,HistGradientBoosting,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",29.408812,0.949867,0.950332,0.896174,0.921229,0.918404,1701.318342,38446.888613,629.653956
59,1,Boruta,MLP,NaN,41,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",29.408812,0.943355,0.939686,0.885282,0.910809,0.907482,2260.471959,1986.441823,629.589964
60,2,GWO,RandomForest,10.0,10,"50,4,39,35,47,28,14,19,8,15",178.060506,0.948536,0.934835,0.921874,0.927776,0.916128,373.105902,45509.671355,262.810230
61,2,GWO,DecisionTree,10.0,10,"50,4,39,35,47,28,14,19,8,15",178.060506,0.955726,0.951582,0.914689,0.932215,0.927812,11.368737,250.073466,164.702296
62,2,GWO,LogisticRegression,10.0,10,"50,4,39,35,47,28,14,19,8,15",178.060506,0.681955,0.503895,0.636885,0.531540,0.539680,55.353401,120.353988,164.703562
63,2,GWO,GaussianNB,10.0,10,"50,4,39,35,47,28,14,19,8,15",178.060506,0.772148,0.555969,0.526935,0.521273,0.620102,1.874645,352.029194,164.697814
64,2,GWO,HistGradientBoosting,10.0,10,"50,4,39,35,47,28,14,19,8,15",178.060506,0.946616,0.956844,0.892945,0.922385,0.913089,1496.024308,31547.130155,164.764597
65,2,GWO,MLP,10.0,10,"50,4,39,35,47,28,14,19,8,15",178.060506,0.928278,0.925321,0.841930,0.877479,0.882489,2690.440318,1322.451456,307.866507
66,2,BA,RandomForest,10.0,10,"1,5,9,8,47,39,34,32,44,43",128.011592,0.930234,0.878205,0.887495,0.881352,0.886754,391.146426,46643.007381,258.287041
67,2,BA,DecisionTree,10.0,10,"1,5,9,8,47,39,34,32,44,43",128.011592,0.938872,0.904483,0.868339,0.885518,0.899986,9.944354,166.331346,164.706687
68,2,BA,LogisticRegression,10.0,10,"1,5,9,8,47,39,34,32,44,43",128.011592,0.663194,0.425357,0.595253,0.457710,0.504559,124.384344,248.232099,164.705921
69,2,BA,GaussianNB,10.0,10,"1,5,9,8,47,39,34,32,44,43",128.011592,0.594116,0.330868,0.428633,0.329814,0.412785,2.486295,356.805582,164.698596
70,2,BA,HistGradientBoosting,10.0,10,"1,5,9,8,47,39,34,32,44,43",128.011592,0.922461,0.906971,0.825877,0.862543,0.872717,729.695220,12534.817053,164.759191
71,2,BA,MLP,10.0,10,"1,5,9,8,47,39,34,32,44,43",128.011592,0.862153,0.837437,0.718517,0.767480,0.770057,1560.179524,875.344082,307.865407
78,2,LightGBM,RandomForest,10.0,10,"40,39,42,3,41,50,17,47,21,23",809.733633,0.954167,0.952932,0.920113,0.935806,0.925236,395.956399,45823.613056,258.218693
79,2,LightGBM,DecisionTree,10.0,10,"40,39,42,3,41,50,17,47,21,23",809.733633,0.953586,0.953223,0.905776,0.928365,0.924234,18.046576,147.470658,164.705315
80,2,LightGBM,LogisticRegression,10.0,10,"40,39,42,3,41,50,17,47,21,23",809.733633,0.661736,0.415557,0.555262,0.424289,0.497015,36.993858,270.399076,164.702627
81,2,LightGBM,GaussianNB,10.0,10,"40,39,42,3,41,50,17,47,21,23",809.733633,0.715734,0.387449,0.395767,0.342930,0.529865,2.128254,505.057210,164.697857
82,2,LightGBM,HistGradientBoosting,10.0,10,"40,39,42,3,41,50,17,47,21,23",809.733633,0.943041,0.945973,0.884191,0.912962,0.907136,995.423013,23258.300179,164.761335
83,2,LightGBM,MLP,10.0,10,"40,39,42,3,41,50,17,47,21,23",809.733633,0.897693,0.867820,0.782349,0.817680,0.831357,3402.517889,1877.475711,307.868394
84,2,Boruta,RandomForest,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",21.670698,0.960174,0.968759,0.931876,0.949444,0.935116,424.034263,39882.793264,629.635103
85,2,Boruta,DecisionTree,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",21.670698,0.962755,0.972610,0.925747,0.948063,0.939374,37.598780,450.916192,629.587544
86,2,Boruta,LogisticRegression,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",21.670698,0.844584,0.691698,0.804290,0.722857,0.758632,705.061883,459.898985,629.586038
87,2,Boruta,GaussianNB,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",21.670698,0.809878,0.629523,0.638878,0.618532,0.688681,9.156312,878.290378,629.582488
88,2,Boruta,HistGradientBoosting,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",21.670698,0.955310,0.970885,0.913268,0.940373,0.927384,1699.270055,36419.655575,629.633958
89,2,Boruta,MLP,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",21.670698,0.942571,0.939222,0.881880,0.908476,0.906260,2249.857078,1703.169916,629.594813
90,3,GWO,RandomForest,10.0,10,"50,47,41,16,39,27,48,4,18,43",213.291762,0.953130,0.948452,0.925028,0.936177,0.923582,356.240472,43661.453370,258.332609
91,3,GWO,DecisionTree,10.0,10,"50,47,41,16,39,27,48,4,18,43",213.291762,0.957873,0.959415,0.917063,0.937269,0.931351,10.625971,160.948617,164.701129
92,3,GWO,LogisticRegression,10.0,10,"50,47,41,16,39,27,48,4,18,43",213.291762,0.656905,0.500332,0.628393,0.516233,0.511076,43.222802,228.852714,164.703885
93,3,GWO,GaussianNB,10.0,10,"50,47,41,16,39,27,48,4,18,43",213.291762,0.763441,0.597917,0.535787,0.526404,0.609651,2.696551,530.357048,164.697542
94,3,GWO,HistGradientBoosting,10.0,10,"50,47,41,16,39,27,48,4,18,43",213.291762,0.949518,0.962009,0.900086,0.928941,0.917845,2205.280066,27904.724957,164.769709
95,3,GWO,MLP,10.0,10,"50,47,41,16,39,27,48,4,18,43",213.291762,0.931239,0.923505,0.849154,0.881722,0.887436,4380.821108,1249.017265,307.865478
96,3,BA,RandomForest,10.0,10,"7,4,9,26,25,42,43,38,41,50",161.249397,0.945404,0.917043,0.913393,0.913031,0.910996,396.968286,44545.628352,261.306740
97,3,BA,DecisionTree,10.0,10,"7,4,9,26,25,42,43,38,41,50",161.249397,0.946556,0.922364,0.902350,0.910263,0.912809,11.064228,193.283229,164.701830
98,3,BA,LogisticRegression,10.0,10,"7,4,9,26,25,42,43,38,41,50",161.249397,0.639719,0.443074,0.587441,0.466781,0.477260,59.727757,454.928871,164.703316
99,3,BA,GaussianNB,10.0,10,"7,4,9,26,25,42,43,38,41,50",161.249397,0.721745,0.437860,0.502214,0.437532,0.557259,2.246180,354.207559,164.698017
100,3,BA,HistGradientBoosting,10.0,10,"7,4,9,26,25,42,43,38,41,50",161.249397,0.939131,0.934481,0.878015,0.903341,0.900801,1416.134044,34012.194653,164.768118
101,3,BA,MLP,10.0,10,"7,4,9,26,25,42,43,38,41,50",161.249397,0.906511,0.876204,0.806006,0.835701,0.846149,3184.395626,1103.853479,307.860107
108,3,LightGBM,RandomForest,10.0,10,"40,39,42,3,41,50,47,17,23,49",1773.177506,0.956161,0.961287,0.924235,0.941954,0.928498,408.357519,53843.897685,258.329640
109,3,LightGBM,DecisionTree,10.0,10,"40,39,42,3,41,50,47,17,23,49",1773.177506,0.955934,0.959497,0.911892,0.934548,0.928120,16.913172,177.407810,164.703565
110,3,LightGBM,LogisticRegression,10.0,10,"40,39,42,3,41,50,47,17,23,49",1773.177506,0.612239,0.398984,0.536683,0.423506,0.444297,47.743379,324.984773,164.706564
111,3,LightGBM,GaussianNB,10.0,10,"40,39,42,3,41,50,47,17,23,49",1773.177506,0.517428,0.401068,0.384867,0.312825,0.343102,1.742057,375.497532,164.697463
112,3,LightGBM,HistGradientBoosting,10.0,10,"40,39,42,3,41,50,47,17,23,49",1773.177506,0.947451,0.960755,0.897943,0.927198,0.914474,2357.788991,40622.208810,164.771785
113,3,LightGBM,MLP,10.0,10,"40,39,42,3,41,50,47,17,23,49",1773.177506,0.896977,0.859661,0.797965,0.825650,0.830023,3163.761447,1811.796761,307.864408
114,3,Boruta,RandomForest,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",24.400988,0.960125,0.969071,0.931983,0.949659,0.935032,421.739533,49597.452528,629.625678
115,3,Boruta,DecisionTree,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",24.400988,0.962630,0.972540,0.925409,0.947836,0.939165,37.074724,344.376209,629.591156
116,3,Boruta,LogisticRegression,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",24.400988,0.844572,0.691418,0.804401,0.722591,0.758595,886.684022,478.602687,629.586032
117,3,Boruta,GaussianNB,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",24.400988,0.809885,0.628876,0.638362,0.618094,0.688678,6.676958,887.189753,629.583055
118,3,Boruta,HistGradientBoosting,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",24.400988,0.954740,0.972299,0.911939,0.940219,0.926451,2176.241814,23443.048104,629.652140
119,3,Boruta,MLP,NaN,41,"3,4,6,7,8,9,10,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",24.400988,0.942257,0.937911,0.882869,0.908514,0.905615,2495.049974,1652.725121,629.588985
120,4,GWO,RandomForest,10.0,10,"28,43,39,45,18,15,50,40,49,4",215.120092,0.954393,0.959360,0.927151,0.942481,0.925632,390.996456,48472.113142,258.344860
121,4,GWO,DecisionTree,10.0,10,"28,43,39,45,18,15,50,40,49,4",215.120092,0.958643,0.969347,0.921200,0.944085,0.932603,14.990418,174.082483,164.701164
122,4,GWO,LogisticRegression,10.0,10,"28,43,39,45,18,15,50,40,49,4",215.120092,0.709817,0.540751,0.638997,0.550129,0.578761,60.909825,312.155661,164.703325
123,4,GWO,GaussianNB,10.0,10,"28,43,39,45,18,15,50,40,49,4",215.120092,0.762479,0.538808,0.552699,0.515314,0.612972,1.863796,725.396324,164.696397
124,4,GWO,HistGradientBoosting,10.0,10,"28,43,39,45,18,15,50,40,49,4",215.120092,0.943265,0.959027,0.890575,0.922320,0.907568,1366.162690,30409.960407,164.768156
125,4,GWO,MLP,10.0,10,"28,43,39,45,18,15,50,40,49,4",215.120092,0.927024,0.932700,0.854456,0.890084,0.880400,3179.945266,1353.616727,307.865137
126,4,BA,RandomForest,10.0,10,"11,8,21,50,49,44,36,35,23,43",143.776046,0.932781,0.892136,0.895442,0.890788,0.890263,321.823319,56818.948275,258.167236
127,4,BA,DecisionTree,10.0,10,"11,8,21,50,49,44,36,35,23,43",143.776046,0.931365,0.891443,0.886798,0.886281,0.887810,11.697753,131.418797,164.701687
128,4,BA,LogisticRegression,10.0,10,"11,8,21,50,49,44,36,35,23,43",143.776046,0.717422,0.530834,0.596006,0.527303,0.572031,76.198494,301.099846,164.707207
129,4,BA,GaussianNB,10.0,10,"11,8,21,50,49,44,36,35,23,43",143.776046,0.748336,0.515152,0.481626,0.448745,0.586195,2.021886,397.941814,164.697195
130,4,BA,HistGradientBoosting,10.0,10,"11,8,21,50,49,44,36,35,23,43",143.776046,0.933780,0.948781,0.869757,0.905938,0.892001,1378.737502,31494.781353,164.766073
131,4,BA,MLP,10.0,10,"11,8,21,50,49,44,36,35,23,43",143.776046,0.919385,0.915109,0.836818,0.872535,0.867776,3619.424133,1887.079991,307.867618
138,4,LightGBM,RandomForest,10.0,10,"40,39,42,3,41,50,17,23,47,21",667.858511,0.954047,0.952957,0.920332,0.935912,0.925042,384.028649,41230.173422,257.571485
139,4,LightGBM,DecisionTree,10.0,10,"40,39,42,3,41,50,17,23,47,21",667.858511,0.953511,0.952513,0.904816,0.927488,0.924115,18.607003,148.658261,164.704809
140,4,LightGBM,LogisticRegression,10.0,10,"40,39,42,3,41,50,17,23,47,21",667.858511,0.661641,0.415311,0.554987,0.424263,0.496917,36.804469,313.399666,164.703044
141,4,LightGBM,GaussianNB,10.0,10,"40,39,42,3,41,50,17,23,47,21",667.858511,0.715789,0.388535,0.395714,0.343192,0.529886,2.453682,345.472161,164.698590
142,4,LightGBM,HistGradientBoosting,10.0,10,"40,39,42,3,41,50,17,23,47,21",667.858511,0.944047,0.951717,0.886887,0.917026,0.908803,796.435816,25538.139542,164.753229
143,4,LightGBM,MLP,10.0,10,"40,39,42,3,41,50,17,23,47,21",667.858511,0.897850,0.862095,0.786928,0.819490,0.831491,3039.828619,1558.494200,307.864476
144,4,Boruta,RandomForest,NaN,42,"3,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50",21.856989,0.959979,0.968670,0.931899,0.949414,0.934798,377.050524,29496.177834,644.629393

Rows: 300

,Algorithm,Classifier,Accuracy,Precision,Recall,F1_macro,MCC,N_Selected,fs_time_s,train_time_s,inference_time_ms,peak_mem_mb
0,Boruta,RandomForest,0.960053,0.968853,0.931864,0.949486,0.934918,41.2,21.385711,388.908428,38485.466011,632.631626
1,Boruta,DecisionTree,0.962729,0.972628,0.925590,0.947976,0.939333,41.2,21.385711,38.187735,409.809770,632.587744
2,GWO,DecisionTree,0.956968,0.962202,0.915959,0.937937,0.929864,10.0,190.621071,10.910510,162.175361,164.703777
3,LightGBM,RandomForest,0.954305,0.953813,0.920890,0.936615,0.925466,10.0,820.572967,381.883285,40840.455992,259.459781
4,GWO,RandomForest,0.951641,0.949651,0.923434,0.935856,0.921162,10.0,190.621071,329.132580,37471.583837,259.497023
7,Boruta,HistGradientBoosting,0.952378,0.959430,0.905144,0.929961,0.922565,41.2,21.385711,1332.454135,26099.164462,632.648615
8,LightGBM,DecisionTree,0.953985,0.953653,0.906406,0.928889,0.924902,10.0,820.572967,18.496138,170.950099,164.704101
9,GWO,HistGradientBoosting,0.946092,0.958861,0.892748,0.923381,0.912261,10.0,190.621071,1217.765538,24989.439239,164.771596
11,LightGBM,HistGradientBoosting,0.943303,0.949197,0.886039,0.915406,0.907571,10.0,820.572967,1027.472188,23777.845627,164.765708
12,Boruta,MLP,0.943197,0.940609,0.883250,0.909913,0.907212,41.2,21.385711,2190.907379,1709.690491,632.589891
13,BA,RandomForest,0.940106,0.913046,0.904180,0.906875,0.902369,10.0,145.014779,329.518069,38788.557909,259.211297
14,BA,DecisionTree,0.943649,0.924865,0.892255,0.906709,0.907957,10.0,145.014779,10.413739,157.965548,164.702662
15,BA,HistGradientBoosting,0.934399,0.938275,0.864279,0.898003,0.892882,10.0,145.014779,947.021424,23021.786603,164.764411
16,GWO,MLP,0.928030,0.925266,0.848617,0.882702,0.882073,10.0,190.621071,2458.538604,1112.969616,307.874294
18,BA,MLP,0.911156,0.898353,0.807339,0.846516,0.853757,10.0,145.014779,2267.236831,1308.466900,307.865958
19,LightGBM,MLP,0.898044,0.864916,0.786466,0.819744,0.831923,10.0,820.572967,2929.256508,1291.931400,307.868590
20,Boruta,LogisticRegression,0.845930,0.692724,0.804896,0.723875,0.760342,41.2,21.385711,630.913916,457.158845,632.587117
21,Boruta,GaussianNB,0.810268,0.629757,0.637850,0.618239,0.689263,41.2,21.385711,7.962432,1119.407212,632.582156
22,GWO,LogisticRegression,0.696822,0.527840,0.644521,0.542956,0.562668,10.0,190.621071,50.744261,303.709876,164.705248
23,GWO,GaussianNB,0.753506,0.570577,0.550791,0.529187,0.602550,10.0,190.621071,2.057373,462.896382,164.699038
24,BA,LogisticRegression,0.678888,0.496275,0.605327,0.505700,0.534252,10.0,145.014779,70.537770,322.359367,164.704880
27,BA,GaussianNB,0.714032,0.496664,0.487969,0.454936,0.544911,10.0,145.014779,2.122455,398.912561,164.698232
28,LightGBM,LogisticRegression,0.655989,0.415409,0.554673,0.424663,0.491892,10.0,820.572967,36.817713,245.679425,164.704584
29,LightGBM,GaussianNB,0.697880,0.395488,0.396450,0.343243,0.514498,10.0,820.572967,2.073779,427.750430,164.698334

Deployment-oriented summary (lower downstream cost is better)

,Algorithm,Classifier,N_Selected,train_time_s,inference_time_ms,peak_mem_mb
0,BA,GaussianNB,10.0,2.122455,398.912561,164.698232
1,LightGBM,GaussianNB,10.0,2.073779,427.750430,164.698334
3,GWO,GaussianNB,10.0,2.057373,462.896382,164.699038
5,BA,DecisionTree,10.0,10.413739,157.965548,164.702662
6,GWO,DecisionTree,10.0,10.910510,162.175361,164.703777
7,LightGBM,DecisionTree,10.0,18.496138,170.950099,164.704101
9,LightGBM,LogisticRegression,10.0,36.817713,245.679425,164.704584
10,BA,LogisticRegression,10.0,70.537770,322.359367,164.704880
11,GWO,LogisticRegression,10.0,50.744261,303.709876,164.705248
12,BA,HistGradientBoosting,10.0,947.021424,23021.786603,164.764411
14,LightGBM,HistGradientBoosting,10.0,1027.472188,23777.845627,164.765708
15,GWO,HistGradientBoosting,10.0,1217.765538,24989.439239,164.771596
17,BA,RandomForest,10.0,329.518069,38788.557909,259.211297
18,LightGBM,RandomForest,10.0,381.883285,40840.455992,259.459781
19,GWO,RandomForest,10.0,329.132580,37471.583837,259.497023
20,BA,MLP,10.0,2267.236831,1308.466900,307.865958
22,LightGBM,MLP,10.0,2929.256508,1291.931400,307.868590
23,GWO,MLP,10.0,2458.538604,1112.969616,307.874294
24,Boruta,GaussianNB,41.2,7.962432,1119.407212,632.582156
25,Boruta,LogisticRegression,41.2,630.913916,457.158845,632.587117
26,Boruta,DecisionTree,41.2,38.187735,409.809770,632.587744
27,Boruta,MLP,41.2,2190.907379,1709.690491,632.589891
28,Boruta,RandomForest,41.2,388.908428,38485.466011,632.631626
29,Boruta,HistGradientBoosting,41.2,1332.454135,26099.164462,632.648615

,Method,Classifier,accuracy,precision_macro,recall_macro,f1_macro,mcc,n_selected,fs_time_s,train_time_s,inference_time_ms,peak_mem_mb
0,BA,DecisionTree,0.9436 +- 0.0101,0.9249 +- 0.0290,0.8923 +- 0.0150,0.9067 +- 0.0220,0.9080 +- 0.0165,10.0000 +- 0.0000,145.015 +- 10.083,10.414 +- 2.219,157.966 +- 22.250,164.703 +- 0.002
1,Boruta,DecisionTree,0.9627 +- 0.0002,0.9726 +- 0.0006,0.9256 +- 0.0006,0.9480 +- 0.0005,0.9393 +- 0.0003,41.2000 +- 0.6325,21.386 +- 5.048,38.188 +- 1.669,409.810 +- 39.771,632.588 +- 9.485
2,GWO,DecisionTree,0.9570 +- 0.0022,0.9622 +- 0.0048,0.9160 +- 0.0030,0.9379 +- 0.0034,0.9299 +- 0.0036,10.0000 +- 0.0000,190.621 +- 19.284,10.911 +- 1.675,162.175 +- 32.950,164.704 +- 0.002
3,LightGBM,DecisionTree,0.9540 +- 0.0009,0.9537 +- 0.0025,0.9064 +- 0.0025,0.9289 +- 0.0025,0.9249 +- 0.0015,10.0000 +- 0.0000,820.573 +- 499.661,18.496 +- 1.376,170.950 +- 29.374,164.704 +- 0.001
5,BA,GaussianNB,0.7140 +- 0.0577,0.4967 +- 0.0833,0.4880 +- 0.0457,0.4549 +- 0.0693,0.5449 +- 0.0759,10.0000 +- 0.0000,145.015 +- 10.083,2.122 +- 0.398,398.913 +- 75.815,164.698 +- 0.001
6,Boruta,GaussianNB,0.8103 +- 0.0009,0.6298 +- 0.0025,0.6378 +- 0.0022,0.6182 +- 0.0025,0.6893 +- 0.0014,41.2000 +- 0.6325,21.386 +- 5.048,7.962 +- 1.272,1119.407 +- 327.987,632.582 +- 9.484
7,GWO,GaussianNB,0.7535 +- 0.0342,0.5706 +- 0.0447,0.5508 +- 0.0247,0.5292 +- 0.0299,0.6026 +- 0.0411,10.0000 +- 0.0000,190.621 +- 19.284,2.057 +- 0.359,462.896 +- 118.065,164.699 +- 0.003
8,LightGBM,GaussianNB,0.6979 +- 0.0637,0.3955 +- 0.0162,0.3964 +- 0.0068,0.3432 +- 0.0145,0.5145 +- 0.0610,10.0000 +- 0.0000,820.573 +- 499.661,2.074 +- 0.471,427.750 +- 104.662,164.698 +- 0.001
10,BA,HistGradientBoosting,0.9344 +- 0.0063,0.9383 +- 0.0162,0.8643 +- 0.0171,0.8980 +- 0.0160,0.8929 +- 0.0105,10.0000 +- 0.0000,145.015 +- 10.083,947.021 +- 497.669,23021.787 +- 14377.090,164.764 +- 0.005
11,Boruta,HistGradientBoosting,0.9524 +- 0.0038,0.9594 +- 0.0145,0.9051 +- 0.0109,0.9300 +- 0.0130,0.9226 +- 0.0064,41.2000 +- 0.6325,21.386 +- 5.048,1332.454 +- 767.266,26099.164 +- 11370.535,632.649 +- 9.483
12,GWO,HistGradientBoosting,0.9461 +- 0.0021,0.9589 +- 0.0025,0.8927 +- 0.0041,0.9234 +- 0.0030,0.9123 +- 0.0034,10.0000 +- 0.0000,190.621 +- 19.284,1217.766 +- 644.829,24989.439 +- 10166.605,164.772 +- 0.007
13,LightGBM,HistGradientBoosting,0.9433 +- 0.0023,0.9492 +- 0.0058,0.8860 +- 0.0064,0.9154 +- 0.0062,0.9076 +- 0.0038,10.0000 +- 0.0000,820.573 +- 499.661,1027.472 +- 728.005,23777.846 +- 15401.789,164.766 +- 0.006
15,BA,LogisticRegression,0.6789 +- 0.0447,0.4963 +- 0.0488,0.6053 +- 0.0253,0.5057 +- 0.0368,0.5343 +- 0.0509,10.0000 +- 0.0000,145.015 +- 10.083,70.538 +- 34.842,322.359 +- 172.146,164.705 +- 0.002
16,Boruta,LogisticRegression,0.8459 +- 0.0019,0.6927 +- 0.0022,0.8049 +- 0.0016,0.7239 +- 0.0025,0.7603 +- 0.0025,41.2000 +- 0.6325,21.386 +- 5.048,630.914 +- 200.040,457.159 +- 33.851,632.587 +- 9.485
17,GWO,LogisticRegression,0.6968 +- 0.0254,0.5278 +- 0.0248,0.6445 +- 0.0179,0.5430 +- 0.0220,0.5627 +- 0.0328,10.0000 +- 0.0000,190.621 +- 19.284,50.744 +- 27.663,303.710 +- 191.706,164.705 +- 0.002
18,LightGBM,LogisticRegression,0.6560 +- 0.0155,0.4154 +- 0.0082,0.5547 +- 0.0081,0.4247 +- 0.0022,0.4919 +- 0.0167,10.0000 +- 0.0000,820.573 +- 499.661,36.818 +- 8.968,245.679 +- 74.021,164.705 +- 0.001
20,BA,MLP,0.9112 +- 0.0177,0.8984 +- 0.0270,0.8073 +- 0.0323,0.8465 +- 0.0300,0.8538 +- 0.0303,10.0000 +- 0.0000,145.015 +- 10.083,2267.237 +- 753.672,1308.467 +- 562.708,307.866 +- 0.008
21,Boruta,MLP,0.9432 +- 0.0005,0.9406 +- 0.0019,0.8832 +- 0.0021,0.9099 +- 0.0011,0.9072 +- 0.0009,41.2000 +- 0.6325,21.386 +- 5.048,2190.907 +- 620.626,1709.690 +- 555.532,632.590 +- 9.484
22,GWO,MLP,0.9280 +- 0.0032,0.9253 +- 0.0065,0.8486 +- 0.0056,0.8827 +- 0.0060,0.8821 +- 0.0054,10.0000 +- 0.0000,190.621 +- 19.284,2458.539 +- 877.259,1112.970 +- 284.726,307.874 +- 0.027
23,LightGBM,MLP,0.8980 +- 0.0030,0.8649 +- 0.0060,0.7865 +- 0.0075,0.8197 +- 0.0061,0.8319 +- 0.0049,10.0000 +- 0.0000,820.573 +- 499.661,2929.257 +- 1101.812,1291.931 +- 521.288,307.869 +- 0.011
25,BA,RandomForest,0.9401 +- 0.0075,0.9130 +- 0.0232,0.9042 +- 0.0142,0.9069 +- 0.0193,0.9024 +- 0.0122,10.0000 +- 0.0000,145.015 +- 10.083,329.518 +- 61.102,38788.558 +- 11820.249,259.211 +- 2.268
26,Boruta,RandomForest,0.9601 +- 0.0001,0.9689 +- 0.0004,0.9319 +- 0.0001,0.9495 +- 0.0002,0.9349 +- 0.0001,41.2000 +- 0.6325,21.386 +- 5.048,388.908 +- 56.027,38485.466 +- 14031.357,632.632 +- 9.487
27,GWO,RandomForest,0.9516 +- 0.0034,0.9497 +- 0.0092,0.9234 +- 0.0028,0.9359 +- 0.0055,0.9212 +- 0.0055,10.0000 +- 0.0000,190.621 +- 19.284,329.133 +- 53.285,37471.584 +- 9200.681,259.497 +- 3.760
28,LightGBM,RandomForest,0.9543 +- 0.0007,0.9538 +- 0.0028,0.9209 +- 0.0015,0.9366 +- 0.0021,0.9255 +- 0.0011,10.0000 +- 0.0000,820.573 +- 499.661,381.883 +- 52.850,40840.456 +- 11812.759,259.460 +- 2.364

## Statistical Significance and Pairwise Tests

In [ ]:
try:
    from scipy.stats import friedmanchisquare, wilcoxon
    _HAS_SCIPY = True
except Exception:
    _HAS_SCIPY = False

def _prepare_pivot(df: pd.DataFrame, value_col: str, ordered_methods):
    pivot = df.pivot_table(index='seed', columns='method', values=value_col, aggfunc='mean')
    pivot = pivot.dropna(axis=1, how='all')
    ordered = [m for m in list(ordered_methods) if m in pivot.columns]
    pivot = pivot[ordered]
    pivot = pivot.dropna(axis=0, how='any')
    return pivot

def _holm_adjust(pvals):
    if len(pvals) == 0:
        return []
    order = np.argsort(pvals)
    ranked = np.asarray(pvals, dtype=float)[order]
    m = len(ranked)
    adj = np.empty(m, dtype=float)
    running = 0.0
    for i, p in enumerate(ranked):
        value = min(1.0, (m - i) * float(p))
        running = max(running, value)
        adj[i] = running
    restored = np.empty(m, dtype=float)
    restored[order] = adj
    return restored.tolist()

def _safe_wilcoxon(a, b):
    if (not _HAS_SCIPY) or (len(a) < 2):
        return None
    if np.allclose(np.asarray(a) - np.asarray(b), 0.0):
        return 1.0
    return float(wilcoxon(a, b, zero_method='wilcox').pvalue)

def global_significance_for_classifier(df: pd.DataFrame, clf_name: str, methods_list, metric: str = 'f1_macro'):
    sub = df[df['classifier'].astype(str) == str(clf_name)].copy()
    if sub.empty:
        return {'Classifier': str(clf_name), 'metric': metric, 'test': None, 'p_value': None, 'reason': 'no rows'}
    pivot = _prepare_pivot(sub, metric, methods_list)
    methods_avail = list(pivot.columns)
    n_runs = int(pivot.shape[0])
    if len(methods_avail) < 2 or n_runs < 2:
        return {'Classifier': str(clf_name), 'metric': metric, 'test': None, 'p_value': None, 'methods': methods_avail, 'n_runs': n_runs, 'reason': 'need >=2 methods with complete runs'}
    if not _HAS_SCIPY:
        return {'Classifier': str(clf_name), 'metric': metric, 'test': None, 'p_value': None, 'methods': methods_avail, 'n_runs': n_runs, 'reason': 'scipy not available'}
    if len(methods_avail) == 2:
        a, b = methods_avail
        p = _safe_wilcoxon(pivot[a].values, pivot[b].values)
        return {'Classifier': str(clf_name), 'metric': metric, 'test': 'Wilcoxon', 'p_value': p, 'methods': methods_avail, 'n_runs': n_runs}
    samples = [pivot[m].values for m in methods_avail]
    _, p = friedmanchisquare(*samples)
    return {'Classifier': str(clf_name), 'metric': metric, 'test': 'Friedman', 'p_value': float(p), 'methods': methods_avail, 'n_runs': n_runs}

def pairwise_vs_reference_for_classifier(df: pd.DataFrame, clf_name: str, methods_list, reference: str = 'GWO', metric: str = 'f1_macro'):
    sub = df[df['classifier'].astype(str) == str(clf_name)].copy()
    if sub.empty:
        return []
    pivot = _prepare_pivot(sub, metric, methods_list)
    if reference not in pivot.columns:
        return []
    rows = []
    pvals = []
    valid_idx = []
    for method in pivot.columns:
        if str(method) == str(reference):
            continue
        pair = pivot[[reference, method]].dropna(axis=0, how='any')
        n_runs = int(pair.shape[0])
        row = {
            'Classifier': str(clf_name),
            'metric': metric,
            'reference': str(reference),
            'comparison': str(method),
            'n_runs': n_runs,
            'mean_ref': float(pair[reference].mean()) if n_runs else np.nan,
            'mean_cmp': float(pair[method].mean()) if n_runs else np.nan,
            'wins_ref': int((pair[reference] > pair[method]).sum()) if n_runs else 0,
            'ties': int((pair[reference] == pair[method]).sum()) if n_runs else 0,
            'wins_cmp': int((pair[reference] < pair[method]).sum()) if n_runs else 0,
            'test': 'Wilcoxon',
            'p_value': None,
            'p_holm': None,
            'better_by_mean': str(reference) if (n_runs and pair[reference].mean() >= pair[method].mean()) else str(method)
        }
        if _HAS_SCIPY and n_runs >= 2:
            p = _safe_wilcoxon(pair[reference].values, pair[method].values)
            row['p_value'] = p
            if p is not None:
                valid_idx.append(len(rows))
                pvals.append(p)
        else:
            row['test'] = None
        rows.append(row)
    adj = _holm_adjust(pvals)
    for idx, p_adj in zip(valid_idx, adj):
        rows[idx]['p_holm'] = float(p_adj)
    return rows

def global_significance_for_fs(fs_df_local: pd.DataFrame, methods_list, metric: str = 'fs_time_s'):
    pivot = _prepare_pivot(fs_df_local.copy(), metric, methods_list)
    methods_avail = list(pivot.columns)
    n_runs = int(pivot.shape[0])
    if len(methods_avail) < 2 or n_runs < 2:
        return {'metric': metric, 'test': None, 'p_value': None, 'methods': methods_avail, 'n_runs': n_runs, 'reason': 'need >=2 methods with complete runs'}
    if not _HAS_SCIPY:
        return {'metric': metric, 'test': None, 'p_value': None, 'methods': methods_avail, 'n_runs': n_runs, 'reason': 'scipy not available'}
    if len(methods_avail) == 2:
        a, b = methods_avail
        p = _safe_wilcoxon(pivot[a].values, pivot[b].values)
        return {'metric': metric, 'test': 'Wilcoxon', 'p_value': p, 'methods': methods_avail, 'n_runs': n_runs}
    samples = [pivot[m].values for m in methods_avail]
    _, p = friedmanchisquare(*samples)
    return {'metric': metric, 'test': 'Friedman', 'p_value': float(p), 'methods': methods_avail, 'n_runs': n_runs}

def pairwise_vs_reference_for_fs(fs_df_local: pd.DataFrame, methods_list, reference: str = 'GWO', metric: str = 'fs_time_s'):
    pivot = _prepare_pivot(fs_df_local.copy(), metric, methods_list)
    if reference not in pivot.columns:
        return []
    rows = []
    pvals = []
    valid_idx = []
    for method in pivot.columns:
        if str(method) == str(reference):
            continue
        pair = pivot[[reference, method]].dropna(axis=0, how='any')
        n_runs = int(pair.shape[0])
        mean_ref = float(pair[reference].mean()) if n_runs else np.nan
        mean_cmp = float(pair[method].mean()) if n_runs else np.nan
        row = {
            'metric': metric,
            'reference': str(reference),
            'comparison': str(method),
            'n_runs': n_runs,
            'mean_ref': mean_ref,
            'mean_cmp': mean_cmp,
            'wins_ref': int((pair[reference] < pair[method]).sum()) if n_runs else 0,
            'ties': int((pair[reference] == pair[method]).sum()) if n_runs else 0,
            'wins_cmp': int((pair[reference] > pair[method]).sum()) if n_runs else 0,
            'test': 'Wilcoxon',
            'p_value': None,
            'p_holm': None,
            'faster_by_mean': str(reference) if (n_runs and mean_ref <= mean_cmp) else str(method)
        }
        if _HAS_SCIPY and n_runs >= 2:
            p = _safe_wilcoxon(pair[reference].values, pair[method].values)
            row['p_value'] = p
            if p is not None:
                valid_idx.append(len(rows))
                pvals.append(p)
        else:
            row['test'] = None
        rows.append(row)
    adj = _holm_adjust(pvals)
    for idx, p_adj in zip(valid_idx, adj):
        rows[idx]['p_holm'] = float(p_adj)
    return rows

print('Global significance for performance (f1_macro)')
sig_rows = []
for clf_name in sorted(raw_df['classifier'].astype(str).unique()):
    sig_rows.append(global_significance_for_classifier(raw_df, clf_name, methods, metric='f1_macro'))
sig_df = pd.DataFrame(sig_rows)
display(sig_df)

print('Pairwise post-hoc vs GWO for performance (f1_macro)')
pairwise_rows = []
for clf_name in sorted(raw_df['classifier'].astype(str).unique()):
    pairwise_rows.extend(pairwise_vs_reference_for_classifier(raw_df, clf_name, methods, reference='GWO', metric='f1_macro'))
pairwise_df = pd.DataFrame(pairwise_rows)
display(pairwise_df)

print('Global significance for feature-selection time (fs_time_s)')
sig_df_time = pd.DataFrame([global_significance_for_fs(fs_df, methods, metric='fs_time_s')])
display(sig_df_time)

print('Pairwise post-hoc vs GWO for feature-selection time (fs_time_s)')
pairwise_time_df = pd.DataFrame(pairwise_vs_reference_for_fs(fs_df, methods, reference='GWO', metric='fs_time_s'))
display(pairwise_time_df)

print('Global significance for number of selected features (n_selected)')
sig_df_n_selected = pd.DataFrame([global_significance_for_fs(fs_df, methods, metric='n_selected')])
display(sig_df_n_selected)

print('Pairwise post-hoc vs GWO for number of selected features (n_selected)')
pairwise_n_selected_df = pd.DataFrame(pairwise_vs_reference_for_fs(fs_df, methods, reference='GWO', metric='n_selected'))
display(pairwise_n_selected_df)

print('Stability summary (mean pairwise Jaccard across runs)')
display(stability_df)

Global significance for performance (f1_macro)

,Classifier,metric,test,p_value,methods,n_runs
0,DecisionTree,f1_macro,Friedman,1.767445e-07,"[GWO, BA, LightGBM, Boruta]",10
1,GaussianNB,f1_macro,Friedman,1.526142e-06,"[GWO, BA, LightGBM, Boruta]",10
2,HistGradientBoosting,f1_macro,Friedman,4.759058e-05,"[GWO, BA, LightGBM, Boruta]",10
3,LogisticRegression,f1_macro,Friedman,3.772312e-07,"[GWO, BA, LightGBM, Boruta]",10
4,MLP,f1_macro,Friedman,1.217218e-06,"[GWO, BA, LightGBM, Boruta]",10
5,RandomForest,f1_macro,Friedman,1.172166e-06,"[GWO, BA, LightGBM, Boruta]",10

Pairwise post-hoc vs GWO for performance (f1_macro)

,Classifier,metric,reference,comparison,n_runs,mean_ref,mean_cmp,wins_ref,ties,wins_cmp,test,p_value,p_holm,better_by_mean
0,DecisionTree,f1_macro,GWO,BA,10,0.937937,0.906709,10,0,0,Wilcoxon,0.001953,0.007812,GWO
2,DecisionTree,f1_macro,GWO,LightGBM,10,0.937937,0.928889,10,0,0,Wilcoxon,0.001953,0.007812,GWO
3,DecisionTree,f1_macro,GWO,Boruta,10,0.937937,0.947976,0,0,10,Wilcoxon,0.001953,0.007812,Boruta
4,GaussianNB,f1_macro,GWO,BA,10,0.529187,0.454936,8,0,2,Wilcoxon,0.019531,0.039062,GWO
6,GaussianNB,f1_macro,GWO,LightGBM,10,0.529187,0.343243,10,0,0,Wilcoxon,0.001953,0.007812,GWO
7,GaussianNB,f1_macro,GWO,Boruta,10,0.529187,0.618239,0,0,10,Wilcoxon,0.001953,0.007812,Boruta
8,HistGradientBoosting,f1_macro,GWO,BA,10,0.923381,0.898003,10,0,0,Wilcoxon,0.001953,0.007812,GWO
10,HistGradientBoosting,f1_macro,GWO,LightGBM,10,0.923381,0.915406,10,0,0,Wilcoxon,0.001953,0.007812,GWO
11,HistGradientBoosting,f1_macro,GWO,Boruta,10,0.923381,0.929961,3,0,7,Wilcoxon,0.160156,0.320312,Boruta
12,LogisticRegression,f1_macro,GWO,BA,10,0.542956,0.505700,8,0,2,Wilcoxon,0.027344,0.027344,GWO
14,LogisticRegression,f1_macro,GWO,LightGBM,10,0.542956,0.424663,10,0,0,Wilcoxon,0.001953,0.007812,GWO
15,LogisticRegression,f1_macro,GWO,Boruta,10,0.542956,0.723875,0,0,10,Wilcoxon,0.001953,0.007812,Boruta
16,MLP,f1_macro,GWO,BA,10,0.882702,0.846516,10,0,0,Wilcoxon,0.001953,0.007812,GWO
18,MLP,f1_macro,GWO,LightGBM,10,0.882702,0.819744,10,0,0,Wilcoxon,0.001953,0.007812,GWO
19,MLP,f1_macro,GWO,Boruta,10,0.882702,0.909913,0,0,10,Wilcoxon,0.001953,0.007812,Boruta
20,RandomForest,f1_macro,GWO,BA,10,0.935856,0.906875,10,0,0,Wilcoxon,0.001953,0.007812,GWO
22,RandomForest,f1_macro,GWO,LightGBM,10,0.935856,0.936615,5,0,5,Wilcoxon,0.695312,0.695312,LightGBM
23,RandomForest,f1_macro,GWO,Boruta,10,0.935856,0.949486,0,0,10,Wilcoxon,0.001953,0.007812,Boruta

Global significance for feature-selection time (fs_time_s)

      metric      test   p_value                           methods  n_runs
0  fs_time_s  Friedman  0.000002  [GWO, BA, LightGBM, Boruta]      10

Pairwise post-hoc vs GWO for feature-selection time (fs_time_s)

,metric,reference,comparison,n_runs,mean_ref,mean_cmp,wins_ref,ties,wins_cmp,test,p_value,p_holm,faster_by_mean
0,fs_time_s,GWO,BA,10,190.621071,145.014779,0,0,10,Wilcoxon,0.001953,0.007812,BA
2,fs_time_s,GWO,LightGBM,10,190.621071,820.572967,8,0,2,Wilcoxon,0.009766,0.009766,GWO
3,fs_time_s,GWO,Boruta,10,190.621071,21.385711,0,0,10,Wilcoxon,0.001953,0.007812,Boruta

Global significance for number of selected features (n_selected)

,metric,test,p_value,methods,n_runs
0,n_selected,Friedman,4.328423e-08,"[GWO, BA, LightGBM, Boruta]",10

Pairwise post-hoc vs GWO for number of selected features (n_selected)

,metric,reference,comparison,n_runs,mean_ref,mean_cmp,wins_ref,ties,wins_cmp,test,p_value,p_holm,faster_by_mean
0,n_selected,GWO,BA,10,10.0,10.0,0,10,0,Wilcoxon,1.000000,1.000000,GWO
2,n_selected,GWO,LightGBM,10,10.0,10.0,0,10,0,Wilcoxon,1.000000,1.000000,GWO
3,n_selected,GWO,Boruta,10,10.0,41.2,10,0,0,Wilcoxon,0.001953,0.007812,GWO

Stability summary (mean pairwise Jaccard across runs)

     method  mean_pairwise_jaccard  std_pairwise_jaccard  n_pairs
0    Boruta               0.969261              0.017814       45
1  LightGBM               0.927946              0.095033       45
3       GWO               0.248921              0.101118       45
4        BA               0.123380              0.068218       45

## Without FS

In [4]:
import random
import time
import tracemalloc
from itertools import combinations
from sklearn.base import clone
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, f1_score, matthews_corrcoef, precision_score, recall_score
from sklearn.model_selection import StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

N_RUNS = 10
RUN_SEEDS = list(range(N_RUNS))
K_SUP = 10
N_FEATURES_TOTAL = int(X.shape[1])

FS_MAX_SAMPLES = 50000
FS_EPOCHS = 30
FS_POP_SIZE = 10
FS_CV_FOLDS = 3

FS_FITNESS_MODEL = 'DecisionTree'
FS_FITNESS_SCORING = 'f1_macro'

EVAL_CV_FOLDS = 3

def _subsample_for_fs_local(X_in: np.ndarray, y_in: np.ndarray, max_samples: int, seed: int):
    if (max_samples is None) or (X_in.shape[0] <= int(max_samples)):
        return X_in, y_in
    rng = np.random.default_rng(int(seed))
    idx = rng.choice(X_in.shape[0], size=int(max_samples), replace=False)
    return X_in[idx], y_in[idx]

def evaluate_cv_eff(clf, X_sub: np.ndarray, y_sub: np.ndarray, cv_folds: int, seed: int):
    cvk = StratifiedKFold(n_splits=int(cv_folds), shuffle=True, random_state=int(seed))

    accs, precs, recs, f1s, mccs = [], [], [], [], []
    train_time_s = 0.0
    infer_time_ms = 0.0

    tracemalloc.start()
    for tr, te in cvk.split(X_sub, y_sub):
        model = Pipeline([
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', StandardScaler(with_mean=True)),
            ('clf', clone(clf))
        ])

        t0 = time.perf_counter()
        model.fit(X_sub[tr], y_sub[tr])
        train_time_s += (time.perf_counter() - t0)

        t1 = time.perf_counter()
        p = model.predict(X_sub[te])
        infer_time_ms += (time.perf_counter() - t1) * 1000.0

        accs.append(accuracy_score(y_sub[te], p))
        precs.append(precision_score(y_sub[te], p, average='macro', zero_division=0))
        recs.append(recall_score(y_sub[te], p, average='macro', zero_division=0))
        f1s.append(f1_score(y_sub[te], p, average='macro', zero_division=0))
        mccs.append(matthews_corrcoef(y_sub[te], p))

    current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    return {
        'accuracy': float(np.mean(accs)),
        'precision_macro': float(np.mean(precs)),
        'recall_macro': float(np.mean(recs)),
        'f1_macro': float(np.mean(f1s)),
        'mcc': float(np.mean(mccs)),
        'train_time_s': float(train_time_s),
        'inference_time_ms': float(infer_time_ms),
        'peak_mem_mb': float(peak) / (1024.0 * 1024.0)
    }

methods = ['Without FS']

clf_factories = {
    'RandomForest': lambda s: RandomForestClassifier(
        n_estimators=800,
        max_depth=30,
        min_samples_split=3,
        min_samples_leaf=1,
        max_features='sqrt',
        class_weight='balanced',
        max_samples=0.8,
        n_jobs=-1,
        random_state=42
    ),
    'DecisionTree': lambda s: DecisionTreeClassifier(random_state=int(s), class_weight='balanced'),
    'LogisticRegression': lambda s: LogisticRegression(max_iter=1000, class_weight='balanced', random_state=int(s)),
    'GaussianNB': lambda s: GaussianNB(),
    'HistGradientBoosting': lambda s: HistGradientBoostingClassifier(random_state=int(s), learning_rate=0.1),
    'MLP': lambda s: MLPClassifier(
        random_state=int(s),
        hidden_layer_sizes=(128, 64),
        max_iter=200,
        early_stopping=True,
        n_iter_no_change=10,
        validation_fraction=0.1
    )
}

fs_cache = {}

def make_fs_base(seed: int):
    if str(FS_FITNESS_MODEL).lower() in ['rf', 'randomforest', 'random_forest']:
        return RandomForestClassifier(
            n_estimators=120,
            max_depth=18,
            min_samples_split=4,
            min_samples_leaf=2,
            max_features='sqrt',
            bootstrap=True,
            max_samples=0.7,
            class_weight='balanced_subsample',
            n_jobs=-1,
            random_state=int(seed)
        )
    return DecisionTreeClassifier(random_state=int(seed), class_weight='balanced')

def _serialize_idx(idx):
    return ','.join(str(int(i)) for i in idx)

def _mean_pairwise_jaccard(index_sets):
    sets = [set(int(i) for i in s) for s in index_sets if len(s) > 0]
    if len(sets) < 2:
        return np.nan, np.nan, 0
    vals = []
    for a, b in combinations(sets, 2):
        union = len(a | b)
        vals.append(len(a & b) / union if union else 1.0)
    return float(np.mean(vals)), float(np.std(vals)), int(len(vals))

def get_idx_and_time(seed: int, method: str, X_fs: np.ndarray, y_fs: np.ndarray):
    key = (int(seed), str(method))
    if key in fs_cache:
        return fs_cache[key]

    random.seed(int(seed))
    np.random.seed(int(seed))

    base = make_fs_base(int(seed))
    t0 = time.perf_counter()
    if str(method) == 'Without FS':
        idx, _ = select_features_without_fs(X_fs, y_fs, clf=base, cv=FS_CV_FOLDS, scoring=str(FS_FITNESS_SCORING))
    else:
        raise ValueError(f'Unknown method: {method}')

    fs_time_s = float(time.perf_counter() - t0)
    fs_cache[key] = (idx, fs_time_s)
    return idx, fs_time_s

rows = []
for seed in RUN_SEEDS:
    X_fs, y_fs = _subsample_for_fs_local(X, y, FS_MAX_SAMPLES, seed)
    for method in methods:
        idx, fs_time_s = get_idx_and_time(seed, method, X_fs, y_fs)
        X_sub = X[:, idx]
        for clf_name, make_clf in clf_factories.items():
            m = evaluate_cv_eff(make_clf(seed), X_sub, y, cv_folds=EVAL_CV_FOLDS, seed=seed)
            rows.append({
                'seed': int(seed),
                'method': str(method),
                'classifier': str(clf_name),
                'k_target': int(K_SUP) if method in [] else np.nan,
                'n_selected': int(len(idx)),
                'selected_features': _serialize_idx(idx),
                'fs_time_s': float(fs_time_s),
                **m
            })

fs_rows = []
for (s, m), (idx, fs_time_s) in fs_cache.items():
    fs_rows.append({
        'seed': int(s),
        'method': str(m),
        'k_target': int(K_SUP) if str(m) in [] else np.nan,
        'n_selected': int(len(idx)),
        'selected_features': _serialize_idx(idx),
        'fs_time_s': float(fs_time_s)
    })
fs_df = pd.DataFrame(fs_rows)
fs_df = fs_df.sort_values(['seed', 'method']).reset_index(drop=True)
display(fs_df)
display(fs_df.groupby('method', as_index=False)[['fs_time_s', 'n_selected']].agg(['mean', 'std']).reset_index())

stability_rows = []
for method_name, sub_df in fs_df.groupby('method'):
    sets = []
    for txt in sub_df['selected_features'].astype(str):
        sets.append([int(x) for x in txt.split(',') if str(x).strip() != ''])
    mean_j, std_j, n_pairs = _mean_pairwise_jaccard(sets)
    stability_rows.append({
        'method': str(method_name),
        'mean_pairwise_jaccard': mean_j,
        'std_pairwise_jaccard': std_j,
        'n_pairs': n_pairs
    })
stability_df = pd.DataFrame(stability_rows).sort_values('mean_pairwise_jaccard', ascending=False).reset_index(drop=True)
print('Feature-selection stability across runs')
display(stability_df)

raw_df = pd.DataFrame(rows)
display(raw_df)
print('Rows:', len(raw_df))

metrics_cols = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro', 'mcc', 'fs_time_s', 'train_time_s', 'inference_time_ms', 'peak_mem_mb', 'n_selected']

means = raw_df.groupby(['method', 'classifier'])[metrics_cols].mean().reset_index()
means = means.rename(columns={
    'method': 'Algorithm',
    'classifier': 'Classifier',
    'accuracy': 'Accuracy',
    'precision_macro': 'Precision',
    'recall_macro': 'Recall',
    'f1_macro': 'F1_macro',
    'mcc': 'MCC',
    'n_selected': 'N_Selected'
})

eval_df = means[['Algorithm', 'Classifier', 'Accuracy', 'Precision', 'Recall', 'F1_macro', 'MCC', 'N_Selected', 'fs_time_s', 'train_time_s', 'inference_time_ms', 'peak_mem_mb']].copy()
eval_df = eval_df.sort_values(['F1_macro', 'MCC', 'Accuracy'], ascending=[False, False, False]).reset_index(drop=True)
display(eval_df)

print('Deployment-oriented summary (lower downstream cost is better)')
deployment_df = eval_df[['Algorithm', 'Classifier', 'N_Selected', 'train_time_s', 'inference_time_ms', 'peak_mem_mb']].copy()
deployment_df = deployment_df.sort_values(['N_Selected', 'peak_mem_mb', 'inference_time_ms', 'train_time_s'], ascending=[True, True, True, True]).reset_index(drop=True)
display(deployment_df)

agg = raw_df.groupby(['method', 'classifier'])[metrics_cols].agg(['mean', 'std'])
agg.columns = [f"{m}_{s}" for (m, s) in agg.columns]
agg = agg.reset_index()

def fmt_pair(m, s, is_time=False):
    if pd.isna(m):
        return ''
    if pd.isna(s):
        return f"{m:.4f}" if not is_time else f"{m:.3f}"
    return (f"{m:.4f} +- {s:.4f}" if not is_time else f"{m:.3f} +- {s:.3f}")

final_table = pd.DataFrame({
    'Method': agg['method'].astype(str),
    'Classifier': agg['classifier'].astype(str),
})

for src, dst in {
    'accuracy': 'accuracy',
    'precision_macro': 'precision_macro',
    'recall_macro': 'recall_macro',
    'f1_macro': 'f1_macro',
    'mcc': 'mcc',
    'n_selected': 'n_selected',
    'fs_time_s': 'fs_time_s',
    'train_time_s': 'train_time_s',
    'inference_time_ms': 'inference_time_ms',
    'peak_mem_mb': 'peak_mem_mb'
}.items():
    mcol = f"{src}_mean"
    scol = f"{src}_std"
    is_time = src in ['fs_time_s', 'train_time_s', 'inference_time_ms', 'peak_mem_mb']
    final_table[dst] = [fmt_pair(m, s, is_time=is_time) for m, s in zip(agg[mcol], agg[scol])]

final_table = final_table.sort_values(['Classifier', 'Method']).reset_index(drop=True)
display(final_table)

,seed,method,k_target,n_selected,selected_features,fs_time_s
0,0,Without FS,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.929884
1,1,Without FS,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.836359
2,2,Without FS,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.947452
3,3,Without FS,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.933598
4,4,Without FS,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.950988
5,5,Without FS,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.758935
6,6,Without FS,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",2.004424
7,7,Without FS,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.932611
8,8,Without FS,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.864838
9,9,Without FS,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.952452

  index      method fs_time_s           n_selected
                         mean       std       mean  std
0     0  Without FS  1.911154  0.071129       51.0  0.0

Feature-selection stability across runs

       method  mean_pairwise_jaccard  std_pairwise_jaccard  n_pairs
0  Without FS                    1.0                   0.0       45

,seed,method,classifier,k_target,n_selected,selected_features,fs_time_s,accuracy,precision_macro,recall_macro,f1_macro,mcc,train_time_s,inference_time_ms,peak_mem_mb
0,0,Without FS,RandomForest,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.929884,0.959928,0.968909,0.931891,0.949517,0.934710,249.451818,8387.550500,779.756327
1,0,Without FS,DecisionTree,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.929884,0.962322,0.971591,0.924790,0.947068,0.938656,36.403723,441.553563,779.554370
2,0,Without FS,LogisticRegression,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.929884,0.868607,0.718194,0.824532,0.751872,0.791711,366.474471,704.423522,779.552401
3,0,Without FS,GaussianNB,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.929884,0.778467,0.631963,0.617641,0.599059,0.647655,8.423856,1376.084547,779.545933
4,0,Without FS,HistGradientBoosting,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.929884,0.945683,0.924071,0.890753,0.902975,0.911629,79.777777,4905.024719,779.641213
5,0,Without FS,MLP,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.929884,0.944441,0.947243,0.883133,0.912693,0.909277,654.772901,957.965766,779.561975
6,1,Without FS,RandomForest,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.836359,0.960001,0.969379,0.931691,0.949633,0.934832,258.811721,7583.350242,779.610837
7,1,Without FS,DecisionTree,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.836359,0.962662,0.972433,0.924915,0.947527,0.939223,37.103135,427.053935,779.552803
8,1,Without FS,LogisticRegression,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.836359,0.868778,0.718932,0.825030,0.752816,0.791941,362.769937,484.537416,779.550624
9,1,Without FS,GaussianNB,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.836359,0.778066,0.631795,0.617254,0.598522,0.646993,8.766534,1212.404043,779.544991
10,1,Without FS,HistGradientBoosting,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.836359,0.949677,0.937162,0.900634,0.915185,0.918169,78.249909,4224.758629,779.610469
11,1,Without FS,MLP,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.836359,0.943391,0.940196,0.885891,0.911234,0.907547,501.107895,827.086218,779.554408
12,2,Without FS,RandomForest,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.947452,0.960125,0.968926,0.931886,0.949518,0.935036,257.456268,9004.750232,779.605931
13,2,Without FS,DecisionTree,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.947452,0.962814,0.972833,0.925624,0.948100,0.939469,35.884399,396.449129,779.549415
14,2,Without FS,LogisticRegression,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.947452,0.868630,0.718831,0.824720,0.752487,0.791727,356.118739,367.471443,779.549870
15,2,Without FS,GaussianNB,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.947452,0.777823,0.631446,0.616401,0.596996,0.646585,8.156796,1263.954384,779.545492
16,2,Without FS,HistGradientBoosting,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.947452,0.952906,0.962474,0.908186,0.933526,0.923420,58.004903,2917.364496,779.598882
17,2,Without FS,MLP,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.947452,0.944576,0.949865,0.880608,0.912531,0.909417,788.329857,1160.454669,779.552986
18,3,Without FS,RandomForest,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.933598,0.960068,0.969083,0.932012,0.949674,0.934941,259.990677,7666.183269,779.588181
19,3,Without FS,DecisionTree,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.933598,0.962688,0.972599,0.925587,0.947962,0.939264,36.031745,517.883702,779.550279
20,3,Without FS,LogisticRegression,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.933598,0.868499,0.718128,0.824502,0.751920,0.791551,362.941530,494.011680,779.548878
21,3,Without FS,GaussianNB,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.933598,0.778055,0.631611,0.616742,0.597895,0.646964,8.260699,1204.430586,779.544455
22,3,Without FS,HistGradientBoosting,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.933598,0.954953,0.967920,0.912853,0.938721,0.926819,81.354376,4639.640085,779.606297
23,3,Without FS,MLP,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.933598,0.944665,0.945449,0.887302,0.914567,0.909634,750.356256,931.639862,779.556447
24,4,Without FS,RandomForest,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.950988,0.960059,0.968739,0.932141,0.949581,0.934930,257.833148,8090.167076,779.614834
25,4,Without FS,DecisionTree,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.950988,0.963058,0.973065,0.925941,0.948353,0.939878,35.375691,396.693424,779.545511
26,4,Without FS,LogisticRegression,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.950988,0.868802,0.718736,0.825048,0.752579,0.791990,367.343157,561.134590,779.553313
27,4,Without FS,GaussianNB,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.950988,0.778018,0.630793,0.616785,0.597730,0.646937,8.304764,1264.494224,779.544766
28,4,Without FS,HistGradientBoosting,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.950988,0.955833,0.974008,0.913837,0.942077,0.928285,76.643318,5033.748067,779.614500
29,4,Without FS,MLP,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.950988,0.943916,0.944737,0.883262,0.912038,0.908342,610.707429,698.199888,779.552453
30,5,Without FS,RandomForest,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.758935,0.959975,0.968968,0.931844,0.949534,0.934789,258.694400,9747.349811,779.607201
31,5,Without FS,DecisionTree,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.758935,0.962582,0.972382,0.925548,0.947843,0.939090,35.503548,492.286446,779.553538
32,5,Without FS,LogisticRegression,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.758935,0.868798,0.718998,0.824880,0.752872,0.791957,367.503070,552.600491,779.549030
33,5,Without FS,GaussianNB,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.758935,0.777962,0.632235,0.617110,0.598357,0.646839,8.081527,1149.157145,779.545877
34,5,Without FS,HistGradientBoosting,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.758935,0.951183,0.959930,0.900441,0.928199,0.920601,68.933497,3718.902268,779.599741
35,5,Without FS,MLP,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.758935,0.944365,0.944250,0.885465,0.912720,0.909148,762.752397,972.462458,779.557685
36,6,Without FS,RandomForest,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",2.004424,0.960061,0.968634,0.932348,0.949646,0.934935,262.401882,7926.582573,779.592548
37,6,Without FS,DecisionTree,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",2.004424,0.962967,0.973513,0.927028,0.949163,0.939728,36.290826,396.717069,779.548946
38,6,Without FS,LogisticRegression,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",2.004424,0.868703,0.718523,0.824733,0.752324,0.791832,366.523182,385.484217,779.552355
39,6,Without FS,GaussianNB,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",2.004424,0.778481,0.632148,0.617618,0.599141,0.647668,8.699630,1197.942912,779.545114
40,6,Without FS,HistGradientBoosting,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",2.004424,0.956211,0.975772,0.916532,0.944354,0.928879,86.004010,5571.294920,779.610151
41,6,Without FS,MLP,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",2.004424,0.943355,0.944335,0.882854,0.911276,0.907564,513.717269,827.697345,779.556504
42,7,Without FS,RandomForest,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.932611,0.959911,0.968318,0.931698,0.949153,0.934687,256.788704,7956.641460,779.612212
43,7,Without FS,DecisionTree,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.932611,0.963007,0.972454,0.926233,0.948239,0.939796,34.843331,473.252073,779.552045
44,7,Without FS,LogisticRegression,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.932611,0.869168,0.719424,0.825156,0.753374,0.792496,362.569824,584.750163,779.549293
45,7,Without FS,GaussianNB,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.932611,0.777869,0.631140,0.616413,0.597188,0.646687,7.887868,1144.897638,779.543818
46,7,Without FS,HistGradientBoosting,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.932611,0.948463,0.927742,0.896477,0.909362,0.916144,90.747373,7495.543060,779.614066
47,7,Without FS,MLP,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.932611,0.944642,0.945543,0.886781,0.914171,0.909611,798.422770,763.458315,779.550493
48,8,Without FS,RandomForest,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.864838,0.959921,0.968519,0.931917,0.949363,0.934700,256.649206,8058.984691,779.617854
49,8,Without FS,DecisionTree,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.864838,0.962777,0.973019,0.925947,0.948345,0.939415,36.025494,404.807394,779.551787
50,8,Without FS,LogisticRegression,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.864838,0.868988,0.719353,0.825169,0.753176,0.792236,363.471321,486.084619,779.550866
51,8,Without FS,GaussianNB,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.864838,0.778651,0.632508,0.617827,0.599291,0.647939,7.808374,1110.234081,779.545112
52,8,Without FS,HistGradientBoosting,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.864838,0.952632,0.958816,0.905271,0.930377,0.922991,80.235452,4790.831794,779.612452
53,8,Without FS,MLP,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.864838,0.945163,0.948565,0.886614,0.915641,0.910449,951.285154,863.789877,779.554668
54,9,Without FS,RandomForest,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.952452,0.960165,0.969018,0.932091,0.949682,0.935106,262.621735,11290.619289,779.599897
55,9,Without FS,DecisionTree,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.952452,0.962611,0.971721,0.924883,0.947187,0.939142,35.654706,455.674980,779.551826
56,9,Without FS,LogisticRegression,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.952452,0.868856,0.718740,0.825193,0.752614,0.792074,362.896744,491.942892,779.548078
57,9,Without FS,GaussianNB,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.952452,0.778020,0.631615,0.616853,0.598188,0.646939,8.270572,1270.383883,779.544628
58,9,Without FS,HistGradientBoosting,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.952452,0.954404,0.966268,0.910543,0.936727,0.925921,71.940501,3685.807190,779.610482
59,9,Without FS,MLP,NaN,51,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50",1.952452,0.944870,0.948154,0.885556,0.914575,0.910047,714.056372,862.779751,779.551722

Rows: 60

,Algorithm,Classifier,Accuracy,Precision,Recall,F1_macro,MCC,N_Selected,fs_time_s,train_time_s,inference_time_ms,peak_mem_mb
0,Without FS,RandomForest,0.960021,0.968849,0.931952,0.949530,0.934867,51.0,1.911154,258.069956,8571.217914,779.620582
1,Without FS,DecisionTree,0.962749,0.972561,0.925650,0.947979,0.939366,51.0,1.911154,35.911660,440.237171,779.551052
2,Without FS,HistGradientBoosting,0.952194,0.955416,0.905553,0.928150,0.922286,51.0,1.911154,77.189112,4698.291523,779.611825
3,Without FS,MLP,0.944338,0.945834,0.884746,0.913144,0.909104,51.0,1.911154,704.550830,886.553415,779.554934
4,Without FS,LogisticRegression,0.868783,0.718786,0.824896,0.752603,0.791952,51.0,1.911154,363.861198,511.244103,779.550471
5,Without FS,GaussianNB,0.778141,0.631725,0.617064,0.598237,0.647121,51.0,1.911154,8.266062,1219.398344,779.545019

Deployment-oriented summary (lower downstream cost is better)

,Algorithm,Classifier,N_Selected,train_time_s,inference_time_ms,peak_mem_mb
0,Without FS,GaussianNB,51.0,8.266062,1219.398344,779.545019
1,Without FS,LogisticRegression,51.0,363.861198,511.244103,779.550471
2,Without FS,DecisionTree,51.0,35.911660,440.237171,779.551052
3,Without FS,MLP,51.0,704.550830,886.553415,779.554934
4,Without FS,HistGradientBoosting,51.0,77.189112,4698.291523,779.611825
5,Without FS,RandomForest,51.0,258.069956,8571.217914,779.620582

,Method,Classifier,accuracy,precision_macro,recall_macro,f1_macro,mcc,n_selected,fs_time_s,train_time_s,inference_time_ms,peak_mem_mb
0,Without FS,DecisionTree,0.9627 +- 0.0002,0.9726 +- 0.0006,0.9256 +- 0.0007,0.9480 +- 0.0006,0.9394 +- 0.0004,51.0000 +- 0.0000,1.911 +- 0.071,35.912 +- 0.623,440.237 +- 43.722,779.551 +- 0.003
1,Without FS,GaussianNB,0.7781 +- 0.0003,0.6317 +- 0.0005,0.6171 +- 0.0005,0.5982 +- 0.0008,0.6471 +- 0.0005,51.0000 +- 0.0000,1.911 +- 0.071,8.266 +- 0.310,1219.398 +- 77.677,779.545 +- 0.001
2,Without FS,HistGradientBoosting,0.9522 +- 0.0034,0.9554 +- 0.0188,0.9056 +- 0.0083,0.9282 +- 0.0143,0.9223 +- 0.0056,51.0000 +- 0.0000,1.911 +- 0.071,77.189 +- 9.189,4698.292 +- 1253.186,779.612 +- 0.012
3,Without FS,LogisticRegression,0.8688 +- 0.0002,0.7188 +- 0.0004,0.8249 +- 0.0003,0.7526 +- 0.0005,0.7920 +- 0.0003,51.0000 +- 0.0000,1.911 +- 0.071,363.861 +- 3.400,511.244 +- 97.424,779.550 +- 0.002
4,Without FS,MLP,0.9443 +- 0.0006,0.9458 +- 0.0028,0.8847 +- 0.0022,0.9131 +- 0.0015,0.9091 +- 0.0010,51.0000 +- 0.0000,1.911 +- 0.071,704.551 +- 137.992,886.553 +- 128.343,779.555 +- 0.003
5,Without FS,RandomForest,0.9600 +- 0.0001,0.9688 +- 0.0003,0.9320 +- 0.0002,0.9495 +- 0.0002,0.9349 +- 0.0001,51.0000 +- 0.0000,1.911 +- 0.071,258.070 +- 3.689,8571.218 +- 1158.646,779.621 +- 0.049