# Edge-IIoTset Intrusion Detection - GWO

In [1]:
!pip install scikit-learn
!pip install mealpy
!pip install Boruta
!pip install lightgbm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
from typing import List, Tuple, Dict, Optional
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, make_scorer, confusion_matrix, ConfusionMatrixDisplay, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.feature_selection import VarianceThreshold
_HAS_MEALPY = False
_HAS_BORUTA = False
try:
    from boruta import BorutaPy
    _HAS_BORUTA = True
    print('BorutaPy available')
except Exception:
    _HAS_BORUTA = False
    print('BorutaPy not available yet. Run the install cell, then re-run this cell.')
try:
    from mealpy.swarm_based import GWO, BA
    _HAS_MEALPY = True
    print("Mealpy available: GWO/BA")
except Exception:
    _HAS_MEALPY = False
    print("Mealpy not available. Using fallback feature selection.")

_HAS_FLOATVAR = False
try:
    from mealpy import FloatVar
    _HAS_FLOATVAR = True
except Exception:
    _HAS_FLOATVAR = False

plt.style.use('seaborn-v0_8-darkgrid')

Requirement already satisfied: scikit-learn in ./.venv/lib/python3.12/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (3.6.0)

Requirement already satisfied: mealpy in ./.venv/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.17.5 in ./.venv/lib/python3.12/site-packages (from mealpy) (2.4.6)
Requirement already satisfied: matplotlib>=3.3.0 in ./.venv/lib/python3.12/site-packages (from mealpy) (3.10.9)
Requirement already satisfied: scipy>=1.7.1 in ./.venv/lib/python3.12/site-packages (from mealpy) (1.17.1)
Requirement already satisfied: pandas>=1.2.0 in ./.venv/lib/python3.12/site-packages (from mealpy) (3.0.3)
Requirement already satisfied: opfunu>=1.0.0 in ./.venv/lib/python3.12/site-packages (from mealpy) (1.0.1)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (26.2)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (12.2.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.12/site-packages (from matplotlib>=3.3.0->mealpy) (2.9.0.post0)
Requirement already satisfied: requests>=2.27.0 in ./.venv/lib/python3.12/site-packages (from opfunu>=1.0.0->mealpy) (2.34.2)

Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->mealpy) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests>=2.27.0->opfunu>=1.0.0->mealpy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.12/site-packages (from requests>=2.27.0->opfunu>=1.0.0->mealpy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.12/site-packages (from requests>=2.27.0->opfunu>=1.0.0->mealpy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.12/site-packages (from requests>=2.27.0->opfunu>=1.0.0->mealpy) (2026.5.20)

Requirement already satisfied: Boruta in ./.venv/lib/python3.12/site-packages (0.4.3)
Requirement already satisfied: numpy>=1.10.4 in ./.venv/lib/python3.12/site-packages (from Boruta) (2.4.6)
Requirement already satisfied: scikit-learn>=0.17.1 in ./.venv/lib/python3.12/site-packages (from Boruta) (1.9.0)
Requirement already satisfied: scipy>=0.17.0 in ./.venv/lib/python3.12/site-packages (from Boruta) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn>=0.17.1->Boruta) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in ./.venv/lib/python3.12/site-packages (from scikit-learn>=0.17.1->Boruta) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn>=0.17.1->Boruta) (3.6.0)

Requirement already satisfied: lightgbm in ./.venv/lib/python3.12/site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in ./.venv/lib/python3.12/site-packages (from lightgbm) (2.4.6)
Requirement already satisfied: scipy in ./.venv/lib/python3.12/site-packages (from lightgbm) (1.17.1)

BorutaPy available

Mealpy available: GWO/BA

## Feature Selection Functions (GWO + Original BorutaPy + Optional BA Helpers + Without FS)

In [2]:
def _evaluate_subset(
    X: np.ndarray, y: np.ndarray, idx: List[int],
    clf=None, cv: int = 3, scoring: str = 'accuracy',
    lam: float = 0.01,
    alpha_fp: float = 0.0,   # set >0 later if you want explicit false-positive penalty
    benign_id: Optional[int] = None
) -> float:
    if len(idx) == 0:
        return 0.0

    # CHANGED: default classifier now class-weighted for robustness
    if clf is None:
        clf = DecisionTreeClassifier(random_state=42, class_weight='balanced')

    pipe = Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler(with_mean=True)),
        ('clf', clf)
    ])

    X_sub = X[:, idx]
    cvk = StratifiedKFold(n_splits=cv, shuffle=True, random_state=42)

    scorer = 'accuracy' if scoring == 'accuracy' else make_scorer(f1_score, average='macro')

    # Base CV score
    scores = cross_val_score(pipe, X_sub, y, scoring=scorer, cv=cvk, n_jobs=None)
    base = float(np.mean(scores))

    # Compactness penalty
    size_penalty = lam * (len(idx) / X.shape[1])

    # Optional false-positive penalty (OFF by default)
    fp_penalty = 0.0
    if alpha_fp > 0.0 and benign_id is not None:
        fprs = []
        for tr, te in cvk.split(X_sub, y):
            pipe.fit(X_sub[tr], y[tr])
            p = pipe.predict(X_sub[te])
            y_te = y[te]
            benign = (y_te == benign_id)
            fp = np.sum((p != benign_id) & benign)
            tn = np.sum((p == benign_id) & benign)
            fprs.append(fp / (fp + tn + 1e-12))
        fp_penalty = alpha_fp * float(np.mean(fprs))

    return base - size_penalty - fp_penalty

# =========================================
# Convergence History Storage (Global)
# =========================================
convergence_history = {}

def _optimize_continuous(
    OptimizerClass, X: np.ndarray, y: np.ndarray, k: int,
    clf=None, epochs: int = 30, pop_size: int = 30,
    cv: int = 3, scoring: str = 'accuracy', seed: int = 42
) -> Tuple[List[int], float]:

    dim = X.shape[1]
    lb_vec = [0.0] * dim
    ub_vec = [1.0] * dim

    lambda_max = 0.05
    lambda_min = 0.005

    total_calls = epochs * pop_size
    call_counter = {'n': 0}

    history = []

    def fitness(w):
        call_counter['n'] += 1
        progress = min(call_counter['n'] / total_calls, 1.0)
        t = progress * epochs

        a_t = 2 - 2 * (t / epochs)
        lam_dynamic = lambda_min + (lambda_max - lambda_min) * (a_t / 2)

        w = np.asarray(w)
        idx = list(range(dim)) if k >= dim else list(np.argsort(-w)[:k])

        score = _evaluate_subset(
            X, y, idx,
            clf=clf,
            cv=cv,
            scoring=scoring,
            lam=lam_dynamic
        )

        history.append(score)
        return score

    random.seed(int(seed))
    np.random.seed(int(seed))

    problem_mealpy = {
        'obj_func': fitness,
        'minmax': 'max',
        'lb': lb_vec,
        'ub': ub_vec,
        'seed': int(seed)
    }

    if _HAS_FLOATVAR:
        problem_mealpy['bounds'] = FloatVar(lb=lb_vec, ub=ub_vec)

    if isinstance(OptimizerClass, type):
        opt = OptimizerClass(epoch=epochs, pop_size=pop_size)
        res = opt.solve(problem_mealpy)
        algo_name = OptimizerClass.__name__
    else:
        if hasattr(OptimizerClass, 'OriginalGWO'):
            opt = OptimizerClass.OriginalGWO(epoch=epochs, pop_size=pop_size)
            algo_name = "GWO"
        elif hasattr(OptimizerClass, 'OriginalBA'):
            opt = OptimizerClass.OriginalBA(epoch=epochs, pop_size=pop_size)
            algo_name = "BA"
        else:
            raise TypeError('Unsupported optimizer type')
        res = opt.solve(problem_mealpy)

    best_pos = res[0] if isinstance(res, tuple) else res.solution

    # Save convergence history
    convergence_history[f"{algo_name}_k{k}"] = history

    w = np.asarray(best_pos)
    idx = list(range(dim)) if k >= dim else list(np.argsort(-w)[:k])

    final_lambda = lambda_min
    score = _evaluate_subset(
        X, y, idx,
        clf=clf,
        cv=cv,
        scoring=scoring,
        lam=final_lambda
    )

    return idx, score


def select_features_gwo(X, y, k, clf=None, epochs=30, pop_size=30, cv=3, scoring='accuracy', seed: int = 42):
    if _HAS_MEALPY:
        return _optimize_continuous(GWO, X, y, k, clf, epochs, pop_size, cv, scoring, seed=seed)

    from sklearn.feature_selection import mutual_info_classif
    mi = mutual_info_classif(X, y, random_state=42)
    idx = list(np.argsort(-mi)[:k])

    # CHANGED: apply penalty in fallback too
    return idx, _evaluate_subset(X, y, idx, clf=clf, cv=cv, scoring=scoring, lam=0.01)


def select_features_ba(X, y, k, clf=None, epochs=30, pop_size=30, cv=3, scoring='accuracy'):
    if _HAS_MEALPY:
        return _optimize_continuous(BA, X, y, k, clf, epochs, pop_size, cv, scoring)

    from sklearn.feature_selection import mutual_info_classif
    mi = mutual_info_classif(X, y, random_state=42)
    idx = list(np.argsort(-mi)[:k])

    # CHANGED: apply penalty in fallback too
    return idx, _evaluate_subset(X, y, idx, clf=clf, cv=cv, scoring=scoring, lam=0.01)


def select_features_boruta(X, y, k=None, clf=None, cv=3, scoring='accuracy', seed: int = 42):
    if not _HAS_BORUTA:
        raise ImportError("BorutaPy is not available. Install Boruta, then rerun the imports cell.")

    X_imp = SimpleImputer(strategy='median').fit_transform(X)
    y_arr = np.asarray(y)
    dim = int(X_imp.shape[1])

    rf = RandomForestClassifier(
   n_estimators=800,
    max_depth=30,
    min_samples_split=3,
    min_samples_leaf=1,
    max_features='sqrt',
    class_weight='balanced',
    max_samples=0.8,
    n_jobs=-1,
    random_state=42
    )

    boruta = BorutaPy(
        estimator=rf,
        n_estimators='auto',
        perc=100,
        alpha=0.05,
        two_step=True,
        max_iter=15,
        random_state=int(seed),
        verbose=0
    )
    boruta.fit(X_imp, y_arr)

    idx = list(np.where(np.asarray(boruta.support_, dtype=bool))[0])
    if len(idx) == 0:
        ranking = np.asarray(getattr(boruta, 'ranking_', np.ones(dim)), dtype=float)
        idx = [int(np.argmin(ranking))]

    return idx, _evaluate_subset(X, y_arr, idx, clf=clf, cv=cv, scoring=scoring, lam=0.0)


def select_features_hybrid_boruta(X, y, k, clf=None, cv=3, scoring='accuracy', seed: int = 42):
    X_imp = SimpleImputer(strategy='median').fit_transform(X)
    y_arr = np.asarray(y)
    dim = int(X_imp.shape[1])
    kk = int(min(max(int(k), 1), dim))

    rng = np.random.default_rng(int(seed))
    n_iter = int(max(10, int(cv) * 3))
    wins = np.zeros(dim, dtype=float)
    imp_sum = np.zeros(dim, dtype=float)

    for _ in range(n_iter):
        X_shadow = X_imp.copy()
        for j in range(dim):
            rng.shuffle(X_shadow[:, j])
        X_aug = np.hstack([X_imp, X_shadow])

        rf = RandomForestClassifier(
       n_estimators=800,
    max_depth=30,
    min_samples_split=3,
    min_samples_leaf=1,
    max_features='sqrt',
    class_weight='balanced',
    max_samples=0.8,
    n_jobs=-1,
    random_state=42
        )
        rf.fit(X_aug, y_arr)
        imp = np.asarray(getattr(rf, 'feature_importances_', None), dtype=float)
        if imp is None or imp.size != (2 * dim):
            raise RuntimeError('rf importances not available')

        real_imp = imp[:dim]
        shadow_imp = imp[dim:]
        thr = float(np.max(shadow_imp))
        wins += (real_imp > thr).astype(float)
        imp_sum += real_imp

    score = wins + 1e-3 * (imp_sum / float(n_iter))
    idx = list(np.argsort(-score)[:kk])
    return idx, _evaluate_subset(X, y_arr, idx, clf=clf, cv=cv, scoring=scoring, lam=0.01)


def select_features_without_fs(X, y, clf=None, cv=3, scoring='accuracy'):
    idx = list(range(X.shape[1]))
    return idx, _evaluate_subset(X, y, idx, clf=clf, cv=cv, scoring=scoring, lam=0.0)


def select_features_lightgbm(X, y, k, clf=None, cv=3, scoring='accuracy', seed: int = 42):
    try:
        from lightgbm import LGBMClassifier
    except ImportError:
        raise ImportError('lightgbm is not available.')
    X_imp = SimpleImputer(strategy='median').fit_transform(X)
    y_arr = np.asarray(y)
    kk = int(min(max(int(k), 1), X_imp.shape[1]))
    n_classes = len(np.unique(y_arr))
    objective = 'binary' if n_classes <= 2 else 'multiclass'
    model = LGBMClassifier(
        n_estimators=800,
        learning_rate=0.05,
        num_leaves=31,
        subsample=0.8,
        colsample_bytree=0.8,
        objective=objective,
        class_weight='balanced',
        random_state=int(seed),
        verbosity=-1
    )
    model.fit(X_imp, y_arr)
    imp = np.asarray(getattr(model, 'feature_importances_', np.zeros(X_imp.shape[1])), dtype=float)
    if imp.size != X_imp.shape[1] or np.all(imp == 0):
        raise RuntimeError('LightGBM importances not available')
    idx = list(np.argsort(-imp)[:kk])
    return idx, _evaluate_subset(X, y_arr, idx, clf=clf, cv=cv, scoring=scoring, lam=0.01)


def run_all_algorithms(X, y, ks: List[int], clf=None, epochs=30, pop_size=30, cv=3, feature_names: Optional[List[str]] = None, scoring='accuracy') -> Dict[str, Dict[int, Dict]]:
    results = {'GWO': {}, 'BA': {}, 'LightGBM': {}, 'Boruta': {}}
    for k in ks:
        idx_gwo, s_gwo = select_features_gwo(X, y, k, clf, epochs, pop_size, cv, scoring)
        idx_ba, s_ba = select_features_ba(X, y, k, clf, epochs, pop_size, cv, scoring)
        idx_lgbm, s_lgbm = select_features_lightgbm(X, y, k, clf, cv=cv, scoring=scoring)
        idx_boruta, s_boruta = select_features_boruta(X, y, None, clf, cv=cv, scoring=scoring, seed=42)

        for algo, idx, score in [('GWO', idx_gwo, s_gwo), ('BA', idx_ba, s_ba), ('LightGBM', idx_lgbm, s_lgbm), ('Boruta', idx_boruta, s_boruta)]:
            feats = [feature_names[i] for i in idx] if feature_names else None
            results[algo][k] = {'indices': idx, 'score': score, 'features': feats}

    return results

## Load Data + Cleaning + Dimensionality Reduction

In [3]:
print('Loading and preprocessing dataset...')
all_data = r"/root/iiot-run/data/cleaned_Edge-IIoTset_aligned.csv"

print('Loading data...')
combined_data = pd.read_csv(all_data, on_bad_lines='skip')
#combined_data = pd.read_csv(all_data, on_bad_lines='skip').sample(n=3000, random_state=42)

print(f"Dataset loaded successfully!")
print(f"   - Total samples: {len(combined_data)}")
print(f"   - Features: {combined_data.shape[1] - 1}")

# -------- Detect label column (label2 preferred, else label1)
label_col_src = None
for col in combined_data.columns:
    cl = col.lower()
    if 'label2' in cl:
        label_col_src = col
        break
    if 'label1' in cl and label_col_src is None:
        label_col_src = col

if label_col_src:
    label_percent = (combined_data[label_col_src].value_counts(normalize=True) * 100).round(2)
    print('\nLabel distribution (%):')
    print(label_percent)

# -------- Drop non-numeric string columns but keep label columns
string_columns = combined_data.select_dtypes(include=['object']).columns.tolist()
for keep in ['label2', 'label1', label_col_src]:
    if keep in string_columns:
        string_columns.remove(keep)

print(f"   - Dropping {len(string_columns)} string columns for ML processing")
combined_data_numeric = combined_data.drop(columns=string_columns)

target_col = 'label2' if 'label2' in combined_data_numeric.columns else ('label1' if 'label1' in combined_data_numeric.columns else None)
if target_col is None:
    raise ValueError('No label2/label1 column found in dataset')

X_raw = combined_data_numeric.drop(target_col, axis=1)
y_raw = combined_data_numeric[target_col]

# -------- Multiclass encoding
y_clean = y_raw.astype(str).str.strip()
classes = sorted(y_clean.unique())
class_to_id = {c: i for i, c in enumerate(classes)}
y = y_clean.map(class_to_id).astype(int)
print(f'Encoding used (multiclass): {class_to_id}')

# -------- Fill numeric NaNs with column mean
numeric_columns = X_raw.select_dtypes(include=[np.number]).columns
X_raw[numeric_columns] = X_raw[numeric_columns].fillna(X_raw[numeric_columns].mean())

# -------- Build df for cleaning
df = X_raw.copy()
df['label'] = y
label_col = 'label'
print(f'Dataset: {df.shape[0]} rows, {df.shape[1]} cols')
print('Target column:', label_col)

# -------- Robust time/order split (use Timestamp if present; else use row order)
use_time_split = ('Timestamp' in df.columns)

if use_time_split:
    df['__ts'] = pd.to_datetime(df['Timestamp'], errors='coerce')
    df = df.sort_values('__ts')
else:
    df = df.reset_index(drop=True)

# -------- Drop identifiers (keep Timestamp only for sorting; do not use it as a feature)
drop_cols = ['Protocol', 'Flow_ID', 'Src_IP', 'Dst_IP', 'Src_Port', 'Dst_Port', 'Timestamp']
df = df.drop(columns=[c for c in drop_cols if c in df.columns], errors='ignore')

# -------- Feature matrix and target
X_df = df.drop(columns=[label_col]).copy()
y = df[label_col].values

# -------- Convert to numeric + clean inf/nan
for col in X_df.columns:
    X_df[col] = pd.to_numeric(X_df[col], errors='coerce')

X_df.replace([np.inf, -np.inf], np.nan, inplace=True)

# -------- Fix special columns if present
for special in ['Flow_Duration', 'Fwd_Header_Length']:
    if special in X_df.columns:
        bad = (X_df[special] <= 0) | pd.isna(X_df[special])
        med = X_df[special][X_df[special] > 0].median()
        X_df.loc[bad, special] = med if not np.isnan(med) else 0

# -------- Drop columns with too many NaNs
missing_ratio = X_df.isna().mean()
X_df = X_df.loc[:, missing_ratio <= 0.4]

# -------- Fill remaining NaNs
X_df = X_df.apply(lambda c: c.fillna(c.median()))
X_df = X_df.fillna(0)

# -------- Remove zero-variance features
vt = VarianceThreshold(threshold=0.0)
vt.fit(X_df.values)
X_df = X_df.iloc[:, vt.get_support(indices=True)]

# -------- Final valid rows
valid = ~pd.isna(y)
X_df, y = X_df.loc[valid], y[valid]

feature_names = list(X_df.columns)

# -------- Split: train first 80%, test last 20% (robust generalisation test)
# split_point = int(len(X_df) * 0.8)
# X_train_df = X_df.iloc[:split_point].copy()
# X_test_df  = X_df.iloc[split_point:].copy()
# y_train = y[:split_point]
# y_test  = y[split_point:]

#new
from sklearn.model_selection import train_test_split

X_train_df, X_test_df, y_train, y_test = train_test_split(
    X_df,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)




X = X_train_df.values.astype(float)
y = y_train
X_test = X_test_df.values.astype(float)

print(f'After cleaning:')
print(f'   - Train: {X.shape[0]} rows, {X.shape[1]} columns')
print(f'   - Test:  {X_test.shape[0]} rows, {X_test.shape[1]} columns')
print(f'   - NaNs in X_train: {np.isnan(X).sum()}')
print(f'   - NaNs in X_test:  {np.isnan(X_test).sum()}')

print(np.bincount(y_train))
print(np.bincount(y_test))

Loading and preprocessing dataset...
Loading data...

Dataset loaded successfully!
   - Total samples: 104312
   - Features: 37

Label distribution (%):
label2
Ransomware               10.47
DDoS_HTTP                10.12
SQL_injection             9.88
Uploading                 9.84
DDoS_TCP                  9.82
Backdoor                  9.77
Vulnerability_scanner     9.66
Port_Scanning             9.65
Password                  9.58
XSS                       9.06
MITM                      1.16
Fingerprinting            0.96
Name: proportion, dtype: float64
   - Dropping 1 string columns for ML processing
Encoding used (multiclass): {'Backdoor': 0, 'DDoS_HTTP': 1, 'DDoS_TCP': 2, 'Fingerprinting': 3, 'MITM': 4, 'Password': 5, 'Port_Scanning': 6, 'Ransomware': 7, 'SQL_injection': 8, 'Uploading': 9, 'Vulnerability_scanner': 10, 'XSS': 11}
Dataset: 104312 rows, 37 cols
Target column: label

/tmp/ipykernel_121829/907619554.py:28: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  string_columns = combined_data.select_dtypes(include=['object']).columns.tolist()

After cleaning:
   - Train: 83449 rows, 24 columns
   - Test:  20863 rows, 24 columns
   - NaNs in X_train: 0
   - NaNs in X_test:  0
[8156 8449 8197  801  971 7991 8057 8740 8249 8215 8061 7562]
[2039 2112 2050  200  243 1998 2014 2185 2062 2054 2015 1891]

## Classification, Feature Count, Time, and Stability Evaluation

In [4]:
import random
import time
import tracemalloc
from itertools import combinations
from sklearn.base import clone
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, f1_score, matthews_corrcoef, precision_score, recall_score
from sklearn.model_selection import StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

N_RUNS = 10
RUN_SEEDS = list(range(N_RUNS))
K_SUP = 10
N_FEATURES_TOTAL = int(X.shape[1])

FS_MAX_SAMPLES = 50000
FS_EPOCHS = 30
FS_POP_SIZE = 10
FS_CV_FOLDS = 3

FS_FITNESS_MODEL = 'DecisionTree'
FS_FITNESS_SCORING = 'f1_macro'

EVAL_CV_FOLDS = 3

def _subsample_for_fs_local(X_in: np.ndarray, y_in: np.ndarray, max_samples: int, seed: int):
    if (max_samples is None) or (X_in.shape[0] <= int(max_samples)):
        return X_in, y_in
    rng = np.random.default_rng(int(seed))
    idx = rng.choice(X_in.shape[0], size=int(max_samples), replace=False)
    return X_in[idx], y_in[idx]

def evaluate_cv_eff(clf, X_sub: np.ndarray, y_sub: np.ndarray, cv_folds: int, seed: int):
    cvk = StratifiedKFold(n_splits=int(cv_folds), shuffle=True, random_state=int(seed))

    accs, precs, recs, f1s, mccs = [], [], [], [], []
    train_time_s = 0.0
    infer_time_ms = 0.0

    tracemalloc.start()
    for tr, te in cvk.split(X_sub, y_sub):
        model = Pipeline([
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', StandardScaler(with_mean=True)),
            ('clf', clone(clf))
        ])

        t0 = time.perf_counter()
        model.fit(X_sub[tr], y_sub[tr])
        train_time_s += (time.perf_counter() - t0)

        t1 = time.perf_counter()
        p = model.predict(X_sub[te])
        infer_time_ms += (time.perf_counter() - t1) * 1000.0

        accs.append(accuracy_score(y_sub[te], p))
        precs.append(precision_score(y_sub[te], p, average='macro', zero_division=0))
        recs.append(recall_score(y_sub[te], p, average='macro', zero_division=0))
        f1s.append(f1_score(y_sub[te], p, average='macro', zero_division=0))
        mccs.append(matthews_corrcoef(y_sub[te], p))

    current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    return {
        'accuracy': float(np.mean(accs)),
        'precision_macro': float(np.mean(precs)),
        'recall_macro': float(np.mean(recs)),
        'f1_macro': float(np.mean(f1s)),
        'mcc': float(np.mean(mccs)),
        'train_time_s': float(train_time_s),
        'inference_time_ms': float(infer_time_ms),
        'peak_mem_mb': float(peak) / (1024.0 * 1024.0)
    }

methods = ['GWO', 'BA', 'LightGBM', 'Boruta']

clf_factories = {
    'RandomForest': lambda s: RandomForestClassifier(
        n_estimators=800,
        max_depth=30,
        min_samples_split=3,
        min_samples_leaf=1,
        max_features='sqrt',
        class_weight='balanced',
        max_samples=0.8,
        n_jobs=-1,
        random_state=42
    ),
    'DecisionTree': lambda s: DecisionTreeClassifier(random_state=int(s), class_weight='balanced'),
    'LogisticRegression': lambda s: LogisticRegression(max_iter=1000, class_weight='balanced', random_state=int(s)),
    'GaussianNB': lambda s: GaussianNB(),
    'HistGradientBoosting': lambda s: HistGradientBoostingClassifier(random_state=int(s), learning_rate=0.1),
    'MLP': lambda s: MLPClassifier(
        random_state=int(s),
        hidden_layer_sizes=(128, 64),
        max_iter=200,
        early_stopping=True,
        n_iter_no_change=10,
        validation_fraction=0.1
    )
}

fs_cache = {}

def make_fs_base(seed: int):
    if str(FS_FITNESS_MODEL).lower() in ['rf', 'randomforest', 'random_forest']:
        return RandomForestClassifier(
            n_estimators=120,
            max_depth=18,
            min_samples_split=4,
            min_samples_leaf=2,
            max_features='sqrt',
            bootstrap=True,
            max_samples=0.7,
            class_weight='balanced_subsample',
            n_jobs=-1,
            random_state=int(seed)
        )
    return DecisionTreeClassifier(random_state=int(seed), class_weight='balanced')

def _serialize_idx(idx):
    return ','.join(str(int(i)) for i in idx)

def _mean_pairwise_jaccard(index_sets):
    sets = [set(int(i) for i in s) for s in index_sets if len(s) > 0]
    if len(sets) < 2:
        return np.nan, np.nan, 0
    vals = []
    for a, b in combinations(sets, 2):
        union = len(a | b)
        vals.append(len(a & b) / union if union else 1.0)
    return float(np.mean(vals)), float(np.std(vals)), int(len(vals))

def get_idx_and_time(seed: int, method: str, X_fs: np.ndarray, y_fs: np.ndarray):
    key = (int(seed), str(method))
    if key in fs_cache:
        return fs_cache[key]

    random.seed(int(seed))
    np.random.seed(int(seed))

    base = make_fs_base(int(seed))
    t0 = time.perf_counter()
    if str(method) == 'GWO':
        idx, _ = select_features_gwo(X_fs, y_fs, K_SUP, clf=base, epochs=FS_EPOCHS, pop_size=FS_POP_SIZE, cv=FS_CV_FOLDS, scoring=str(FS_FITNESS_SCORING), seed=int(seed))
    elif str(method) == 'BA':
        idx, _ = select_features_ba(X_fs, y_fs, K_SUP, clf=base, epochs=FS_EPOCHS, pop_size=FS_POP_SIZE, cv=FS_CV_FOLDS, scoring=str(FS_FITNESS_SCORING))
    elif str(method) == 'LightGBM':
        idx, _ = select_features_lightgbm(X_fs, y_fs, K_SUP, clf=base, cv=FS_CV_FOLDS, scoring=str(FS_FITNESS_SCORING), seed=int(seed))
    elif str(method) == 'Boruta':
        idx, _ = select_features_boruta(X_fs, y_fs, None, clf=base, cv=FS_CV_FOLDS, scoring=str(FS_FITNESS_SCORING), seed=int(seed))
    else:
        raise ValueError(f'Unknown method: {method}')

    fs_time_s = float(time.perf_counter() - t0)
    fs_cache[key] = (idx, fs_time_s)
    return idx, fs_time_s

rows = []
for seed in RUN_SEEDS:
    X_fs, y_fs = _subsample_for_fs_local(X, y, FS_MAX_SAMPLES, seed)
    for method in methods:
        idx, fs_time_s = get_idx_and_time(seed, method, X_fs, y_fs)
        X_sub = X[:, idx]
        for clf_name, make_clf in clf_factories.items():
            m = evaluate_cv_eff(make_clf(seed), X_sub, y, cv_folds=EVAL_CV_FOLDS, seed=seed)
            rows.append({
                'seed': int(seed),
                'method': str(method),
                'classifier': str(clf_name),
                'k_target': int(K_SUP) if method in ['GWO', 'BA', 'LightGBM'] else np.nan,
                'n_selected': int(len(idx)),
                'selected_features': _serialize_idx(idx),
                'fs_time_s': float(fs_time_s),
                **m
            })

fs_rows = []
for (s, m), (idx, fs_time_s) in fs_cache.items():
    fs_rows.append({
        'seed': int(s),
        'method': str(m),
        'k_target': int(K_SUP) if str(m) in ['GWO', 'BA', 'LightGBM'] else np.nan,
        'n_selected': int(len(idx)),
        'selected_features': _serialize_idx(idx),
        'fs_time_s': float(fs_time_s)
    })
fs_df = pd.DataFrame(fs_rows)
fs_df = fs_df.sort_values(['seed', 'method']).reset_index(drop=True)
display(fs_df)
display(fs_df.groupby('method', as_index=False)[['fs_time_s', 'n_selected']].agg(['mean', 'std']).reset_index())

stability_rows = []
for method_name, sub_df in fs_df.groupby('method'):
    sets = []
    for txt in sub_df['selected_features'].astype(str):
        sets.append([int(x) for x in txt.split(',') if str(x).strip() != ''])
    mean_j, std_j, n_pairs = _mean_pairwise_jaccard(sets)
    stability_rows.append({
        'method': str(method_name),
        'mean_pairwise_jaccard': mean_j,
        'std_pairwise_jaccard': std_j,
        'n_pairs': n_pairs
    })
stability_df = pd.DataFrame(stability_rows).sort_values('mean_pairwise_jaccard', ascending=False).reset_index(drop=True)
print('Feature-selection stability across runs')
display(stability_df)

raw_df = pd.DataFrame(rows)
display(raw_df)
print('Rows:', len(raw_df))

metrics_cols = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro', 'mcc', 'fs_time_s', 'train_time_s', 'inference_time_ms', 'peak_mem_mb', 'n_selected']

means = raw_df.groupby(['method', 'classifier'])[metrics_cols].mean().reset_index()
means = means.rename(columns={
    'method': 'Algorithm',
    'classifier': 'Classifier',
    'accuracy': 'Accuracy',
    'precision_macro': 'Precision',
    'recall_macro': 'Recall',
    'f1_macro': 'F1_macro',
    'mcc': 'MCC',
    'n_selected': 'N_Selected'
})

eval_df = means[['Algorithm', 'Classifier', 'Accuracy', 'Precision', 'Recall', 'F1_macro', 'MCC', 'N_Selected', 'fs_time_s', 'train_time_s', 'inference_time_ms', 'peak_mem_mb']].copy()
eval_df = eval_df.sort_values(['F1_macro', 'MCC', 'Accuracy'], ascending=[False, False, False]).reset_index(drop=True)
display(eval_df)

print('Deployment-oriented summary (lower downstream cost is better)')
deployment_df = eval_df[['Algorithm', 'Classifier', 'N_Selected', 'train_time_s', 'inference_time_ms', 'peak_mem_mb']].copy()
deployment_df = deployment_df.sort_values(['N_Selected', 'peak_mem_mb', 'inference_time_ms', 'train_time_s'], ascending=[True, True, True, True]).reset_index(drop=True)
display(deployment_df)

agg = raw_df.groupby(['method', 'classifier'])[metrics_cols].agg(['mean', 'std'])
agg.columns = [f"{m}_{s}" for (m, s) in agg.columns]
agg = agg.reset_index()

def fmt_pair(m, s, is_time=False):
    if pd.isna(m):
        return ''
    if pd.isna(s):
        return f"{m:.4f}" if not is_time else f"{m:.3f}"
    return (f"{m:.4f} +- {s:.4f}" if not is_time else f"{m:.3f} +- {s:.3f}")

final_table = pd.DataFrame({
    'Method': agg['method'].astype(str),
    'Classifier': agg['classifier'].astype(str),
})

for src, dst in {
    'accuracy': 'accuracy',
    'precision_macro': 'precision_macro',
    'recall_macro': 'recall_macro',
    'f1_macro': 'f1_macro',
    'mcc': 'mcc',
    'n_selected': 'n_selected',
    'fs_time_s': 'fs_time_s',
    'train_time_s': 'train_time_s',
    'inference_time_ms': 'inference_time_ms',
    'peak_mem_mb': 'peak_mem_mb'
}.items():
    mcol = f"{src}_mean"
    scol = f"{src}_std"
    is_time = src in ['fs_time_s', 'train_time_s', 'inference_time_ms', 'peak_mem_mb']
    final_table[dst] = [fmt_pair(m, s, is_time=is_time) for m, s in zip(agg[mcol], agg[scol])]

final_table = final_table.sort_values(['Classifier', 'Method']).reset_index(drop=True)
display(final_table)

2026/06/14 01:47:16 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/14 01:47:26 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8147768967203118, Global best: 0.8147768967203118, Runtime: 5.65913 seconds

2026/06/14 01:47:31 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8165297724646787, Global best: 0.8165297724646787, Runtime: 5.02645 seconds

2026/06/14 01:47:37 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8280529794639805, Global best: 0.8280529794639805, Runtime: 5.74369 seconds

2026/06/14 01:47:43 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8343491493558525, Global best: 0.8343491493558525, Runtime: 5.83063 seconds

2026/06/14 01:47:50 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8343491493558525, Global best: 0.8343491493558525, Runtime: 6.99719 seconds

2026/06/14 01:47:55 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8343491493558525, Global best: 0.8343491493558525, Runtime: 5.66542 seconds

2026/06/14 01:48:03 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8343491493558525, Global best: 0.8343491493558525, Runtime: 7.59333 seconds

2026/06/14 01:48:09 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8372628007289326, Global best: 0.8372628007289326, Runtime: 6.25184 seconds

2026/06/14 01:48:16 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8446709817518733, Global best: 0.8446709817518733, Runtime: 6.25182 seconds

2026/06/14 01:48:22 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8459512029573267, Global best: 0.8459512029573267, Runtime: 6.24844 seconds

2026/06/14 01:48:28 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8465559805351319, Global best: 0.8465559805351319, Runtime: 5.95107 seconds

2026/06/14 01:48:34 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8480102083465378, Global best: 0.8480102083465378, Runtime: 5.79034 seconds

2026/06/14 01:48:39 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8484063336097304, Global best: 0.8484063336097304, Runtime: 5.47803 seconds

2026/06/14 01:48:44 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8494274570377601, Global best: 0.8494274570377601, Runtime: 5.15676 seconds

2026/06/14 01:48:51 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8500085353758464, Global best: 0.8500085353758464, Runtime: 6.80116 seconds

2026/06/14 01:48:57 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8508649570377601, Global best: 0.8508649570377601, Runtime: 5.59161 seconds

2026/06/14 01:49:03 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8515495931864013, Global best: 0.8515495931864013, Runtime: 6.36773 seconds

2026/06/14 01:49:09 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8520458012227892, Global best: 0.8520458012227892, Runtime: 5.89177 seconds

2026/06/14 01:49:15 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8527399570377601, Global best: 0.8527399570377601, Runtime: 5.90545 seconds

2026/06/14 01:49:20 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8534716956259263, Global best: 0.8534716956259263, Runtime: 5.66485 seconds

2026/06/14 01:49:26 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8540044246508188, Global best: 0.8540044246508188, Runtime: 5.68155 seconds

2026/06/14 01:49:31 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8546919246508188, Global best: 0.8546919246508188, Runtime: 4.84731 seconds

2026/06/14 01:49:36 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8552544246508188, Global best: 0.8552544246508188, Runtime: 4.99267 seconds

2026/06/14 01:49:41 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8559419246508188, Global best: 0.8559419246508188, Runtime: 5.23893 seconds

2026/06/14 01:49:46 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8565669246508187, Global best: 0.8565669246508187, Runtime: 4.90093 seconds

2026/06/14 01:49:52 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.85717745703776, Global best: 0.85717745703776, Runtime: 5.97146 seconds

2026/06/14 01:49:57 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8578649570377601, Global best: 0.8578649570377601, Runtime: 4.94767 seconds

2026/06/14 01:50:02 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8584274570377601, Global best: 0.8584274570377601, Runtime: 4.81711 seconds

2026/06/14 01:50:07 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8591149570377601, Global best: 0.8591149570377601, Runtime: 5.05077 seconds

2026/06/14 01:50:12 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8591149570377601, Global best: 0.8591149570377601, Runtime: 5.07302 seconds

2026/06/14 02:01:29 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/14 02:01:39 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.7473369552341603, Global best: 0.7473369552341603, Runtime: 5.37682 seconds

2026/06/14 02:01:44 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.13938 seconds

2026/06/14 02:01:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 4.79893 seconds

2026/06/14 02:01:54 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.20399 seconds

2026/06/14 02:01:59 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.00792 seconds

2026/06/14 02:02:05 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.63233 seconds

2026/06/14 02:02:10 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.02287 seconds

2026/06/14 02:02:15 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 4.90168 seconds

2026/06/14 02:02:20 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.15502 seconds

2026/06/14 02:02:27 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 6.62625 seconds

2026/06/14 02:02:32 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 4.85224 seconds

2026/06/14 02:02:37 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.18842 seconds

2026/06/14 02:02:42 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.03190 seconds

2026/06/14 02:02:47 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.19441 seconds

2026/06/14 02:02:52 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.38715 seconds

2026/06/14 02:02:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.43453 seconds

2026/06/14 02:03:03 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.59003 seconds

2026/06/14 02:03:09 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.87599 seconds

2026/06/14 02:03:15 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.40318 seconds

2026/06/14 02:03:21 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.84880 seconds

2026/06/14 02:03:26 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.48326 seconds

2026/06/14 02:03:32 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.62861 seconds

2026/06/14 02:03:37 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.50766 seconds

2026/06/14 02:03:43 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.80558 seconds

2026/06/14 02:03:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.73146 seconds

2026/06/14 02:03:54 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.66013 seconds

2026/06/14 02:04:00 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.56126 seconds

2026/06/14 02:04:06 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.79995 seconds

2026/06/14 02:04:12 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.76665 seconds

2026/06/14 02:04:17 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8071018415496354, Global best: 0.8071018415496354, Runtime: 5.68563 seconds

2026/06/14 02:34:26 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/14 02:34:37 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8509734972133173, Global best: 0.8509734972133173, Runtime: 5.81919 seconds

2026/06/14 02:34:42 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8509734972133173, Global best: 0.8509734972133173, Runtime: 5.31655 seconds

2026/06/14 02:34:48 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8509734972133173, Global best: 0.8509734972133173, Runtime: 5.29585 seconds

2026/06/14 02:34:52 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8509734972133173, Global best: 0.8509734972133173, Runtime: 4.41113 seconds

2026/06/14 02:34:57 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.852632718728517, Global best: 0.852632718728517, Runtime: 4.86190 seconds

2026/06/14 02:35:01 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8538483976045801, Global best: 0.8538483976045801, Runtime: 4.26943 seconds

2026/06/14 02:35:06 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8545384143686667, Global best: 0.8545384143686667, Runtime: 5.15290 seconds

2026/06/14 02:35:12 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8545384143686667, Global best: 0.8545384143686667, Runtime: 5.60463 seconds

2026/06/14 02:35:17 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.85485995070982, Global best: 0.85485995070982, Runtime: 5.10990 seconds

2026/06/14 02:35:23 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8555946232101502, Global best: 0.8555946232101502, Runtime: 5.68277 seconds

2026/06/14 02:35:27 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8593693254482984, Global best: 0.8593693254482984, Runtime: 4.80156 seconds

2026/06/14 02:35:32 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8601918330995924, Global best: 0.8601918330995924, Runtime: 4.74013 seconds

2026/06/14 02:35:37 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8604425854791015, Global best: 0.8604425854791015, Runtime: 4.95321 seconds

2026/06/14 02:35:41 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8612443254482983, Global best: 0.8612443254482983, Runtime: 4.32690 seconds

2026/06/14 02:35:45 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.861978378326471, Global best: 0.861978378326471, Runtime: 3.92881 seconds

2026/06/14 02:35:49 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8628114737294712, Global best: 0.8628114737294712, Runtime: 3.71024 seconds

2026/06/14 02:35:53 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8633800854791014, Global best: 0.8633800854791014, Runtime: 3.93059 seconds

2026/06/14 02:35:57 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8641998019758166, Global best: 0.8641998019758166, Runtime: 3.83377 seconds

2026/06/14 02:36:01 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8646373019758166, Global best: 0.8646373019758166, Runtime: 3.69039 seconds

2026/06/14 02:36:05 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.865403249097644, Global best: 0.865403249097644, Runtime: 4.37035 seconds

2026/06/14 02:36:09 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.865965749097644, Global best: 0.865965749097644, Runtime: 3.84734 seconds

2026/06/14 02:36:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8666998019758165, Global best: 0.8666998019758165, Runtime: 3.86832 seconds

2026/06/14 02:36:17 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8671632567489381, Global best: 0.8671632567489381, Runtime: 4.14153 seconds

2026/06/14 02:36:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8679158783264709, Global best: 0.8679158783264709, Runtime: 4.12746 seconds

2026/06/14 02:36:25 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8685618713015824, Global best: 0.8685618713015824, Runtime: 3.91501 seconds

2026/06/14 02:36:29 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8691998019758166, Global best: 0.8691998019758166, Runtime: 3.86458 seconds

2026/06/14 02:36:33 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8697623019758165, Global best: 0.8697623019758165, Runtime: 3.90796 seconds

2026/06/14 02:36:36 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8702257567489382, Global best: 0.8702257567489382, Runtime: 3.66990 seconds

2026/06/14 02:36:40 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8709498019758165, Global best: 0.8709498019758165, Runtime: 4.04976 seconds

2026/06/14 02:36:44 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8710614737294712, Global best: 0.8710614737294712, Runtime: 3.80698 seconds

2026/06/14 02:45:47 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/14 02:45:59 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.7394904524261916, Global best: 0.7394904524261916, Runtime: 5.55377 seconds

2026/06/14 02:46:06 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.71815 seconds

2026/06/14 02:46:12 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.59174 seconds

2026/06/14 02:46:19 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.24144 seconds

2026/06/14 02:46:25 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.55639 seconds

2026/06/14 02:46:32 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.41470 seconds

2026/06/14 02:46:38 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.21972 seconds

2026/06/14 02:46:44 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.34587 seconds

2026/06/14 02:46:51 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.83489 seconds

2026/06/14 02:46:57 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.38657 seconds

2026/06/14 02:47:04 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.62866 seconds

2026/06/14 02:47:11 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 7.15133 seconds

2026/06/14 02:47:18 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.54200 seconds

2026/06/14 02:47:24 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.53351 seconds

2026/06/14 02:47:32 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 7.22966 seconds

2026/06/14 02:47:38 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.24505 seconds

2026/06/14 02:47:44 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.16087 seconds

2026/06/14 02:47:50 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.35039 seconds

2026/06/14 02:47:56 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.06003 seconds

2026/06/14 02:48:03 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.67468 seconds

2026/06/14 02:48:10 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.62574 seconds

2026/06/14 02:48:16 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.46113 seconds

2026/06/14 02:48:23 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.98872 seconds

2026/06/14 02:48:30 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.70342 seconds

2026/06/14 02:48:36 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.40024 seconds

2026/06/14 02:48:43 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.61390 seconds

2026/06/14 02:48:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.43428 seconds

2026/06/14 02:48:56 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.82473 seconds

2026/06/14 02:49:02 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.07155 seconds

2026/06/14 02:49:09 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.7785445462696942, Global best: 0.7785445462696942, Runtime: 6.41979 seconds

2026/06/14 03:19:48 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/14 03:19:58 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8121810304487624, Global best: 0.8121810304487624, Runtime: 5.29768 seconds

2026/06/14 03:20:04 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8205219325013673, Global best: 0.8205219325013673, Runtime: 5.56026 seconds

2026/06/14 03:20:09 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8205219325013673, Global best: 0.8205219325013673, Runtime: 4.71703 seconds

2026/06/14 03:20:12 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8217001478561918, Global best: 0.8217001478561918, Runtime: 3.69007 seconds

2026/06/14 03:20:16 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8217001478561918, Global best: 0.8217001478561918, Runtime: 3.98047 seconds

2026/06/14 03:20:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8235967255262515, Global best: 0.8235967255262515, Runtime: 4.74076 seconds

2026/06/14 03:20:25 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8235967255262515, Global best: 0.8235967255262515, Runtime: 4.44555 seconds

2026/06/14 03:20:29 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8250666983964842, Global best: 0.8250666983964842, Runtime: 3.99641 seconds

2026/06/14 03:20:33 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8257371455284639, Global best: 0.8257371455284639, Runtime: 3.94973 seconds

2026/06/14 03:20:37 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8263564523874152, Global best: 0.8263564523874152, Runtime: 4.08740 seconds

2026/06/14 03:20:41 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8347096421504991, Global best: 0.8347096421504991, Runtime: 3.97490 seconds

2026/06/14 03:20:45 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8347393660964039, Global best: 0.8347393660964039, Runtime: 3.89782 seconds

2026/06/14 03:20:49 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8360254005776356, Global best: 0.8360254005776356, Runtime: 3.93580 seconds

2026/06/14 03:20:54 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8362117622767562, Global best: 0.8362117622767562, Runtime: 5.20736 seconds

2026/06/14 03:20:58 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8373322527574576, Global best: 0.8373322527574576, Runtime: 3.97101 seconds

2026/06/14 03:21:02 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8379934979202882, Global best: 0.8379934979202882, Runtime: 3.87018 seconds

2026/06/14 03:21:06 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8387321166282611, Global best: 0.8387321166282611, Runtime: 3.86030 seconds

2026/06/14 03:21:10 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8391696166282612, Global best: 0.8391696166282612, Runtime: 4.26216 seconds

2026/06/14 03:21:14 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.83993740720479, Global best: 0.83993740720479, Runtime: 3.95475 seconds

2026/06/14 03:21:18 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8404579885599459, Global best: 0.8404579885599459, Runtime: 4.00627 seconds

2026/06/14 03:21:22 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8411992241609095, Global best: 0.8411992241609095, Runtime: 3.89422 seconds

2026/06/14 03:21:26 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8418124072047901, Global best: 0.8418124072047901, Runtime: 4.06125 seconds

2026/06/14 03:21:30 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8424828259231827, Global best: 0.8424828259231827, Runtime: 3.98959 seconds

2026/06/14 03:21:34 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8430051126488146, Global best: 0.8430051126488146, Runtime: 3.74185 seconds

2026/06/14 03:21:38 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8436999599633977, Global best: 0.8436999599633977, Runtime: 4.20985 seconds

2026/06/14 03:21:42 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.844240854519731, Global best: 0.844240854519731, Runtime: 3.73940 seconds

2026/06/14 03:21:46 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8448090010134162, Global best: 0.8448090010134162, Runtime: 4.35178 seconds

2026/06/14 03:21:50 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8454999072047901, Global best: 0.8454999072047901, Runtime: 3.93801 seconds

2026/06/14 03:21:55 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8460590010134161, Global best: 0.8460590010134161, Runtime: 4.19881 seconds

2026/06/14 03:21:58 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8460590010134161, Global best: 0.8460590010134161, Runtime: 3.52227 seconds

2026/06/14 03:32:15 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/14 03:32:25 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.7626753361002926, Global best: 0.7626753361002926, Runtime: 5.23717 seconds

2026/06/14 03:32:30 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.7642378361002925, Global best: 0.7642378361002925, Runtime: 5.41523 seconds

2026/06/14 03:32:36 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.7649878361002925, Global best: 0.7649878361002925, Runtime: 5.94887 seconds

2026/06/14 03:32:43 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.7649878361002925, Global best: 0.7649878361002925, Runtime: 6.60071 seconds

2026/06/14 03:32:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.7649878361002925, Global best: 0.7649878361002925, Runtime: 6.46225 seconds

2026/06/14 03:32:55 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.7649878361002925, Global best: 0.7649878361002925, Runtime: 6.13005 seconds

2026/06/14 03:33:01 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.7674878361002926, Global best: 0.7674878361002926, Runtime: 6.18121 seconds

2026/06/14 03:33:07 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.7674878361002926, Global best: 0.7674878361002926, Runtime: 5.86231 seconds

2026/06/14 03:33:13 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.7683628361002925, Global best: 0.7683628361002925, Runtime: 5.82057 seconds

2026/06/14 03:33:20 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.7694873141033388, Global best: 0.7694873141033388, Runtime: 7.03796 seconds

2026/06/14 03:33:27 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.7699248141033389, Global best: 0.7699248141033389, Runtime: 6.50002 seconds

2026/06/14 03:33:33 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.7699248141033389, Global best: 0.7699248141033389, Runtime: 6.34847 seconds

2026/06/14 03:33:40 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.7699248141033389, Global best: 0.7699248141033389, Runtime: 6.66300 seconds

2026/06/14 03:33:46 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.7699248141033389, Global best: 0.7699248141033389, Runtime: 6.68848 seconds

2026/06/14 03:33:53 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.7721292070632366, Global best: 0.7721292070632366, Runtime: 6.87632 seconds

2026/06/14 03:34:00 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.7731917070632366, Global best: 0.7731917070632366, Runtime: 6.49507 seconds

2026/06/14 03:34:06 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.7731917070632366, Global best: 0.7731917070632366, Runtime: 6.48413 seconds

2026/06/14 03:34:13 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.7739975567069193, Global best: 0.7739975567069193, Runtime: 6.65940 seconds

2026/06/14 03:34:20 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.7746156802117923, Global best: 0.7746156802117923, Runtime: 6.97203 seconds

2026/06/14 03:34:27 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.7746156802117923, Global best: 0.7746156802117923, Runtime: 7.72660 seconds

2026/06/14 03:34:34 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.7746156802117923, Global best: 0.7746156802117923, Runtime: 6.94767 seconds

2026/06/14 03:34:41 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.7769878361002925, Global best: 0.7769878361002925, Runtime: 6.56210 seconds

2026/06/14 03:34:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.7769878361002925, Global best: 0.7769878361002925, Runtime: 7.53019 seconds

2026/06/14 03:34:56 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.7769878361002925, Global best: 0.7769878361002925, Runtime: 7.92850 seconds

2026/06/14 03:35:03 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.7769878361002925, Global best: 0.7769878361002925, Runtime: 7.01447 seconds

2026/06/14 03:35:10 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.7769878361002925, Global best: 0.7769878361002925, Runtime: 6.77316 seconds

2026/06/14 03:35:17 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.7799719892324456, Global best: 0.7799719892324456, Runtime: 6.84993 seconds

2026/06/14 03:35:24 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.7804719892324457, Global best: 0.7804719892324457, Runtime: 7.16615 seconds

2026/06/14 03:35:31 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.7929399315559262, Global best: 0.7929399315559262, Runtime: 6.73175 seconds

2026/06/14 03:35:38 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.7935024315559263, Global best: 0.7935024315559263, Runtime: 6.76624 seconds

2026/06/14 04:04:28 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/14 04:04:40 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8207797493169575, Global best: 0.8207797493169575, Runtime: 5.37783 seconds

2026/06/14 04:04:45 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8207797493169575, Global best: 0.8207797493169575, Runtime: 4.99640 seconds

2026/06/14 04:04:50 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8207797493169575, Global best: 0.8207797493169575, Runtime: 4.79468 seconds

2026/06/14 04:04:54 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8330475615975477, Global best: 0.8330475615975477, Runtime: 4.56105 seconds

2026/06/14 04:04:59 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8330475615975477, Global best: 0.8330475615975477, Runtime: 4.97740 seconds

2026/06/14 04:05:04 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.840099261430473, Global best: 0.840099261430473, Runtime: 5.21941 seconds

2026/06/14 04:05:10 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8404711222242948, Global best: 0.8404711222242948, Runtime: 5.05002 seconds

2026/06/14 04:05:15 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.842327782650658, Global best: 0.842327782650658, Runtime: 5.58537 seconds

2026/06/14 04:05:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8450080590778912, Global best: 0.8450080590778912, Runtime: 5.68300 seconds

2026/06/14 04:05:26 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8450080590778912, Global best: 0.8450080590778912, Runtime: 5.42799 seconds

2026/06/14 04:05:30 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8455485335107604, Global best: 0.8455485335107604, Runtime: 4.01020 seconds

2026/06/14 04:05:35 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8466839111806594, Global best: 0.8466839111806594, Runtime: 4.51548 seconds

2026/06/14 04:05:40 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8466839111806594, Global best: 0.8466839111806594, Runtime: 4.93760 seconds

2026/06/14 04:05:44 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8479240330141354, Global best: 0.8479240330141354, Runtime: 4.35094 seconds

2026/06/14 04:05:48 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8484903968970566, Global best: 0.8484903968970566, Runtime: 4.14563 seconds

2026/06/14 04:05:52 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8493187151571207, Global best: 0.8493187151571207, Runtime: 4.27051 seconds

2026/06/14 04:05:57 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8498402953396336, Global best: 0.8498402953396336, Runtime: 4.14909 seconds

2026/06/14 04:06:01 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8505494072613932, Global best: 0.8505494072613932, Runtime: 3.87982 seconds

2026/06/14 04:06:05 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8512913193911916, Global best: 0.8512913193911916, Runtime: 4.50361 seconds

2026/06/14 04:06:09 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8519255686693248, Global best: 0.8519255686693248, Runtime: 3.79985 seconds

2026/06/14 04:06:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8525914312448669, Global best: 0.8525914312448669, Runtime: 3.77415 seconds

2026/06/14 04:06:16 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8531890069298097, Global best: 0.8531890069298097, Runtime: 3.78164 seconds

2026/06/14 04:06:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8538346353022885, Global best: 0.8538346353022885, Runtime: 4.23127 seconds

2026/06/14 04:06:25 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8543569473390015, Global best: 0.8543569473390015, Runtime: 3.90644 seconds

2026/06/14 04:06:29 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8550424146184443, Global best: 0.8550424146184443, Runtime: 4.20169 seconds

2026/06/14 04:06:33 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8556812501009893, Global best: 0.8556812501009893, Runtime: 3.96858 seconds

2026/06/14 04:06:37 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8563352494263043, Global best: 0.8563352494263043, Runtime: 3.90083 seconds

2026/06/14 04:06:41 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8569617452120822, Global best: 0.8569617452120822, Runtime: 4.23121 seconds

2026/06/14 04:06:45 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8575562501009892, Global best: 0.8575562501009892, Runtime: 3.67628 seconds

2026/06/14 04:06:48 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8575562501009892, Global best: 0.8575562501009892, Runtime: 3.87394 seconds

2026/06/14 04:16:26 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/14 04:16:39 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8258938861016003, Global best: 0.8258938861016003, Runtime: 6.83094 seconds

2026/06/14 04:16:45 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8258938861016003, Global best: 0.8258938861016003, Runtime: 5.85855 seconds

2026/06/14 04:16:51 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8258938861016003, Global best: 0.8258938861016003, Runtime: 5.84265 seconds

2026/06/14 04:16:57 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8258938861016003, Global best: 0.8258938861016003, Runtime: 5.83270 seconds

2026/06/14 04:17:03 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8258938861016003, Global best: 0.8258938861016003, Runtime: 6.33467 seconds

2026/06/14 04:17:11 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8258938861016003, Global best: 0.8258938861016003, Runtime: 8.33060 seconds

2026/06/14 04:17:19 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8307688861016003, Global best: 0.8307688861016003, Runtime: 7.15929 seconds

2026/06/14 04:17:25 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8307688861016003, Global best: 0.8307688861016003, Runtime: 6.33558 seconds

2026/06/14 04:17:31 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8315813861016003, Global best: 0.8315813861016003, Runtime: 6.10264 seconds

2026/06/14 04:17:37 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8315813861016003, Global best: 0.8315813861016003, Runtime: 5.82205 seconds

2026/06/14 04:17:43 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8328938861016003, Global best: 0.8328938861016003, Runtime: 5.84145 seconds

2026/06/14 04:17:48 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8328938861016003, Global best: 0.8328938861016003, Runtime: 5.58662 seconds

2026/06/14 04:17:53 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8339563861016003, Global best: 0.8339563861016003, Runtime: 4.94870 seconds

2026/06/14 04:17:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8348313861016003, Global best: 0.8348313861016003, Runtime: 4.82952 seconds

2026/06/14 04:18:03 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8352063861016003, Global best: 0.8352063861016003, Runtime: 5.25218 seconds

2026/06/14 04:18:08 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8352063861016003, Global best: 0.8352063861016003, Runtime: 4.87633 seconds

2026/06/14 04:18:13 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8352063861016003, Global best: 0.8352063861016003, Runtime: 4.94303 seconds

2026/06/14 04:18:18 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8352063861016003, Global best: 0.8352063861016003, Runtime: 4.72320 seconds

2026/06/14 04:18:23 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8352063861016003, Global best: 0.8352063861016003, Runtime: 4.81755 seconds

2026/06/14 04:18:27 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8352063861016003, Global best: 0.8352063861016003, Runtime: 4.63524 seconds

2026/06/14 04:18:32 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8390813861016003, Global best: 0.8390813861016003, Runtime: 5.04817 seconds

2026/06/14 04:18:37 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8390813861016003, Global best: 0.8390813861016003, Runtime: 5.05980 seconds

2026/06/14 04:18:43 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8390813861016003, Global best: 0.8390813861016003, Runtime: 5.45149 seconds

2026/06/14 04:18:48 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8390813861016003, Global best: 0.8390813861016003, Runtime: 4.73930 seconds

2026/06/14 04:18:53 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8390813861016003, Global best: 0.8390813861016003, Runtime: 5.03456 seconds

2026/06/14 04:18:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8390813861016003, Global best: 0.8390813861016003, Runtime: 5.19229 seconds

2026/06/14 04:19:03 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8428313861016004, Global best: 0.8428313861016004, Runtime: 4.88894 seconds

2026/06/14 04:19:08 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8428313861016004, Global best: 0.8428313861016004, Runtime: 4.86943 seconds

2026/06/14 04:19:13 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8428313861016004, Global best: 0.8428313861016004, Runtime: 5.17705 seconds

2026/06/14 04:19:18 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8446205850217061, Global best: 0.8446205850217061, Runtime: 4.87781 seconds

2026/06/14 04:47:18 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/14 04:47:29 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.7950101754628962, Global best: 0.7950101754628962, Runtime: 5.62352 seconds

2026/06/14 04:47:35 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8355697151623245, Global best: 0.8355697151623245, Runtime: 5.25325 seconds

2026/06/14 04:47:40 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8355697151623245, Global best: 0.8355697151623245, Runtime: 5.45889 seconds

2026/06/14 04:47:46 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8355697151623245, Global best: 0.8355697151623245, Runtime: 5.83570 seconds

2026/06/14 04:47:50 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8428621218324239, Global best: 0.8428621218324239, Runtime: 4.28683 seconds

2026/06/14 04:47:55 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8429728223205348, Global best: 0.8429728223205348, Runtime: 4.30470 seconds

2026/06/14 04:47:59 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8441750586726954, Global best: 0.8441750586726954, Runtime: 4.31733 seconds

2026/06/14 04:48:03 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8450055106951311, Global best: 0.8450055106951311, Runtime: 4.50499 seconds

2026/06/14 04:48:08 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8450055106951311, Global best: 0.8450055106951311, Runtime: 4.49316 seconds

2026/06/14 04:48:12 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8479213802441996, Global best: 0.8479213802441996, Runtime: 4.31419 seconds

2026/06/14 04:48:17 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8479213802441996, Global best: 0.8479213802441996, Runtime: 4.42165 seconds

2026/06/14 04:48:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8490861503163643, Global best: 0.8490861503163643, Runtime: 4.46279 seconds

2026/06/14 04:48:26 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8490861503163643, Global best: 0.8490861503163643, Runtime: 4.61039 seconds

2026/06/14 04:48:30 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8504040907295518, Global best: 0.8504040907295518, Runtime: 4.52533 seconds

2026/06/14 04:48:35 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8511428312287024, Global best: 0.8511428312287024, Runtime: 5.01234 seconds

2026/06/14 04:48:40 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.851545212486779, Global best: 0.851545212486779, Runtime: 4.59816 seconds

2026/06/14 04:48:45 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8524052400246943, Global best: 0.8524052400246943, Runtime: 4.97826 seconds

2026/06/14 04:48:49 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8531805475816443, Global best: 0.8531805475816443, Runtime: 4.64600 seconds

2026/06/14 04:48:54 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8538669314634878, Global best: 0.8538669314634878, Runtime: 4.62251 seconds

2026/06/14 04:48:59 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.854413235193269, Global best: 0.854413235193269, Runtime: 5.07695 seconds

2026/06/14 04:49:05 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8548991636461585, Global best: 0.8548991636461585, Runtime: 5.61899 seconds

2026/06/14 04:49:10 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8556490549108926, Global best: 0.8556490549108926, Runtime: 5.66587 seconds

2026/06/14 04:49:16 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8560283008780017, Global best: 0.8560283008780017, Runtime: 5.19062 seconds

2026/06/14 04:49:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8567692010741506, Global best: 0.8567692010741506, Runtime: 5.10362 seconds

2026/06/14 04:49:26 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8573270693226275, Global best: 0.8573270693226275, Runtime: 5.44031 seconds

2026/06/14 04:49:31 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8580408154420108, Global best: 0.8580408154420108, Runtime: 5.17633 seconds

2026/06/14 04:49:36 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8585032601015382, Global best: 0.8585032601015382, Runtime: 5.07213 seconds

2026/06/14 04:49:42 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8592532601015382, Global best: 0.8592532601015382, Runtime: 5.25147 seconds

2026/06/14 04:49:48 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8598782601015382, Global best: 0.8598782601015382, Runtime: 5.84042 seconds

2026/06/14 04:49:53 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8598782601015382, Global best: 0.8598782601015382, Runtime: 5.16371 seconds

2026/06/14 04:56:55 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/14 04:57:06 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.7981595310775647, Global best: 0.7981595310775647, Runtime: 6.34271 seconds

2026/06/14 04:57:13 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.7986595310775646, Global best: 0.7986595310775646, Runtime: 6.34504 seconds

2026/06/14 04:57:19 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.7986595310775646, Global best: 0.7986595310775646, Runtime: 6.43018 seconds

2026/06/14 04:57:25 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.7986595310775646, Global best: 0.7986595310775646, Runtime: 6.25073 seconds

2026/06/14 04:57:32 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.7986595310775646, Global best: 0.7986595310775646, Runtime: 6.28031 seconds

2026/06/14 04:57:39 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.7986595310775646, Global best: 0.7986595310775646, Runtime: 6.74550 seconds

2026/06/14 04:57:45 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.7986595310775646, Global best: 0.7986595310775646, Runtime: 6.18236 seconds

2026/06/14 04:57:51 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.7986595310775646, Global best: 0.7986595310775646, Runtime: 6.45280 seconds

2026/06/14 04:57:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8033470310775647, Global best: 0.8033470310775647, Runtime: 6.36518 seconds

2026/06/14 04:58:04 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8038470310775646, Global best: 0.8038470310775646, Runtime: 6.41909 seconds

2026/06/14 04:58:10 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8038470310775646, Global best: 0.8038470310775646, Runtime: 6.39576 seconds

2026/06/14 04:58:17 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8050345310775646, Global best: 0.8050345310775646, Runtime: 6.54261 seconds

2026/06/14 04:58:23 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8050345310775646, Global best: 0.8050345310775646, Runtime: 6.40585 seconds

2026/06/14 04:58:30 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8050345310775646, Global best: 0.8050345310775646, Runtime: 6.36612 seconds

2026/06/14 04:58:36 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8050345310775646, Global best: 0.8050345310775646, Runtime: 6.56012 seconds

2026/06/14 04:58:43 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8050345310775646, Global best: 0.8050345310775646, Runtime: 6.83480 seconds

2026/06/14 04:58:50 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8050345310775646, Global best: 0.8050345310775646, Runtime: 6.48640 seconds

2026/06/14 04:58:56 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8050345310775646, Global best: 0.8050345310775646, Runtime: 6.71057 seconds

2026/06/14 04:59:03 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8093470310775646, Global best: 0.8093470310775646, Runtime: 6.72988 seconds

2026/06/14 04:59:10 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8093470310775646, Global best: 0.8093470310775646, Runtime: 7.02046 seconds

2026/06/14 04:59:17 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8093470310775646, Global best: 0.8093470310775646, Runtime: 6.60055 seconds

2026/06/14 04:59:23 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8093470310775646, Global best: 0.8093470310775646, Runtime: 6.48603 seconds

2026/06/14 04:59:30 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8093470310775646, Global best: 0.8093470310775646, Runtime: 6.70657 seconds

2026/06/14 04:59:36 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8093470310775646, Global best: 0.8093470310775646, Runtime: 6.57564 seconds

2026/06/14 04:59:43 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8093470310775646, Global best: 0.8093470310775646, Runtime: 6.96565 seconds

2026/06/14 04:59:51 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8093470310775646, Global best: 0.8093470310775646, Runtime: 7.23220 seconds

2026/06/14 04:59:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8093470310775646, Global best: 0.8093470310775646, Runtime: 6.95160 seconds

2026/06/14 05:00:06 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8093470310775646, Global best: 0.8093470310775646, Runtime: 7.99046 seconds

2026/06/14 05:00:13 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8093470310775646, Global best: 0.8093470310775646, Runtime: 7.26466 seconds

2026/06/14 05:00:19 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8093470310775646, Global best: 0.8093470310775646, Runtime: 6.58054 seconds

2026/06/14 05:30:37 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/14 05:30:47 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8010011970781054, Global best: 0.8010011970781054, Runtime: 5.05273 seconds

2026/06/14 05:30:53 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8136776797719331, Global best: 0.8136776797719331, Runtime: 5.80586 seconds

2026/06/14 05:30:58 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8337721519021258, Global best: 0.8337721519021258, Runtime: 4.60837 seconds

2026/06/14 05:31:02 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8401160165078261, Global best: 0.8401160165078261, Runtime: 4.26651 seconds

2026/06/14 05:31:07 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8401160165078261, Global best: 0.8401160165078261, Runtime: 5.40319 seconds

2026/06/14 05:31:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8445048550863575, Global best: 0.8445048550863575, Runtime: 5.72461 seconds

2026/06/14 05:31:17 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8446882075321813, Global best: 0.8446882075321813, Runtime: 4.03457 seconds

2026/06/14 05:31:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8455396584186314, Global best: 0.8455396584186314, Runtime: 4.21180 seconds

2026/06/14 05:31:27 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.845928043487781, Global best: 0.845928043487781, Runtime: 5.22263 seconds

2026/06/14 05:31:31 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.847110368579834, Global best: 0.847110368579834, Runtime: 4.24390 seconds

2026/06/14 05:31:35 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8477193058126052, Global best: 0.8477193058126052, Runtime: 4.54543 seconds

2026/06/14 05:31:42 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8483080021852007, Global best: 0.8483080021852007, Runtime: 6.93249 seconds

2026/06/14 05:31:48 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8491633442301691, Global best: 0.8491633442301691, Runtime: 5.47281 seconds

2026/06/14 05:31:52 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8494330021852007, Global best: 0.8494330021852007, Runtime: 4.36694 seconds

2026/06/14 05:31:57 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8505158278219704, Global best: 0.8505158278219704, Runtime: 4.86725 seconds

2026/06/14 05:32:01 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8509824211162054, Global best: 0.8509824211162054, Runtime: 4.17662 seconds

2026/06/14 05:32:06 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8518682661035442, Global best: 0.8518682661035442, Runtime: 4.62917 seconds

2026/06/14 05:32:12 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8525248651481661, Global best: 0.8525248651481661, Runtime: 5.69554 seconds

2026/06/14 05:32:17 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8530511704569802, Global best: 0.8530511704569802, Runtime: 5.71810 seconds

2026/06/14 05:32:23 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8537334862198968, Global best: 0.8537334862198968, Runtime: 5.99820 seconds

2026/06/14 05:32:29 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8542625795141315, Global best: 0.8542625795141315, Runtime: 6.06763 seconds

2026/06/14 05:32:35 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8549624096332817, Global best: 0.8549624096332817, Runtime: 5.52049 seconds

2026/06/14 05:32:41 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8555375515944504, Global best: 0.8555375515944504, Runtime: 6.49548 seconds

2026/06/14 05:32:48 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.85625981192835, Global best: 0.85625981192835, Runtime: 6.27152 seconds

2026/06/14 05:32:53 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.856889341572115, Global best: 0.856889341572115, Runtime: 5.46954 seconds

2026/06/14 05:32:59 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8573893415721151, Global best: 0.8573893415721151, Runtime: 5.66103 seconds

2026/06/14 05:33:04 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8580557661035442, Global best: 0.8580557661035442, Runtime: 5.37630 seconds

2026/06/14 05:33:10 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8586326701226964, Global best: 0.8586326701226964, Runtime: 5.51223 seconds

2026/06/14 05:33:15 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8592365936410129, Global best: 0.8592365936410129, Runtime: 5.59804 seconds

2026/06/14 05:33:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8592365936410129, Global best: 0.8592365936410129, Runtime: 5.61787 seconds

2026/06/14 05:43:18 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/14 05:43:30 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.7513377949362504, Global best: 0.7513377949362504, Runtime: 6.68742 seconds

2026/06/14 05:43:36 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.7523377949362504, Global best: 0.7523377949362504, Runtime: 6.30276 seconds

2026/06/14 05:43:42 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.7537130597809172, Global best: 0.7537130597809172, Runtime: 6.04350 seconds

2026/06/14 05:43:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.7537130597809172, Global best: 0.7537130597809172, Runtime: 6.46676 seconds

2026/06/14 05:43:55 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 5.83943 seconds

2026/06/14 05:44:01 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 6.31592 seconds

2026/06/14 05:44:07 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 6.23977 seconds

2026/06/14 05:44:13 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 6.30258 seconds

2026/06/14 05:44:20 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 6.99228 seconds

2026/06/14 05:44:27 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 6.33524 seconds

2026/06/14 05:44:33 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 6.56134 seconds

2026/06/14 05:44:40 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 6.51656 seconds

2026/06/14 05:44:46 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 6.19723 seconds

2026/06/14 05:44:52 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 6.39868 seconds

2026/06/14 05:44:59 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 6.78723 seconds

2026/06/14 05:45:08 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 8.49945 seconds

2026/06/14 05:45:14 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.7545880597809171, Global best: 0.7545880597809171, Runtime: 6.65701 seconds

2026/06/14 05:45:22 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 7.30354 seconds

2026/06/14 05:45:29 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 6.98163 seconds

2026/06/14 05:45:36 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 7.18070 seconds

2026/06/14 05:45:43 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 6.62478 seconds

2026/06/14 05:45:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 6.74549 seconds

2026/06/14 05:45:56 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 6.73110 seconds

2026/06/14 05:46:03 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 7.05572 seconds

2026/06/14 05:46:10 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 6.95766 seconds

2026/06/14 05:46:16 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 6.35687 seconds

2026/06/14 05:46:23 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 6.88927 seconds

2026/06/14 05:46:30 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 6.76736 seconds

2026/06/14 05:46:37 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 6.54854 seconds

2026/06/14 05:46:43 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.7626505597809171, Global best: 0.7626505597809171, Runtime: 6.27879 seconds

2026/06/14 06:20:15 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/14 06:20:25 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8137952162146652, Global best: 0.8137952162146652, Runtime: 5.61497 seconds

2026/06/14 06:20:32 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8149671629763471, Global best: 0.8149671629763471, Runtime: 6.34201 seconds

2026/06/14 06:20:37 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8279007088618777, Global best: 0.8279007088618777, Runtime: 5.80832 seconds

2026/06/14 06:20:44 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8292057914840809, Global best: 0.8292057914840809, Runtime: 6.30218 seconds

2026/06/14 06:20:50 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8320995648030225, Global best: 0.8320995648030225, Runtime: 6.43722 seconds

2026/06/14 06:20:56 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8335036916755953, Global best: 0.8335036916755953, Runtime: 5.94016 seconds

2026/06/14 06:21:00 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.834003842079374, Global best: 0.834003842079374, Runtime: 4.17409 seconds

2026/06/14 06:21:04 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8347913676926295, Global best: 0.8347913676926295, Runtime: 4.23138 seconds

2026/06/14 06:21:09 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8466415839110972, Global best: 0.8466415839110972, Runtime: 4.21043 seconds

2026/06/14 06:21:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8466415839110972, Global best: 0.8466415839110972, Runtime: 4.34088 seconds

2026/06/14 06:21:17 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8477793646224122, Global best: 0.8477793646224122, Runtime: 4.00539 seconds

2026/06/14 06:21:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8486298574485712, Global best: 0.8486298574485712, Runtime: 3.82677 seconds

2026/06/14 06:21:25 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8492313873952283, Global best: 0.8492313873952283, Runtime: 3.99252 seconds

2026/06/14 06:21:29 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8500077853046989, Global best: 0.8500077853046989, Runtime: 3.68379 seconds

2026/06/14 06:21:33 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8506927359147591, Global best: 0.8506927359147591, Runtime: 3.96742 seconds

2026/06/14 06:21:36 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8512489501505831, Global best: 0.8512489501505831, Runtime: 3.83276 seconds

2026/06/14 06:21:40 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8519149745880538, Global best: 0.8519149745880538, Runtime: 3.66631 seconds

2026/06/14 06:21:44 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8523881201787726, Global best: 0.8523881201787726, Runtime: 3.45694 seconds

2026/06/14 06:21:47 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8531571392447512, Global best: 0.8531571392447512, Runtime: 3.62097 seconds

2026/06/14 06:21:51 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8538417946726864, Global best: 0.8538417946726864, Runtime: 3.68385 seconds

2026/06/14 06:21:54 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8544793446628715, Global best: 0.8544793446628715, Runtime: 3.56227 seconds

2026/06/14 06:21:58 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8549014782148209, Global best: 0.8549014782148209, Runtime: 3.42858 seconds

2026/06/14 06:22:01 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8558823174116322, Global best: 0.8558823174116322, Runtime: 3.62101 seconds

2026/06/14 06:22:05 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8562470275107914, Global best: 0.8562470275107914, Runtime: 3.93802 seconds

2026/06/14 06:22:09 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8568859259689479, Global best: 0.8568859259689479, Runtime: 3.98668 seconds

2026/06/14 06:22:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.857480691409852, Global best: 0.857480691409852, Runtime: 3.92107 seconds

2026/06/14 06:22:17 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8581691411095193, Global best: 0.8581691411095193, Runtime: 3.52654 seconds

2026/06/14 06:22:20 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8588183804429507, Global best: 0.8588183804429507, Runtime: 3.62940 seconds

2026/06/14 06:22:24 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8594608773424579, Global best: 0.8594608773424579, Runtime: 3.62583 seconds

2026/06/14 06:22:28 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8594608773424579, Global best: 0.8594608773424579, Runtime: 3.77373 seconds

2026/06/14 06:32:18 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/14 06:32:29 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8253204347793313, Global best: 0.8253204347793313, Runtime: 5.41129 seconds

2026/06/14 06:32:34 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8253204347793313, Global best: 0.8253204347793313, Runtime: 5.45021 seconds

2026/06/14 06:32:40 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8253204347793313, Global best: 0.8253204347793313, Runtime: 5.51806 seconds

2026/06/14 06:32:45 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8280704347793313, Global best: 0.8280704347793313, Runtime: 5.37966 seconds

2026/06/14 06:32:50 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8280704347793313, Global best: 0.8280704347793313, Runtime: 5.40328 seconds

2026/06/14 06:32:56 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8290079347793313, Global best: 0.8290079347793313, Runtime: 5.28665 seconds

2026/06/14 06:33:02 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8290079347793313, Global best: 0.8290079347793313, Runtime: 5.99483 seconds

2026/06/14 06:33:07 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8317344908484596, Global best: 0.8317344908484596, Runtime: 5.53799 seconds

2026/06/14 06:33:13 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8317344908484596, Global best: 0.8317344908484596, Runtime: 5.67218 seconds

2026/06/14 06:33:18 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8317344908484596, Global best: 0.8317344908484596, Runtime: 5.46592 seconds

2026/06/14 06:33:24 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8317344908484596, Global best: 0.8317344908484596, Runtime: 5.70886 seconds

2026/06/14 06:33:30 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8341719908484596, Global best: 0.8341719908484596, Runtime: 6.34731 seconds

2026/06/14 06:33:36 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8352969908484597, Global best: 0.8352969908484597, Runtime: 5.55379 seconds

2026/06/14 06:33:41 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8352969908484597, Global best: 0.8352969908484597, Runtime: 5.36688 seconds

2026/06/14 06:33:47 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8352969908484597, Global best: 0.8352969908484597, Runtime: 5.34308 seconds

2026/06/14 06:33:53 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8352969908484597, Global best: 0.8352969908484597, Runtime: 5.80928 seconds

2026/06/14 06:33:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8352969908484597, Global best: 0.8352969908484597, Runtime: 5.55799 seconds

2026/06/14 06:34:04 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8352969908484597, Global best: 0.8352969908484597, Runtime: 5.36897 seconds

2026/06/14 06:34:10 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8352969908484597, Global best: 0.8352969908484597, Runtime: 6.23456 seconds

2026/06/14 06:34:15 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8352969908484597, Global best: 0.8352969908484597, Runtime: 5.58595 seconds

2026/06/14 06:34:21 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8352969908484597, Global best: 0.8352969908484597, Runtime: 5.48406 seconds

2026/06/14 06:34:27 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8352969908484597, Global best: 0.8352969908484597, Runtime: 5.88333 seconds

2026/06/14 06:34:32 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8410469908484596, Global best: 0.8410469908484596, Runtime: 5.16953 seconds

2026/06/14 06:34:37 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8410469908484596, Global best: 0.8410469908484596, Runtime: 5.31396 seconds

2026/06/14 06:34:42 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8410469908484596, Global best: 0.8410469908484596, Runtime: 5.27519 seconds

2026/06/14 06:34:48 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8410469908484596, Global best: 0.8410469908484596, Runtime: 5.29884 seconds

2026/06/14 06:34:53 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8410469908484596, Global best: 0.8410469908484596, Runtime: 5.50079 seconds

2026/06/14 06:34:59 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8410469908484596, Global best: 0.8410469908484596, Runtime: 5.55719 seconds

2026/06/14 06:35:05 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8410469908484596, Global best: 0.8410469908484596, Runtime: 5.84098 seconds

2026/06/14 06:35:10 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8410469908484596, Global best: 0.8410469908484596, Runtime: 5.69093 seconds

2026/06/14 07:05:55 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/14 07:06:07 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.7650916323396558, Global best: 0.7650916323396558, Runtime: 7.09486 seconds

2026/06/14 07:06:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.7748761443675296, Global best: 0.7748761443675296, Runtime: 6.59296 seconds

2026/06/14 07:06:18 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.7953833808093437, Global best: 0.7953833808093437, Runtime: 4.98540 seconds

2026/06/14 07:06:23 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8237312708459421, Global best: 0.8237312708459421, Runtime: 4.17543 seconds

2026/06/14 07:06:27 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8237312708459421, Global best: 0.8237312708459421, Runtime: 4.76601 seconds

2026/06/14 07:06:31 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8334597801018795, Global best: 0.8334597801018795, Runtime: 3.61255 seconds

2026/06/14 07:06:35 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8343835089108775, Global best: 0.8343835089108775, Runtime: 3.65309 seconds

2026/06/14 07:06:38 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8378083302702687, Global best: 0.8378083302702687, Runtime: 3.78617 seconds

2026/06/14 07:06:42 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8408857999157427, Global best: 0.8408857999157427, Runtime: 3.56657 seconds

2026/06/14 07:06:46 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8408857999157427, Global best: 0.8408857999157427, Runtime: 3.80823 seconds

2026/06/14 07:06:50 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8419951657618805, Global best: 0.8419951657618805, Runtime: 3.95272 seconds

2026/06/14 07:06:54 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8430763152082072, Global best: 0.8430763152082072, Runtime: 3.86085 seconds

2026/06/14 07:06:57 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8430763152082072, Global best: 0.8430763152082072, Runtime: 3.77630 seconds

2026/06/14 07:07:01 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8443404950211122, Global best: 0.8443404950211122, Runtime: 3.74718 seconds

2026/06/14 07:07:05 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8447342216526522, Global best: 0.8447342216526522, Runtime: 3.70332 seconds

2026/06/14 07:07:09 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8456994245731572, Global best: 0.8456994245731572, Runtime: 3.86020 seconds

2026/06/14 07:07:12 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8462987168239794, Global best: 0.8462987168239794, Runtime: 3.64208 seconds

2026/06/14 07:07:16 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8469705235426727, Global best: 0.8469705235426727, Runtime: 4.12608 seconds

2026/06/14 07:07:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8474991030183938, Global best: 0.8474991030183938, Runtime: 4.14100 seconds

2026/06/14 07:07:25 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8481531887891471, Global best: 0.8481531887891471, Runtime: 4.50955 seconds

2026/06/14 07:07:29 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8488147445442846, Global best: 0.8488147445442846, Runtime: 4.04203 seconds

2026/06/14 07:07:33 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8495578673387985, Global best: 0.8495578673387985, Runtime: 3.82520 seconds

2026/06/14 07:07:37 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8500242494335982, Global best: 0.8500242494335982, Runtime: 4.32424 seconds

2026/06/14 07:07:41 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8507051625960812, Global best: 0.8507051625960812, Runtime: 3.89650 seconds

2026/06/14 07:07:45 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8514149100252633, Global best: 0.8514149100252633, Runtime: 3.74842 seconds

2026/06/14 07:07:49 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8519961850708346, Global best: 0.8519961850708346, Runtime: 3.85813 seconds

2026/06/14 07:07:53 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8525636174534135, Global best: 0.8525636174534135, Runtime: 3.67243 seconds

2026/06/14 07:07:56 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8532243569786584, Global best: 0.8532243569786584, Runtime: 3.84133 seconds

2026/06/14 07:08:00 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8539118569786585, Global best: 0.8539118569786585, Runtime: 3.97682 seconds

2026/06/14 07:08:04 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8539118569786585, Global best: 0.8539118569786585, Runtime: 3.87296 seconds

2026/06/14 07:16:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/14 07:17:09 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8125267092858712, Global best: 0.8125267092858712, Runtime: 5.42566 seconds

2026/06/14 07:17:14 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8125267092858712, Global best: 0.8125267092858712, Runtime: 5.23209 seconds

2026/06/14 07:17:20 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8145892092858713, Global best: 0.8145892092858713, Runtime: 5.38124 seconds

2026/06/14 07:17:26 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8145892092858713, Global best: 0.8145892092858713, Runtime: 5.68048 seconds

2026/06/14 07:17:32 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8157142092858712, Global best: 0.8157142092858712, Runtime: 6.06327 seconds

2026/06/14 07:17:37 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8193706316636846, Global best: 0.8193706316636846, Runtime: 5.52022 seconds

2026/06/14 07:17:42 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8193706316636846, Global best: 0.8193706316636846, Runtime: 5.13993 seconds

2026/06/14 07:17:47 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8204956316636846, Global best: 0.8204956316636846, Runtime: 5.23617 seconds

2026/06/14 07:17:53 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8204956316636846, Global best: 0.8204956316636846, Runtime: 5.57805 seconds

2026/06/14 07:17:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.39978 seconds

2026/06/14 07:18:04 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.44828 seconds

2026/06/14 07:18:09 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.50936 seconds

2026/06/14 07:18:15 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.18640 seconds

2026/06/14 07:18:20 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.87434 seconds

2026/06/14 07:18:26 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.41570 seconds

2026/06/14 07:18:32 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.84468 seconds

2026/06/14 07:18:37 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.54146 seconds

2026/06/14 07:18:43 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.56612 seconds

2026/06/14 07:18:48 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.37471 seconds

2026/06/14 07:18:54 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.53168 seconds

2026/06/14 07:18:59 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.39377 seconds

2026/06/14 07:19:05 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.45593 seconds

2026/06/14 07:19:10 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.56775 seconds

2026/06/14 07:19:16 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.74712 seconds

2026/06/14 07:19:21 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.44501 seconds

2026/06/14 07:19:27 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.49762 seconds

2026/06/14 07:19:33 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.72003 seconds

2026/06/14 07:19:38 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.57561 seconds

2026/06/14 07:19:44 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.92066 seconds

2026/06/14 07:19:50 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8218081316636846, Global best: 0.8218081316636846, Runtime: 5.82912 seconds

2026/06/14 07:48:28 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/14 07:48:37 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.7890075268983237, Global best: 0.7890075268983237, Runtime: 4.94603 seconds

2026/06/14 07:48:42 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8036905230951332, Global best: 0.8036905230951332, Runtime: 5.05520 seconds

2026/06/14 07:48:47 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8245791715749645, Global best: 0.8245791715749645, Runtime: 4.85530 seconds

2026/06/14 07:48:52 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8245791715749645, Global best: 0.8245791715749645, Runtime: 4.27240 seconds

2026/06/14 07:48:57 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.829884601166633, Global best: 0.829884601166633, Runtime: 5.01185 seconds

2026/06/14 07:49:01 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.829884601166633, Global best: 0.829884601166633, Runtime: 4.16026 seconds

2026/06/14 07:49:05 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.829884601166633, Global best: 0.829884601166633, Runtime: 3.96568 seconds

2026/06/14 07:49:09 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.829884601166633, Global best: 0.829884601166633, Runtime: 3.98980 seconds

2026/06/14 07:49:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.836645003574163, Global best: 0.836645003574163, Runtime: 3.95800 seconds

2026/06/14 07:49:16 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8424122523479657, Global best: 0.8424122523479657, Runtime: 3.77244 seconds

2026/06/14 07:49:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8424122523479657, Global best: 0.8424122523479657, Runtime: 4.55365 seconds

2026/06/14 07:49:25 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.843824466565925, Global best: 0.843824466565925, Runtime: 3.83913 seconds

2026/06/14 07:49:28 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8444643315279674, Global best: 0.8444643315279674, Runtime: 3.64700 seconds

2026/06/14 07:49:32 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.845081296517858, Global best: 0.845081296517858, Runtime: 3.82593 seconds

2026/06/14 07:49:36 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8456840817828637, Global best: 0.8456840817828637, Runtime: 3.94521 seconds

2026/06/14 07:49:40 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8463966420431204, Global best: 0.8463966420431204, Runtime: 3.80477 seconds

2026/06/14 07:49:44 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8469777374907681, Global best: 0.8469777374907681, Runtime: 3.84833 seconds

2026/06/14 07:49:48 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8475369885768184, Global best: 0.8475369885768184, Runtime: 3.73629 seconds

2026/06/14 07:49:51 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8483364412311617, Global best: 0.8483364412311617, Runtime: 3.77273 seconds

2026/06/14 07:49:55 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8487751506267123, Global best: 0.8487751506267123, Runtime: 3.68759 seconds

2026/06/14 07:49:59 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8495346138874103, Global best: 0.8495346138874103, Runtime: 3.57754 seconds

2026/06/14 07:50:03 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8500233747171986, Global best: 0.8500233747171986, Runtime: 4.00822 seconds

2026/06/14 07:50:07 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8507215949426937, Global best: 0.8507215949426937, Runtime: 4.10237 seconds

2026/06/14 07:50:12 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8513071251076941, Global best: 0.8513071251076941, Runtime: 4.81312 seconds

2026/06/14 07:50:16 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.852020727992784, Global best: 0.852020727992784, Runtime: 4.11327 seconds

2026/06/14 07:50:20 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8525527415318321, Global best: 0.8525527415318321, Runtime: 4.56402 seconds

2026/06/14 07:50:24 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8532455771937519, Global best: 0.8532455771937519, Runtime: 3.89609 seconds

2026/06/14 07:50:28 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.853833227992784, Global best: 0.853833227992784, Runtime: 3.76462 seconds

2026/06/14 07:50:32 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.854458227992784, Global best: 0.854458227992784, Runtime: 3.88746 seconds

2026/06/14 07:50:36 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.854458227992784, Global best: 0.854458227992784, Runtime: 3.84599 seconds

2026/06/14 07:57:57 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/14 07:58:06 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.7684697139023164, Global best: 0.7684697139023164, Runtime: 4.20488 seconds

2026/06/14 07:58:11 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.7684697139023164, Global best: 0.7684697139023164, Runtime: 4.68004 seconds

2026/06/14 07:58:15 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.7684697139023164, Global best: 0.7684697139023164, Runtime: 4.71589 seconds

2026/06/14 07:58:20 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.7684697139023164, Global best: 0.7684697139023164, Runtime: 4.71207 seconds

2026/06/14 07:58:25 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.7684697139023164, Global best: 0.7684697139023164, Runtime: 4.93897 seconds

2026/06/14 07:58:30 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.7684697139023164, Global best: 0.7684697139023164, Runtime: 4.84816 seconds

2026/06/14 07:58:35 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.7684697139023164, Global best: 0.7684697139023164, Runtime: 4.72460 seconds

2026/06/14 07:58:39 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.7737173767273416, Global best: 0.7737173767273416, Runtime: 4.60405 seconds

2026/06/14 07:58:44 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.7737173767273416, Global best: 0.7737173767273416, Runtime: 4.86058 seconds

2026/06/14 07:58:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.7748423767273417, Global best: 0.7748423767273417, Runtime: 4.60651 seconds

2026/06/14 07:58:53 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.7748423767273417, Global best: 0.7748423767273417, Runtime: 4.61112 seconds

2026/06/14 07:58:59 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.7760646908296011, Global best: 0.7760646908296011, Runtime: 5.16772 seconds

2026/06/14 07:59:03 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.7760646908296011, Global best: 0.7760646908296011, Runtime: 4.60157 seconds

2026/06/14 07:59:08 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.7760646908296011, Global best: 0.7760646908296011, Runtime: 4.62762 seconds

2026/06/14 07:59:12 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.7760646908296011, Global best: 0.7760646908296011, Runtime: 4.61336 seconds

2026/06/14 07:59:17 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.778502190829601, Global best: 0.778502190829601, Runtime: 4.80340 seconds

2026/06/14 07:59:22 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.778502190829601, Global best: 0.778502190829601, Runtime: 4.72317 seconds

2026/06/14 07:59:27 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.778502190829601, Global best: 0.778502190829601, Runtime: 4.58130 seconds

2026/06/14 07:59:31 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.7805646908296011, Global best: 0.7805646908296011, Runtime: 4.49033 seconds

2026/06/14 07:59:36 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.7814396908296011, Global best: 0.7814396908296011, Runtime: 4.70526 seconds

2026/06/14 07:59:41 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.7820646908296011, Global best: 0.7820646908296011, Runtime: 4.83650 seconds

2026/06/14 07:59:45 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.7820646908296011, Global best: 0.7820646908296011, Runtime: 4.49595 seconds

2026/06/14 07:59:50 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.7820646908296011, Global best: 0.7820646908296011, Runtime: 4.59251 seconds

2026/06/14 07:59:54 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.7820646908296011, Global best: 0.7820646908296011, Runtime: 4.37057 seconds

2026/06/14 07:59:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.7844396908296011, Global best: 0.7844396908296011, Runtime: 4.38416 seconds

2026/06/14 08:00:04 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.785127190829601, Global best: 0.785127190829601, Runtime: 5.92223 seconds

2026/06/14 08:00:08 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.785127190829601, Global best: 0.785127190829601, Runtime: 4.15908 seconds

2026/06/14 08:00:13 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.785127190829601, Global best: 0.785127190829601, Runtime: 4.54938 seconds

2026/06/14 08:00:18 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.785127190829601, Global best: 0.785127190829601, Runtime: 4.78305 seconds

2026/06/14 08:00:22 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.785127190829601, Global best: 0.785127190829601, Runtime: 4.53138 seconds

2026/06/14 08:26:15 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: OriginalGWO(epoch=30, pop_size=10)

2026/06/14 08:26:26 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 1, Current best: 0.8134175193622041, Global best: 0.8134175193622041, Runtime: 4.83487 seconds

2026/06/14 08:26:30 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 2, Current best: 0.8134175193622041, Global best: 0.8134175193622041, Runtime: 4.47446 seconds

2026/06/14 08:26:36 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 3, Current best: 0.8301749438333571, Global best: 0.8301749438333571, Runtime: 5.48591 seconds

2026/06/14 08:26:41 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 4, Current best: 0.8311844627601604, Global best: 0.8311844627601604, Runtime: 5.25547 seconds

2026/06/14 08:26:46 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 5, Current best: 0.8316893508797137, Global best: 0.8316893508797137, Runtime: 5.19390 seconds

2026/06/14 08:26:51 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 6, Current best: 0.8354540100101836, Global best: 0.8354540100101836, Runtime: 4.69915 seconds

2026/06/14 08:26:56 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 7, Current best: 0.8354540100101836, Global best: 0.8354540100101836, Runtime: 5.31515 seconds

2026/06/14 08:27:01 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 8, Current best: 0.8448849652523259, Global best: 0.8448849652523259, Runtime: 4.73752 seconds

2026/06/14 08:27:06 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 9, Current best: 0.8455463896856015, Global best: 0.8455463896856015, Runtime: 5.41823 seconds

2026/06/14 08:27:11 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 10, Current best: 0.8458055990862074, Global best: 0.8458055990862074, Runtime: 4.83014 seconds

2026/06/14 08:27:16 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 11, Current best: 0.8469350821055754, Global best: 0.8469350821055754, Runtime: 4.80021 seconds

2026/06/14 08:27:21 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 12, Current best: 0.8474403157128588, Global best: 0.8474403157128588, Runtime: 4.80988 seconds

2026/06/14 08:27:26 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 13, Current best: 0.8491388117492695, Global best: 0.8491388117492695, Runtime: 4.99066 seconds

2026/06/14 08:27:31 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 14, Current best: 0.8500630201249625, Global best: 0.8500630201249625, Runtime: 5.13686 seconds

2026/06/14 08:27:36 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 15, Current best: 0.8509146388392097, Global best: 0.8509146388392097, Runtime: 4.97524 seconds

2026/06/14 08:27:41 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 16, Current best: 0.8515393557259352, Global best: 0.8515393557259352, Runtime: 5.38641 seconds

2026/06/14 08:27:46 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 17, Current best: 0.8519901473502424, Global best: 0.8519901473502424, Runtime: 5.03742 seconds

2026/06/14 08:27:52 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 18, Current best: 0.8527638117492695, Global best: 0.8527638117492695, Runtime: 6.04992 seconds

2026/06/14 08:27:57 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 19, Current best: 0.8532849209979284, Global best: 0.8532849209979284, Runtime: 4.99570 seconds

2026/06/14 08:28:03 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 20, Current best: 0.8540630201249625, Global best: 0.8540630201249625, Runtime: 5.17872 seconds

2026/06/14 08:28:08 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 21, Current best: 0.8546210837812299, Global best: 0.8546210837812299, Runtime: 5.39430 seconds

2026/06/14 08:28:13 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 22, Current best: 0.8551599209979284, Global best: 0.8551599209979284, Runtime: 4.85607 seconds

2026/06/14 08:28:18 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 23, Current best: 0.8557895141424524, Global best: 0.8557895141424524, Runtime: 5.56909 seconds

2026/06/14 08:28:24 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 24, Current best: 0.8565458060816195, Global best: 0.8565458060816195, Runtime: 5.07171 seconds

2026/06/14 08:28:29 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 25, Current best: 0.8570349209979283, Global best: 0.8570349209979283, Runtime: 5.14509 seconds

2026/06/14 08:28:34 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 26, Current best: 0.8577952921569227, Global best: 0.8577952921569227, Runtime: 5.19579 seconds

2026/06/14 08:28:40 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 27, Current best: 0.8583888117492695, Global best: 0.8583888117492695, Runtime: 5.76305 seconds

2026/06/14 08:28:45 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 28, Current best: 0.8589459322802238, Global best: 0.8589459322802238, Runtime: 5.01613 seconds

2026/06/14 08:28:50 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 29, Current best: 0.8595709322802237, Global best: 0.8595709322802237, Runtime: 5.37993 seconds

2026/06/14 08:28:55 PM, INFO, mealpy.swarm_based.GWO.OriginalGWO: >>>Problem: P, Epoch: 30, Current best: 0.8595709322802237, Global best: 0.8595709322802237, Runtime: 4.80667 seconds

2026/06/14 08:36:49 PM, INFO, mealpy.swarm_based.BA.OriginalBA: OriginalBA(epoch=30, pop_size=10, loudness=0.8, pulse_rate=0.95, pf_min=0.0, pf_max=10.0)

2026/06/14 08:36:58 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 1, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 4.64121 seconds

2026/06/14 08:37:04 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 2, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.92291 seconds

2026/06/14 08:37:10 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 3, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.57182 seconds

2026/06/14 08:37:15 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 4, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.36972 seconds

2026/06/14 08:37:21 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 5, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.61221 seconds

2026/06/14 08:37:26 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 6, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.33903 seconds

2026/06/14 08:37:32 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 7, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.62366 seconds

2026/06/14 08:37:37 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 8, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.46060 seconds

2026/06/14 08:37:42 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 9, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.14316 seconds

2026/06/14 08:37:48 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 10, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.96180 seconds

2026/06/14 08:37:54 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 11, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.40546 seconds

2026/06/14 08:37:59 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 12, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.40432 seconds

2026/06/14 08:38:05 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 13, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.56833 seconds

2026/06/14 08:38:10 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 14, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.29023 seconds

2026/06/14 08:38:16 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 15, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.68664 seconds

2026/06/14 08:38:22 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 16, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.73774 seconds

2026/06/14 08:38:27 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 17, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.63236 seconds

2026/06/14 08:38:33 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 18, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.65370 seconds

2026/06/14 08:38:38 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 19, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.59809 seconds

2026/06/14 08:38:44 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 20, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.54861 seconds

2026/06/14 08:38:50 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 21, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.53874 seconds

2026/06/14 08:38:55 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 22, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.42176 seconds

2026/06/14 08:39:01 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 23, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.77796 seconds

2026/06/14 08:39:07 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 24, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 6.07997 seconds

2026/06/14 08:39:12 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 25, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.63988 seconds

2026/06/14 08:39:18 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 26, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.80552 seconds

2026/06/14 08:39:24 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 27, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.74420 seconds

2026/06/14 08:39:30 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 28, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.89796 seconds

2026/06/14 08:39:36 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 29, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.77001 seconds

2026/06/14 08:39:41 PM, INFO, mealpy.swarm_based.BA.OriginalBA: >>>Problem: P, Epoch: 30, Current best: 0.8171893094071271, Global best: 0.8171893094071271, Runtime: 5.58198 seconds

,seed,method,k_target,n_selected,selected_features,fs_time_s
0,0,BA,10.0,10,"0,2,3,7,12,14,11,8,15,19",168.759629
1,0,Boruta,NaN,9,"2,5,7,8,14,15,17,18,19",9.137082
2,0,GWO,10.0,10,"8,1,18,5,14,17,15,2,7,19",176.650451
3,0,LightGBM,10.0,10,"9,19,8,14,7,15,18,0,17,12",88.106288
4,1,BA,10.0,10,"0,2,5,4,7,14,10,8,20,17",202.160513
5,1,Boruta,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.395444
6,1,GWO,10.0,10,"1,2,22,14,5,17,15,19,18,7",138.935049
7,1,LightGBM,10.0,10,"9,19,8,14,7,15,18,0,17,12",81.818006
8,2,BA,10.0,10,"0,3,7,8,9,14,19,16,20,21",203.295567
9,2,Boruta,NaN,10,"2,5,7,8,9,14,15,17,18,19",8.567171
10,2,GWO,10.0,10,"7,19,1,14,18,4,3,11,15,17",130.602186
11,2,LightGBM,10.0,10,"9,19,8,14,7,15,18,0,17,12",141.659361
12,3,BA,10.0,10,"1,2,7,14,21,5,19,16,13,18",171.932050
13,3,Boruta,NaN,10,"2,5,7,8,9,14,15,17,18,19",10.764830
14,3,GWO,10.0,10,"11,14,17,7,18,19,2,15,3,1",140.634687
15,3,LightGBM,10.0,10,"9,19,8,14,7,15,0,18,17,12",128.078672
16,4,BA,10.0,10,"1,2,6,4,7,8,9,19,18,20",205.178591
17,4,Boruta,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.250404
18,4,GWO,10.0,10,"5,11,7,2,15,14,1,19,8,18",154.844487
19,4,LightGBM,10.0,10,"9,19,8,14,7,15,0,18,17,12",113.855563
20,5,BA,10.0,10,"2,6,5,4,7,13,11,8,14,12",205.587397
21,5,Boruta,NaN,9,"2,5,7,8,14,15,17,18,19",9.027997
22,5,GWO,10.0,10,"7,2,18,17,1,19,10,5,14,9",164.252366
23,5,LightGBM,10.0,10,"9,19,8,14,7,15,0,18,17,12",140.478651
24,6,BA,10.0,10,"2,7,6,10,15,14,18,16,21,19",173.001852
25,6,Boruta,NaN,10,"2,5,7,8,9,14,15,17,18,19",8.124758
26,6,GWO,10.0,10,"18,17,15,12,16,7,2,19,1,14",133.162690
27,6,LightGBM,10.0,10,"9,19,8,14,7,15,18,0,17,12",153.141537
28,7,BA,10.0,10,"2,6,5,4,7,14,11,8,15,19",172.445517
29,7,Boruta,NaN,10,"2,5,7,8,9,14,15,17,18,19",7.565393
30,7,GWO,10.0,10,"17,2,3,14,5,7,15,11,19,0",129.965381
31,7,LightGBM,10.0,10,"9,19,8,14,7,15,0,18,17,12",126.789877
32,8,BA,10.0,10,"5,14,15,11,20,21,10,0,19,7",145.418252
33,8,Boruta,NaN,8,"2,7,8,14,15,17,18,19",9.969898
34,8,GWO,10.0,10,"14,17,18,2,12,15,19,7,23,5",127.725921
35,8,LightGBM,10.0,10,"9,19,8,14,7,15,18,0,17,12",87.892781
36,9,BA,10.0,10,"0,1,2,3,7,14,10,9,15,19",172.537136
37,9,Boruta,NaN,10,"2,5,7,8,9,14,15,17,18,19",5.657168
38,9,GWO,10.0,10,"19,5,2,6,14,7,11,17,8,18",160.361275
39,9,LightGBM,10.0,10,"9,19,8,14,7,15,18,0,17,12",85.513551

  index    method   fs_time_s            n_selected
                         mean        std       mean       std
0     0        BA  182.031650  20.629660       10.0  0.000000
1     1    Boruta    8.746015   1.407713        9.6  0.699206
2     2       GWO  145.713449  17.087648       10.0  0.000000
3     3  LightGBM  114.733429  26.985347       10.0  0.000000

Feature-selection stability across runs

     method  mean_pairwise_jaccard  std_pairwise_jaccard  n_pairs
0  LightGBM               1.000000              0.000000       45
1    Boruta               0.932840              0.073291       45
2       GWO               0.585193              0.100605       45
3        BA               0.360625              0.100359       45

,seed,method,classifier,k_target,n_selected,selected_features,fs_time_s,accuracy,precision_macro,recall_macro,f1_macro,mcc,train_time_s,inference_time_ms,peak_mem_mb
0,0,GWO,RandomForest,10.0,10,"8,1,18,5,14,17,15,2,7,19",176.650451,0.904289,0.870065,0.908855,0.874504,0.894719,99.016169,8651.283895,39.981109
1,0,GWO,DecisionTree,10.0,10,"8,1,18,5,14,17,15,2,7,19",176.650451,0.889525,0.856957,0.895926,0.861853,0.878321,1.551409,50.458688,25.134427
2,0,GWO,LogisticRegression,10.0,10,"8,1,18,5,14,17,15,2,7,19",176.650451,0.553500,0.531223,0.606696,0.530317,0.512488,31.876830,57.009064,25.140895
3,0,GWO,GaussianNB,10.0,10,"8,1,18,5,14,17,15,2,7,19",176.650451,0.320555,0.359783,0.390254,0.321915,0.278136,0.260461,83.771988,25.131522
4,0,GWO,HistGradientBoosting,10.0,10,"8,1,18,5,14,17,15,2,7,19",176.650451,0.910892,0.890108,0.913557,0.889162,0.902048,279.714042,3445.726580,31.750505
5,0,GWO,MLP,10.0,10,"8,1,18,5,14,17,15,2,7,19",176.650451,0.893839,0.875088,0.898722,0.874127,0.883240,250.177375,151.226375,47.077561
6,0,BA,RandomForest,10.0,10,"0,2,3,7,12,14,11,8,15,19",168.759629,0.881688,0.844537,0.889745,0.853303,0.869759,85.987437,9716.522272,42.011922
7,0,BA,DecisionTree,10.0,10,"0,2,3,7,12,14,11,8,15,19",168.759629,0.863174,0.827444,0.873649,0.837238,0.849178,1.014715,31.068324,25.135661
8,0,BA,LogisticRegression,10.0,10,"0,2,3,7,12,14,11,8,15,19",168.759629,0.584776,0.553518,0.636219,0.566498,0.544232,42.848815,51.665763,25.138180
9,0,BA,GaussianNB,10.0,10,"0,2,3,7,12,14,11,8,15,19",168.759629,0.245324,0.306300,0.324502,0.229238,0.209525,0.288056,77.662761,25.128451
10,0,BA,HistGradientBoosting,10.0,10,"0,2,3,7,12,14,11,8,15,19",168.759629,0.884372,0.869606,0.890954,0.866978,0.872907,221.219034,5582.778391,31.988757
11,0,BA,MLP,10.0,10,"0,2,3,7,12,14,11,8,15,19",168.759629,0.853096,0.844577,0.864068,0.839979,0.838646,190.931326,107.864643,47.072351
12,0,LightGBM,RandomForest,10.0,10,"9,19,8,14,7,15,18,0,17,12",88.106288,0.898369,0.841198,0.858248,0.829051,0.888305,91.364529,10316.784996,40.011451
13,0,LightGBM,DecisionTree,10.0,10,"9,19,8,14,7,15,18,0,17,12",88.106288,0.882443,0.826222,0.843775,0.814850,0.870577,1.092086,28.678026,25.138530
14,0,LightGBM,LogisticRegression,10.0,10,"9,19,8,14,7,15,18,0,17,12",88.106288,0.576112,0.514672,0.586052,0.524341,0.535317,42.758344,67.199328,25.137023
15,0,LightGBM,GaussianNB,10.0,10,"9,19,8,14,7,15,18,0,17,12",88.106288,0.338254,0.242393,0.380377,0.269723,0.300478,0.262686,82.185912,25.130971
16,0,LightGBM,HistGradientBoosting,10.0,10,"9,19,8,14,7,15,18,0,17,12",88.106288,0.902012,0.880750,0.862007,0.839085,0.892360,231.645284,5539.212388,32.178781
17,0,LightGBM,MLP,10.0,10,"9,19,8,14,7,15,18,0,17,12",88.106288,0.876380,0.874133,0.822491,0.813868,0.864049,135.091753,157.180478,47.065494
18,0,Boruta,RandomForest,NaN,9,"2,5,7,8,14,15,17,18,19",9.137082,0.899472,0.880458,0.903568,0.872624,0.889878,99.306638,9388.606045,39.130031
19,0,Boruta,DecisionTree,NaN,9,"2,5,7,8,14,15,17,18,19",9.137082,0.884636,0.867314,0.890574,0.859900,0.873408,0.883067,28.164046,22.855327
20,0,Boruta,LogisticRegression,NaN,9,"2,5,7,8,14,15,17,18,19",9.137082,0.527891,0.495702,0.579214,0.486087,0.485778,27.646223,94.640778,22.852755
21,0,Boruta,GaussianNB,NaN,9,"2,5,7,8,14,15,17,18,19",9.137082,0.408273,0.340597,0.475210,0.345045,0.368132,0.307052,103.005836,22.847268
22,0,Boruta,HistGradientBoosting,NaN,9,"2,5,7,8,14,15,17,18,19",9.137082,0.907381,0.928551,0.859968,0.876880,0.898142,237.423827,7903.919544,30.633062
23,0,Boruta,MLP,NaN,9,"2,5,7,8,14,15,17,18,19",9.137082,0.889070,0.912838,0.844389,0.860912,0.877975,247.035610,155.212919,46.639842
24,1,GWO,RandomForest,10.0,10,"1,2,22,14,5,17,15,19,18,7",138.935049,0.900993,0.866947,0.906409,0.871652,0.891036,95.868002,9350.721982,39.776575
25,1,GWO,DecisionTree,10.0,10,"1,2,22,14,5,17,15,19,18,7",138.935049,0.889489,0.856778,0.896410,0.861742,0.878284,0.684325,28.852100,25.134916
26,1,GWO,LogisticRegression,10.0,10,"1,2,22,14,5,17,15,19,18,7",138.935049,0.573572,0.570420,0.621815,0.558652,0.535280,34.537737,48.447902,25.136334
27,1,GWO,GaussianNB,10.0,10,"1,2,22,14,5,17,15,19,18,7",138.935049,0.289961,0.322229,0.363967,0.288025,0.245456,0.247473,74.704811,25.129005
28,1,GWO,HistGradientBoosting,10.0,10,"1,2,22,14,5,17,15,19,18,7",138.935049,0.907560,0.883779,0.910273,0.884359,0.898407,225.979956,1538.391513,31.688996
29,1,GWO,MLP,10.0,10,"1,2,22,14,5,17,15,19,18,7",138.935049,0.890760,0.911257,0.845647,0.861664,0.879486,172.948599,159.954801,47.069658
30,1,BA,RandomForest,10.0,10,"0,2,5,4,7,14,10,8,20,17",202.160513,0.843114,0.800542,0.850281,0.809818,0.827656,95.280482,12510.480152,39.947965
31,1,BA,DecisionTree,10.0,10,"0,2,5,4,7,14,10,8,20,17",202.160513,0.831178,0.790414,0.840001,0.799522,0.814527,0.895390,30.671436,25.134534
32,1,BA,LogisticRegression,10.0,10,"0,2,5,4,7,14,10,8,20,17",202.160513,0.353869,0.363760,0.436345,0.326014,0.299626,41.509516,92.169157,25.133137
33,1,BA,GaussianNB,10.0,10,"0,2,5,4,7,14,10,8,20,17",202.160513,0.247337,0.273302,0.328749,0.226657,0.199642,0.267044,77.294703,25.128312
34,1,BA,HistGradientBoosting,10.0,10,"0,2,5,4,7,14,10,8,20,17",202.160513,0.849489,0.844798,0.852301,0.831516,0.835512,181.082903,4610.627618,31.780494
35,1,BA,MLP,10.0,10,"0,2,5,4,7,14,10,8,20,17",202.160513,0.801412,0.852217,0.759317,0.783200,0.782639,232.317936,142.858433,47.073453
36,1,LightGBM,RandomForest,10.0,10,"9,19,8,14,7,15,18,0,17,12",81.818006,0.898717,0.827118,0.862241,0.829782,0.888701,90.911297,8715.689576,39.269587
37,1,LightGBM,DecisionTree,10.0,10,"9,19,8,14,7,15,18,0,17,12",81.818006,0.883618,0.813117,0.848694,0.816575,0.871882,1.138307,33.633531,25.129479
38,1,LightGBM,LogisticRegression,10.0,10,"9,19,8,14,7,15,18,0,17,12",81.818006,0.575154,0.513237,0.585220,0.523469,0.534241,45.551744,71.375234,25.134432
39,1,LightGBM,GaussianNB,10.0,10,"9,19,8,14,7,15,18,0,17,12",81.818006,0.350142,0.250487,0.390454,0.279270,0.310762,0.255660,84.056737,25.128744
40,1,LightGBM,HistGradientBoosting,10.0,10,"9,19,8,14,7,15,18,0,17,12",81.818006,0.893072,0.863148,0.854004,0.829790,0.882533,287.577299,932.022748,31.748204
41,1,LightGBM,MLP,10.0,10,"9,19,8,14,7,15,18,0,17,12",81.818006,0.878009,0.888712,0.807567,0.813982,0.865598,190.801310,143.939702,47.069475
42,1,Boruta,RandomForest,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.395444,0.901808,0.883047,0.905654,0.874760,0.892501,85.166363,10730.145598,39.325668
43,1,Boruta,DecisionTree,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.395444,0.886302,0.868843,0.891958,0.861344,0.875246,0.978523,25.476857,25.129258
44,1,Boruta,LogisticRegression,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.395444,0.515476,0.477670,0.570228,0.472774,0.472568,29.491860,62.308813,25.140331
45,1,Boruta,GaussianNB,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.395444,0.407758,0.340020,0.474943,0.344595,0.367556,0.358681,99.046952,25.129714
46,1,Boruta,HistGradientBoosting,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.395444,0.905463,0.923512,0.854407,0.871408,0.896034,224.495077,3649.729155,31.539021
47,1,Boruta,MLP,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.395444,0.887752,0.911852,0.843302,0.859775,0.876508,192.628279,227.929203,47.065724
48,2,GWO,RandomForest,10.0,10,"7,19,1,14,18,4,3,11,15,17",130.602186,0.894954,0.858516,0.875983,0.848069,0.884412,86.738298,10717.328326,39.269147
49,2,GWO,DecisionTree,10.0,10,"7,19,1,14,18,4,3,11,15,17",130.602186,0.884528,0.849384,0.867038,0.839190,0.872856,0.671469,29.475079,25.135365
50,2,GWO,LogisticRegression,10.0,10,"7,19,1,14,18,4,3,11,15,17",130.602186,0.595058,0.516065,0.611657,0.534791,0.558204,54.976026,72.151816,25.136541
51,2,GWO,GaussianNB,10.0,10,"7,19,1,14,18,4,3,11,15,17",130.602186,0.325828,0.321138,0.370317,0.282123,0.291353,0.268488,85.338757,25.130840
52,2,GWO,HistGradientBoosting,10.0,10,"7,19,1,14,18,4,3,11,15,17",130.602186,0.906482,0.886064,0.884714,0.864673,0.897318,281.737445,2183.213706,32.118731
53,2,GWO,MLP,10.0,10,"7,19,1,14,18,4,3,11,15,17",130.602186,0.882683,0.892697,0.830744,0.839269,0.870800,177.130962,171.518396,47.071792
54,2,BA,RandomForest,10.0,10,"0,3,7,8,9,14,19,16,20,21",203.295567,0.868734,0.807675,0.850023,0.812940,0.855767,99.901028,11466.698114,39.706571
55,2,BA,DecisionTree,10.0,10,"0,3,7,8,9,14,19,16,20,21",203.295567,0.849681,0.789103,0.832837,0.796242,0.834445,1.239524,29.863331,25.138987
56,2,BA,LogisticRegression,10.0,10,"0,3,7,8,9,14,19,16,20,21",203.295567,0.411569,0.391201,0.451091,0.378870,0.359281,21.020268,104.787022,25.145113
57,2,BA,GaussianNB,10.0,10,"0,3,7,8,9,14,19,16,20,21",203.295567,0.179691,0.197991,0.237036,0.140119,0.117398,0.337950,78.154375,25.136366
58,2,BA,HistGradientBoosting,10.0,10,"0,3,7,8,9,14,19,16,20,21",203.295567,0.866386,0.841559,0.843807,0.820081,0.853296,157.054007,1651.206013,31.507567
59,2,BA,MLP,10.0,10,"0,3,7,8,9,14,19,16,20,21",203.295567,0.829393,0.826368,0.811239,0.790904,0.812937,122.736179,110.370367,47.134449
60,2,LightGBM,RandomForest,10.0,10,"9,19,8,14,7,15,18,0,17,12",141.659361,0.896811,0.823337,0.861155,0.826748,0.886645,97.942486,10871.877856,39.990760
61,2,LightGBM,DecisionTree,10.0,10,"9,19,8,14,7,15,18,0,17,12",141.659361,0.880011,0.807977,0.846080,0.812069,0.867962,1.108634,27.003676,25.139393
62,2,LightGBM,LogisticRegression,10.0,10,"9,19,8,14,7,15,18,0,17,12",141.659361,0.576723,0.514913,0.586745,0.524989,0.535988,39.440694,38.375602,25.136822
63,2,LightGBM,GaussianNB,10.0,10,"9,19,8,14,7,15,18,0,17,12",141.659361,0.333138,0.244206,0.375607,0.268904,0.295706,0.303921,84.448527,25.131052
64,2,LightGBM,HistGradientBoosting,10.0,10,"9,19,8,14,7,15,18,0,17,12",141.659361,0.901329,0.871968,0.858182,0.833475,0.891629,291.384669,5539.554004,32.025454
65,2,LightGBM,MLP,10.0,10,"9,19,8,14,7,15,18,0,17,12",141.659361,0.879507,0.876512,0.826248,0.818012,0.867433,197.584573,128.592988,47.090345
66,2,Boruta,RandomForest,NaN,10,"2,5,7,8,9,14,15,17,18,19",8.567171,0.902012,0.883094,0.905798,0.874901,0.892715,98.914214,9333.067790,39.130342
67,2,Boruta,DecisionTree,NaN,10,"2,5,7,8,9,14,15,17,18,19",8.567171,0.885547,0.868194,0.891325,0.860693,0.874415,1.051541,26.239279,25.134053
68,2,Boruta,LogisticRegression,NaN,10,"2,5,7,8,9,14,15,17,18,19",8.567171,0.518940,0.481606,0.572757,0.476536,0.476265,30.914532,77.768638,25.137673
69,2,Boruta,GaussianNB,NaN,10,"2,5,7,8,9,14,15,17,18,19",8.567171,0.407890,0.340743,0.475229,0.344959,0.367717,0.312784,108.972775,25.132696
70,2,Boruta,HistGradientBoosting,NaN,10,"2,5,7,8,9,14,15,17,18,19",8.567171,0.904085,0.925242,0.854638,0.872318,0.894500,231.961644,5181.509357,31.741000
71,2,Boruta,MLP,NaN,10,"2,5,7,8,9,14,15,17,18,19",8.567171,0.884037,0.908696,0.839377,0.856445,0.872330,137.089942,228.084400,47.081946
72,3,GWO,RandomForest,10.0,10,"11,14,17,7,18,19,2,15,3,1",140.634687,0.897027,0.863643,0.902536,0.867972,0.886641,89.980536,9406.278842,39.722166
73,3,GWO,DecisionTree,10.0,10,"11,14,17,7,18,19,2,15,3,1",140.634687,0.887320,0.855171,0.894226,0.859714,0.875889,0.669042,38.124648,25.135923
74,3,GWO,LogisticRegression,10.0,10,"11,14,17,7,18,19,2,15,3,1",140.634687,0.628983,0.580219,0.670779,0.601436,0.594236,49.569345,91.783961,25.134899
75,3,GWO,GaussianNB,10.0,10,"11,14,17,7,18,19,2,15,3,1",140.634687,0.328656,0.324360,0.397776,0.313602,0.295104,0.278068,87.261669,25.129795
76,3,GWO,HistGradientBoosting,10.0,10,"11,14,17,7,18,19,2,15,3,1",140.634687,0.908902,0.888662,0.911605,0.887153,0.899906,223.997121,6270.366972,32.115555
77,3,GWO,MLP,10.0,10,"11,14,17,7,18,19,2,15,3,1",140.634687,0.885415,0.880945,0.874671,0.863445,0.873833,195.469863,104.169158,47.068604
78,3,BA,RandomForest,10.0,10,"1,2,7,14,21,5,19,16,13,18",171.932050,0.886781,0.855158,0.893849,0.859259,0.875365,91.823205,9929.501625,39.210517
79,3,BA,DecisionTree,10.0,10,"1,2,7,14,21,5,19,16,13,18",171.932050,0.873659,0.843278,0.882010,0.847684,0.860798,0.711690,33.771253,25.132982
80,3,BA,LogisticRegression,10.0,10,"1,2,7,14,21,5,19,16,13,18",171.932050,0.483685,0.457137,0.544108,0.456608,0.439006,27.591771,97.096320,25.138847
81,3,BA,GaussianNB,10.0,10,"1,2,7,14,21,5,19,16,13,18",171.932050,0.210584,0.275866,0.296307,0.216609,0.152406,0.296101,84.072079,25.128525
82,3,BA,HistGradientBoosting,10.0,10,"1,2,7,14,21,5,19,16,13,18",171.932050,0.897698,0.879754,0.902471,0.878012,0.887577,296.923296,5178.831783,32.359207
83,3,BA,MLP,10.0,10,"1,2,7,14,21,5,19,16,13,18",171.932050,0.878716,0.874916,0.868243,0.857366,0.866360,211.094073,219.218865,47.071058
84,3,LightGBM,RandomForest,10.0,10,"9,19,8,14,7,15,0,18,17,12",128.078672,0.896524,0.822971,0.860697,0.826312,0.886323,76.248971,8346.347044,39.104911
85,3,LightGBM,DecisionTree,10.0,10,"9,19,8,14,7,15,0,18,17,12",128.078672,0.880382,0.807959,0.845926,0.811922,0.868372,1.070115,28.621762,25.137733
86,3,LightGBM,LogisticRegression,10.0,10,"9,19,8,14,7,15,0,18,17,12",128.078672,0.576268,0.513969,0.586266,0.524519,0.535465,37.595814,178.145325,25.134149
87,3,LightGBM,GaussianNB,10.0,10,"9,19,8,14,7,15,0,18,17,12",128.078672,0.333929,0.244483,0.375978,0.269083,0.296821,0.256526,82.143267,25.130030
88,3,LightGBM,HistGradientBoosting,10.0,10,"9,19,8,14,7,15,0,18,17,12",128.078672,0.902336,0.877954,0.860582,0.836730,0.892740,181.476147,4351.601201,31.835812
89,3,LightGBM,MLP,10.0,10,"9,19,8,14,7,15,0,18,17,12",128.078672,0.877674,0.874434,0.825151,0.817089,0.865362,168.418217,174.338886,47.069436
90,3,Boruta,RandomForest,NaN,10,"2,5,7,8,9,14,15,17,18,19",10.764830,0.901665,0.882826,0.905491,0.874579,0.892330,81.390596,7405.503430,39.612365
91,3,Boruta,DecisionTree,NaN,10,"2,5,7,8,9,14,15,17,18,19",10.764830,0.885787,0.868371,0.891418,0.860783,0.874678,1.308137,43.811762,25.134611
92,3,Boruta,LogisticRegression,NaN,10,"2,5,7,8,9,14,15,17,18,19",10.764830,0.519515,0.481109,0.573163,0.477219,0.476794,24.869119,140.108982,25.136246
93,3,Boruta,GaussianNB,NaN,10,"2,5,7,8,9,14,15,17,18,19",10.764830,0.407722,0.339025,0.474909,0.344368,0.367524,0.290060,95.730911,25.130134
94,3,Boruta,HistGradientBoosting,NaN,10,"2,5,7,8,9,14,15,17,18,19",10.764830,0.906925,0.923572,0.859596,0.874199,0.897635,112.788158,2112.364923,32.158502
95,3,Boruta,MLP,NaN,10,"2,5,7,8,9,14,15,17,18,19",10.764830,0.885247,0.910435,0.840241,0.857397,0.873716,183.940595,182.835783,47.072447
96,4,GWO,RandomForest,10.0,10,"5,11,7,2,15,14,1,19,8,18",154.844487,0.895984,0.863412,0.902539,0.867630,0.885592,79.712410,10464.032477,39.671600
97,4,GWO,DecisionTree,10.0,10,"5,11,7,2,15,14,1,19,8,18",154.844487,0.877230,0.846194,0.886275,0.851386,0.864751,0.937709,29.114101,25.136262
98,4,GWO,LogisticRegression,10.0,10,"5,11,7,2,15,14,1,19,8,18",154.844487,0.562212,0.538946,0.614531,0.543615,0.520569,33.465269,104.607548,25.135175
99,4,GWO,GaussianNB,10.0,10,"5,11,7,2,15,14,1,19,8,18",154.844487,0.218001,0.273547,0.301908,0.221788,0.161116,0.257544,79.050027,25.128654
100,4,GWO,HistGradientBoosting,10.0,10,"5,11,7,2,15,14,1,19,8,18",154.844487,0.901185,0.882265,0.905347,0.880956,0.891377,106.680747,1476.597368,31.493771
101,4,GWO,MLP,10.0,10,"5,11,7,2,15,14,1,19,8,18",154.844487,0.883594,0.880420,0.872783,0.862481,0.871812,186.818727,214.790548,47.070419
102,4,BA,RandomForest,10.0,10,"1,2,6,4,7,8,9,19,18,20",205.178591,0.852425,0.822798,0.861051,0.826929,0.837466,85.011197,10767.561597,39.040912
103,4,BA,DecisionTree,10.0,10,"1,2,6,4,7,8,9,19,18,20",205.178591,0.831406,0.802748,0.842851,0.808222,0.814140,1.696562,30.606190,25.134157
104,4,BA,LogisticRegression,10.0,10,"1,2,6,4,7,8,9,19,18,20",205.178591,0.283586,0.237408,0.368260,0.262546,0.218552,27.516318,79.299065,25.135583
105,4,BA,GaussianNB,10.0,10,"1,2,6,4,7,8,9,19,18,20",205.178591,0.201105,0.288144,0.287531,0.218051,0.139427,0.250821,77.733962,25.132815
106,4,BA,HistGradientBoosting,10.0,10,"1,2,6,4,7,8,9,19,18,20",205.178591,0.854462,0.838997,0.860870,0.837447,0.839588,213.260981,7213.561267,31.576341
107,4,BA,MLP,10.0,10,"1,2,6,4,7,8,9,19,18,20",205.178591,0.806948,0.800962,0.817055,0.794490,0.787479,193.808733,162.359049,47.070104
108,4,LightGBM,RandomForest,10.0,10,"9,19,8,14,7,15,0,18,17,12",113.855563,0.897890,0.826144,0.861517,0.829002,0.887773,83.218890,10199.080460,39.048967
109,4,LightGBM,DecisionTree,10.0,10,"9,19,8,14,7,15,0,18,17,12",113.855563,0.881089,0.826105,0.845065,0.814595,0.869163,1.100927,27.543124,25.133859
110,4,LightGBM,LogisticRegression,10.0,10,"9,19,8,14,7,15,0,18,17,12",113.855563,0.577107,0.514463,0.586950,0.524935,0.536431,39.859599,66.762742,25.136810
111,4,LightGBM,GaussianNB,10.0,10,"9,19,8,14,7,15,0,18,17,12",113.855563,0.332419,0.243747,0.374638,0.268061,0.295009,0.271153,86.991632,25.131658
112,4,LightGBM,HistGradientBoosting,10.0,10,"9,19,8,14,7,15,0,18,17,12",113.855563,0.902647,0.882389,0.862849,0.839807,0.893079,282.134043,1050.366780,31.701666
113,4,LightGBM,MLP,10.0,10,"9,19,8,14,7,15,0,18,17,12",113.855563,0.877614,0.860778,0.839526,0.815695,0.865632,181.048692,108.360914,47.070374
114,4,Boruta,RandomForest,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.250404,0.901425,0.882620,0.905132,0.874317,0.892066,94.810839,10567.128726,39.103920
115,4,Boruta,DecisionTree,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.250404,0.885247,0.867928,0.890932,0.860351,0.874083,1.172108,32.762993,25.139212
116,4,Boruta,LogisticRegression,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.250404,0.518281,0.480681,0.572450,0.475832,0.475570,25.442930,57.160319,25.136138
117,4,Boruta,GaussianNB,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.250404,0.407566,0.340021,0.474817,0.344468,0.367343,0.260550,88.661416,25.129818
118,4,Boruta,HistGradientBoosting,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.250404,0.907249,0.928050,0.859900,0.876702,0.897983,247.097792,7442.977833,31.632654
119,4,Boruta,MLP,NaN,10,"2,5,7,8,9,14,15,17,18,19",9.250404,0.886865,0.911128,0.842422,0.858692,0.875632,163.560290,125.005825,47.067966
120,5,GWO,RandomForest,10.0,10,"7,2,18,17,1,19,10,5,14,9",164.252366,0.902216,0.855927,0.909401,0.864427,0.892556,83.487181,8585.607317,39.300222
121,5,GWO,DecisionTree,10.0,10,"7,2,18,17,1,19,10,5,14,9",164.252366,0.887836,0.842778,0.896743,0.851993,0.876564,0.971426,28.927818,25.131989
122,5,GWO,LogisticRegression,10.0,10,"7,2,18,17,1,19,10,5,14,9",164.252366,0.547676,0.525179,0.604616,0.520353,0.506927,34.649526,71.754056,25.136659
123,5,GWO,GaussianNB,10.0,10,"7,2,18,17,1,19,10,5,14,9",164.252366,0.295929,0.312748,0.369819,0.291003,0.250047,0.278346,81.648624,25.131468
124,5,GWO,HistGradientBoosting,10.0,10,"7,2,18,17,1,19,10,5,14,9",164.252366,0.907716,0.883850,0.908654,0.883591,0.898561,231.435054,2517.986539,31.874557
125,5,GWO,MLP,10.0,10,"7,2,18,17,1,19,10,5,14,9",164.252366,0.881592,0.877941,0.871276,0.859999,0.869774,232.807753,109.873828,47.069703
126,5,BA,RandomForest,10.0,10,"2,6,5,4,7,13,11,8,14,12",205.587397,0.803209,0.806947,0.815201,0.786624,0.785228,95.367049,8252.866770,39.502136
127,5,BA,DecisionTree,10.0,10,"2,6,5,4,7,13,11,8,14,12",205.587397,0.797337,0.792358,0.810721,0.780690,0.777580,0.999001,32.718623,25.137016
128,5,BA,LogisticRegression,10.0,10,"2,6,5,4,7,13,11,8,14,12",205.587397,0.419262,0.450774,0.489168,0.410311,0.365975,25.765490,89.976068,25.135389
129,5,BA,GaussianNB,10.0,10,"2,6,5,4,7,13,11,8,14,12",205.587397,0.319285,0.335600,0.389498,0.300501,0.271357,0.306414,82.984205,25.129587
130,5,BA,HistGradientBoosting,10.0,10,"2,6,5,4,7,13,11,8,14,12",205.587397,0.801280,0.783782,0.737687,0.744390,0.784833,232.923926,2413.899077,31.834483
131,5,BA,MLP,10.0,10,"2,6,5,4,7,13,11,8,14,12",205.587397,0.766408,0.750573,0.705316,0.713699,0.745167,303.178182,171.102954,47.071096
132,5,LightGBM,RandomForest,10.0,10,"9,19,8,14,7,15,0,18,17,12",140.478651,0.898069,0.826427,0.861684,0.829225,0.887973,95.773039,9562.803862,39.116199
133,5,LightGBM,DecisionTree,10.0,10,"9,19,8,14,7,15,0,18,17,12",140.478651,0.882072,0.811859,0.847510,0.815364,0.870174,1.077870,27.676410,25.136179
134,5,LightGBM,LogisticRegression,10.0,10,"9,19,8,14,7,15,0,18,17,12",140.478651,0.576268,0.514102,0.586282,0.524444,0.535491,36.061688,65.793960,25.138714
135,5,LightGBM,GaussianNB,10.0,10,"9,19,8,14,7,15,0,18,17,12",140.478651,0.337703,0.242254,0.379655,0.269395,0.299842,0.293172,99.622899,25.129854

Rows: 240

,Algorithm,Classifier,Accuracy,Precision,Recall,F1_macro,MCC,N_Selected,fs_time_s,train_time_s,inference_time_ms,peak_mem_mb
0,GWO,HistGradientBoosting,0.906596,0.894120,0.896620,0.880769,0.897344,10.0,145.713449,218.364505,3068.601717,31.914554
1,Boruta,HistGradientBoosting,0.906479,0.926405,0.858542,0.875071,0.897147,9.6,8.746015,218.603493,5141.179606,31.286489
2,Boruta,RandomForest,0.900429,0.881602,0.904416,0.873506,0.890956,9.6,8.746015,86.508932,8924.850808,39.110456
3,GWO,RandomForest,0.897434,0.862371,0.900914,0.864774,0.887245,10.0,145.713449,87.933528,9308.927211,39.444783
4,Boruta,DecisionTree,0.885370,0.867964,0.891134,0.860484,0.874217,9.6,8.746015,1.059072,29.660148,24.223118
5,Boruta,MLP,0.886428,0.910627,0.841907,0.858498,0.875043,9.6,8.746015,190.705464,202.314121,46.898514
6,GWO,MLP,0.884424,0.891326,0.857879,0.858363,0.872747,10.0,145.713449,185.892968,187.472076,47.079790
7,GWO,DecisionTree,0.884637,0.850973,0.889785,0.853773,0.873048,10.0,145.713449,0.915479,39.436614,25.134440
8,BA,HistGradientBoosting,0.868912,0.860114,0.850433,0.836850,0.856344,10.0,182.031650,205.218270,3702.343644,31.874806
9,LightGBM,HistGradientBoosting,0.900912,0.877017,0.860388,0.836775,0.891164,10.0,114.733429,226.095444,4789.415971,31.942298
10,BA,RandomForest,0.865542,0.830796,0.866915,0.832101,0.852319,10.0,182.031650,90.000031,10114.275431,39.807316
11,LightGBM,RandomForest,0.897521,0.830077,0.860663,0.828431,0.887395,10.0,114.733429,87.169914,8992.984867,39.479488
12,BA,DecisionTree,0.849023,0.814655,0.852506,0.817526,0.833879,10.0,182.031650,0.980047,30.918419,25.135264
13,LightGBM,MLP,0.877510,0.874266,0.824110,0.815806,0.865219,10.0,114.733429,163.162842,125.403244,47.070994
14,LightGBM,DecisionTree,0.881634,0.816982,0.846277,0.814544,0.869723,10.0,114.733429,1.116777,29.917534,25.135479
15,BA,MLP,0.837637,0.845518,0.812320,0.809373,0.821756,10.0,182.031650,204.419106,141.536419,47.076612
16,GWO,LogisticRegression,0.588467,0.557321,0.634215,0.561587,0.550483,10.0,145.713449,39.324166,76.739022,25.136621
17,LightGBM,LogisticRegression,0.576447,0.514538,0.586455,0.524669,0.535682,10.0,114.733429,39.446844,74.034147,25.135820
18,Boruta,LogisticRegression,0.519231,0.481137,0.572776,0.476894,0.476538,9.6,8.746015,26.980971,86.775896,24.264647
19,BA,LogisticRegression,0.464339,0.440551,0.519720,0.436126,0.415974,10.0,182.031650,31.421283,85.362771,25.137693
20,Boruta,GaussianNB,0.409617,0.349272,0.476550,0.348131,0.369539,9.6,8.746015,0.284978,94.045555,24.217820
21,GWO,GaussianNB,0.308994,0.311852,0.380319,0.288460,0.269948,10.0,145.713449,0.279819,84.824871,25.130383
22,LightGBM,GaussianNB,0.337087,0.243849,0.379012,0.270112,0.299301,10.0,114.733429,0.282074,92.525154,25.130445
23,BA,GaussianNB,0.238094,0.274856,0.312725,0.225077,0.189864,10.0,182.031650,0.294250,81.490792,25.130653

Deployment-oriented summary (lower downstream cost is better)

,Algorithm,Classifier,N_Selected,train_time_s,inference_time_ms,peak_mem_mb
0,Boruta,GaussianNB,9.6,0.284978,94.045555,24.217820
1,Boruta,DecisionTree,9.6,1.059072,29.660148,24.223118
2,Boruta,LogisticRegression,9.6,26.980971,86.775896,24.264647
3,Boruta,HistGradientBoosting,9.6,218.603493,5141.179606,31.286489
4,Boruta,RandomForest,9.6,86.508932,8924.850808,39.110456
5,Boruta,MLP,9.6,190.705464,202.314121,46.898514
6,GWO,GaussianNB,10.0,0.279819,84.824871,25.130383
7,LightGBM,GaussianNB,10.0,0.282074,92.525154,25.130445
8,BA,GaussianNB,10.0,0.294250,81.490792,25.130653
9,GWO,DecisionTree,10.0,0.915479,39.436614,25.134440
10,BA,DecisionTree,10.0,0.980047,30.918419,25.135264
11,LightGBM,DecisionTree,10.0,1.116777,29.917534,25.135479
12,LightGBM,LogisticRegression,10.0,39.446844,74.034147,25.135820
13,GWO,LogisticRegression,10.0,39.324166,76.739022,25.136621
14,BA,LogisticRegression,10.0,31.421283,85.362771,25.137693
15,BA,HistGradientBoosting,10.0,205.218270,3702.343644,31.874806
16,GWO,HistGradientBoosting,10.0,218.364505,3068.601717,31.914554
17,LightGBM,HistGradientBoosting,10.0,226.095444,4789.415971,31.942298
18,GWO,RandomForest,10.0,87.933528,9308.927211,39.444783
19,LightGBM,RandomForest,10.0,87.169914,8992.984867,39.479488
20,BA,RandomForest,10.0,90.000031,10114.275431,39.807316
21,LightGBM,MLP,10.0,163.162842,125.403244,47.070994
22,BA,MLP,10.0,204.419106,141.536419,47.076612
23,GWO,MLP,10.0,185.892968,187.472076,47.079790

,Method,Classifier,accuracy,precision_macro,recall_macro,f1_macro,mcc,n_selected,fs_time_s,train_time_s,inference_time_ms,peak_mem_mb
0,BA,DecisionTree,0.8490 +- 0.0229,0.8147 +- 0.0253,0.8525 +- 0.0248,0.8175 +- 0.0244,0.8339 +- 0.0251,10.0000 +- 0.0000,182.032 +- 20.630,0.980 +- 0.320,30.918 +- 2.051,25.135 +- 0.002
1,Boruta,DecisionTree,0.8854 +- 0.0010,0.8680 +- 0.0009,0.8911 +- 0.0009,0.8605 +- 0.0009,0.8742 +- 0.0011,9.6000 +- 0.6992,8.746 +- 1.408,1.059 +- 0.180,29.660 +- 5.419,24.223 +- 1.595
2,GWO,DecisionTree,0.8846 +- 0.0041,0.8510 +- 0.0116,0.8898 +- 0.0088,0.8538 +- 0.0077,0.8730 +- 0.0046,10.0000 +- 0.0000,145.713 +- 17.088,0.915 +- 0.348,39.437 +- 23.458,25.134 +- 0.001
3,LightGBM,DecisionTree,0.8816 +- 0.0012,0.8170 +- 0.0081,0.8463 +- 0.0017,0.8145 +- 0.0016,0.8697 +- 0.0013,10.0000 +- 0.0000,114.733 +- 26.985,1.117 +- 0.067,29.918 +- 3.751,25.135 +- 0.003
4,BA,GaussianNB,0.2381 +- 0.0794,0.2749 +- 0.0850,0.3127 +- 0.0761,0.2251 +- 0.0777,0.1899 +- 0.0854,10.0000 +- 0.0000,182.032 +- 20.630,0.294 +- 0.041,81.491 +- 4.797,25.131 +- 0.003
5,Boruta,GaussianNB,0.4096 +- 0.0058,0.3493 +- 0.0294,0.4766 +- 0.0050,0.3481 +- 0.0110,0.3695 +- 0.0062,9.6000 +- 0.6992,8.746 +- 1.408,0.285 +- 0.037,94.046 +- 14.409,24.218 +- 1.595
6,GWO,GaussianNB,0.3090 +- 0.0473,0.3119 +- 0.0232,0.3803 +- 0.0434,0.2885 +- 0.0324,0.2699 +- 0.0494,10.0000 +- 0.0000,145.713 +- 17.088,0.280 +- 0.031,84.825 +- 5.755,25.130 +- 0.001
7,LightGBM,GaussianNB,0.3371 +- 0.0052,0.2438 +- 0.0025,0.3790 +- 0.0046,0.2701 +- 0.0033,0.2993 +- 0.0046,10.0000 +- 0.0000,114.733 +- 26.985,0.282 +- 0.022,92.525 +- 15.547,25.130 +- 0.002
8,BA,HistGradientBoosting,0.8689 +- 0.0287,0.8601 +- 0.0386,0.8504 +- 0.0452,0.8368 +- 0.0379,0.8563 +- 0.0307,10.0000 +- 0.0000,182.032 +- 20.630,205.218 +- 63.941,3702.344 +- 1863.182,31.875 +- 0.366
9,Boruta,HistGradientBoosting,0.9065 +- 0.0011,0.9264 +- 0.0023,0.8585 +- 0.0022,0.8751 +- 0.0020,0.8971 +- 0.0012,9.6000 +- 0.6992,8.746 +- 1.408,218.603 +- 61.729,5141.180 +- 2406.883,31.286 +- 0.890
10,GWO,HistGradientBoosting,0.9066 +- 0.0033,0.8941 +- 0.0181,0.8966 +- 0.0223,0.8808 +- 0.0076,0.8973 +- 0.0037,10.0000 +- 0.0000,145.713 +- 17.088,218.365 +- 52.897,3068.602 +- 1479.607,31.915 +- 0.261
11,LightGBM,HistGradientBoosting,0.9009 +- 0.0028,0.8770 +- 0.0065,0.8604 +- 0.0027,0.8368 +- 0.0033,0.8912 +- 0.0031,10.0000 +- 0.0000,114.733 +- 26.985,226.095 +- 68.545,4789.416 +- 2450.545,31.942 +- 0.219
12,BA,LogisticRegression,0.4643 +- 0.0973,0.4406 +- 0.0911,0.5197 +- 0.0846,0.4361 +- 0.0935,0.4160 +- 0.1052,10.0000 +- 0.0000,182.032 +- 20.630,31.421 +- 7.774,85.363 +- 25.466,25.138 +- 0.003
13,Boruta,LogisticRegression,0.5192 +- 0.0077,0.4811 +- 0.0141,0.5728 +- 0.0067,0.4769 +- 0.0085,0.4765 +- 0.0084,9.6000 +- 0.6992,8.746 +- 1.408,26.981 +- 2.601,86.776 +- 45.437,24.265 +- 1.493
14,GWO,LogisticRegression,0.5885 +- 0.0295,0.5573 +- 0.0290,0.6342 +- 0.0268,0.5616 +- 0.0299,0.5505 +- 0.0322,10.0000 +- 0.0000,145.713 +- 17.088,39.324 +- 9.727,76.739 +- 21.656,25.137 +- 0.002
15,LightGBM,LogisticRegression,0.5764 +- 0.0007,0.5145 +- 0.0006,0.5865 +- 0.0006,0.5247 +- 0.0006,0.5357 +- 0.0008,10.0000 +- 0.0000,114.733 +- 26.985,39.447 +- 4.030,74.034 +- 38.750,25.136 +- 0.001
16,BA,MLP,0.8376 +- 0.0360,0.8455 +- 0.0442,0.8123 +- 0.0491,0.8094 +- 0.0428,0.8218 +- 0.0390,10.0000 +- 0.0000,182.032 +- 20.630,204.419 +- 52.981,141.536 +- 41.424,47.077 +- 0.020
17,Boruta,MLP,0.8864 +- 0.0022,0.9106 +- 0.0019,0.8419 +- 0.0020,0.8585 +- 0.0020,0.8750 +- 0.0025,9.6000 +- 0.6992,8.746 +- 1.408,190.705 +- 41.864,202.314 +- 62.373,46.899 +- 0.301
18,GWO,MLP,0.8844 +- 0.0053,0.8913 +- 0.0136,0.8579 +- 0.0211,0.8584 +- 0.0091,0.8727 +- 0.0058,10.0000 +- 0.0000,145.713 +- 17.088,185.893 +- 35.028,187.472 +- 64.584,47.080 +- 0.030
19,LightGBM,MLP,0.8775 +- 0.0009,0.8743 +- 0.0116,0.8241 +- 0.0137,0.8158 +- 0.0020,0.8652 +- 0.0010,10.0000 +- 0.0000,114.733 +- 26.985,163.163 +- 23.358,125.403 +- 27.628,47.071 +- 0.007
20,BA,RandomForest,0.8655 +- 0.0261,0.8308 +- 0.0253,0.8669 +- 0.0272,0.8321 +- 0.0262,0.8523 +- 0.0283,10.0000 +- 0.0000,182.032 +- 20.630,90.000 +- 5.812,10114.275 +- 1693.843,39.807 +- 0.900
21,Boruta,RandomForest,0.9004 +- 0.0019,0.8816 +- 0.0019,0.9044 +- 0.0016,0.8735 +- 0.0017,0.8910 +- 0.0021,9.6000 +- 0.6992,8.746 +- 1.408,86.509 +- 8.280,8924.851 +- 1439.829,39.110 +- 0.597
22,GWO,RandomForest,0.8974 +- 0.0040,0.8624 +- 0.0117,0.9009 +- 0.0095,0.8648 +- 0.0083,0.8872 +- 0.0044,10.0000 +- 0.0000,145.713 +- 17.088,87.934 +- 7.161,9308.927 +- 764.696,39.445 +- 0.315
23,LightGBM,RandomForest,0.8975 +- 0.0008,0.8301 +- 0.0076,0.8607 +- 0.0013,0.8284 +- 0.0011,0.8874 +- 0.0008,10.0000 +- 0.0000,114.733 +- 26.985,87.170 +- 7.130,8992.985 +- 1204.681,39.479 +- 0.519

## Statistical Significance and Pairwise Tests

In [5]:
try:
    from scipy.stats import friedmanchisquare, wilcoxon
    _HAS_SCIPY = True
except Exception:
    _HAS_SCIPY = False

def _prepare_pivot(df: pd.DataFrame, value_col: str, ordered_methods):
    pivot = df.pivot_table(index='seed', columns='method', values=value_col, aggfunc='mean')
    pivot = pivot.dropna(axis=1, how='all')
    ordered = [m for m in list(ordered_methods) if m in pivot.columns]
    pivot = pivot[ordered]
    pivot = pivot.dropna(axis=0, how='any')
    return pivot

def _holm_adjust(pvals):
    if len(pvals) == 0:
        return []
    order = np.argsort(pvals)
    ranked = np.asarray(pvals, dtype=float)[order]
    m = len(ranked)
    adj = np.empty(m, dtype=float)
    running = 0.0
    for i, p in enumerate(ranked):
        value = min(1.0, (m - i) * float(p))
        running = max(running, value)
        adj[i] = running
    restored = np.empty(m, dtype=float)
    restored[order] = adj
    return restored.tolist()

def _safe_wilcoxon(a, b):
    if (not _HAS_SCIPY) or (len(a) < 2):
        return None
    if np.allclose(np.asarray(a) - np.asarray(b), 0.0):
        return 1.0
    return float(wilcoxon(a, b, zero_method='wilcox').pvalue)

def global_significance_for_classifier(df: pd.DataFrame, clf_name: str, methods_list, metric: str = 'f1_macro'):
    sub = df[df['classifier'].astype(str) == str(clf_name)].copy()
    if sub.empty:
        return {'Classifier': str(clf_name), 'metric': metric, 'test': None, 'p_value': None, 'reason': 'no rows'}
    pivot = _prepare_pivot(sub, metric, methods_list)
    methods_avail = list(pivot.columns)
    n_runs = int(pivot.shape[0])
    if len(methods_avail) < 2 or n_runs < 2:
        return {'Classifier': str(clf_name), 'metric': metric, 'test': None, 'p_value': None, 'methods': methods_avail, 'n_runs': n_runs, 'reason': 'need >=2 methods with complete runs'}
    if not _HAS_SCIPY:
        return {'Classifier': str(clf_name), 'metric': metric, 'test': None, 'p_value': None, 'methods': methods_avail, 'n_runs': n_runs, 'reason': 'scipy not available'}
    if len(methods_avail) == 2:
        a, b = methods_avail
        p = _safe_wilcoxon(pivot[a].values, pivot[b].values)
        return {'Classifier': str(clf_name), 'metric': metric, 'test': 'Wilcoxon', 'p_value': p, 'methods': methods_avail, 'n_runs': n_runs}
    samples = [pivot[m].values for m in methods_avail]
    _, p = friedmanchisquare(*samples)
    return {'Classifier': str(clf_name), 'metric': metric, 'test': 'Friedman', 'p_value': float(p), 'methods': methods_avail, 'n_runs': n_runs}

def pairwise_vs_reference_for_classifier(df: pd.DataFrame, clf_name: str, methods_list, reference: str = 'GWO', metric: str = 'f1_macro'):
    sub = df[df['classifier'].astype(str) == str(clf_name)].copy()
    if sub.empty:
        return []
    pivot = _prepare_pivot(sub, metric, methods_list)
    if reference not in pivot.columns:
        return []
    rows = []
    pvals = []
    valid_idx = []
    for method in pivot.columns:
        if str(method) == str(reference):
            continue
        pair = pivot[[reference, method]].dropna(axis=0, how='any')
        n_runs = int(pair.shape[0])
        row = {
            'Classifier': str(clf_name),
            'metric': metric,
            'reference': str(reference),
            'comparison': str(method),
            'n_runs': n_runs,
            'mean_ref': float(pair[reference].mean()) if n_runs else np.nan,
            'mean_cmp': float(pair[method].mean()) if n_runs else np.nan,
            'wins_ref': int((pair[reference] > pair[method]).sum()) if n_runs else 0,
            'ties': int((pair[reference] == pair[method]).sum()) if n_runs else 0,
            'wins_cmp': int((pair[reference] < pair[method]).sum()) if n_runs else 0,
            'test': 'Wilcoxon',
            'p_value': None,
            'p_holm': None,
            'better_by_mean': str(reference) if (n_runs and pair[reference].mean() >= pair[method].mean()) else str(method)
        }
        if _HAS_SCIPY and n_runs >= 2:
            p = _safe_wilcoxon(pair[reference].values, pair[method].values)
            row['p_value'] = p
            if p is not None:
                valid_idx.append(len(rows))
                pvals.append(p)
        else:
            row['test'] = None
        rows.append(row)
    adj = _holm_adjust(pvals)
    for idx, p_adj in zip(valid_idx, adj):
        rows[idx]['p_holm'] = float(p_adj)
    return rows

def global_significance_for_fs(fs_df_local: pd.DataFrame, methods_list, metric: str = 'fs_time_s'):
    pivot = _prepare_pivot(fs_df_local.copy(), metric, methods_list)
    methods_avail = list(pivot.columns)
    n_runs = int(pivot.shape[0])
    if len(methods_avail) < 2 or n_runs < 2:
        return {'metric': metric, 'test': None, 'p_value': None, 'methods': methods_avail, 'n_runs': n_runs, 'reason': 'need >=2 methods with complete runs'}
    if not _HAS_SCIPY:
        return {'metric': metric, 'test': None, 'p_value': None, 'methods': methods_avail, 'n_runs': n_runs, 'reason': 'scipy not available'}
    if len(methods_avail) == 2:
        a, b = methods_avail
        p = _safe_wilcoxon(pivot[a].values, pivot[b].values)
        return {'metric': metric, 'test': 'Wilcoxon', 'p_value': p, 'methods': methods_avail, 'n_runs': n_runs}
    samples = [pivot[m].values for m in methods_avail]
    _, p = friedmanchisquare(*samples)
    return {'metric': metric, 'test': 'Friedman', 'p_value': float(p), 'methods': methods_avail, 'n_runs': n_runs}

def pairwise_vs_reference_for_fs(fs_df_local: pd.DataFrame, methods_list, reference: str = 'GWO', metric: str = 'fs_time_s'):
    pivot = _prepare_pivot(fs_df_local.copy(), metric, methods_list)
    if reference not in pivot.columns:
        return []
    rows = []
    pvals = []
    valid_idx = []
    for method in pivot.columns:
        if str(method) == str(reference):
            continue
        pair = pivot[[reference, method]].dropna(axis=0, how='any')
        n_runs = int(pair.shape[0])
        mean_ref = float(pair[reference].mean()) if n_runs else np.nan
        mean_cmp = float(pair[method].mean()) if n_runs else np.nan
        row = {
            'metric': metric,
            'reference': str(reference),
            'comparison': str(method),
            'n_runs': n_runs,
            'mean_ref': mean_ref,
            'mean_cmp': mean_cmp,
            'wins_ref': int((pair[reference] < pair[method]).sum()) if n_runs else 0,
            'ties': int((pair[reference] == pair[method]).sum()) if n_runs else 0,
            'wins_cmp': int((pair[reference] > pair[method]).sum()) if n_runs else 0,
            'test': 'Wilcoxon',
            'p_value': None,
            'p_holm': None,
            'faster_by_mean': str(reference) if (n_runs and mean_ref <= mean_cmp) else str(method)
        }
        if _HAS_SCIPY and n_runs >= 2:
            p = _safe_wilcoxon(pair[reference].values, pair[method].values)
            row['p_value'] = p
            if p is not None:
                valid_idx.append(len(rows))
                pvals.append(p)
        else:
            row['test'] = None
        rows.append(row)
    adj = _holm_adjust(pvals)
    for idx, p_adj in zip(valid_idx, adj):
        rows[idx]['p_holm'] = float(p_adj)
    return rows

print('Global significance for performance (f1_macro)')
sig_rows = []
for clf_name in sorted(raw_df['classifier'].astype(str).unique()):
    sig_rows.append(global_significance_for_classifier(raw_df, clf_name, methods, metric='f1_macro'))
sig_df = pd.DataFrame(sig_rows)
display(sig_df)

print('Pairwise post-hoc vs GWO for performance (f1_macro)')
pairwise_rows = []
for clf_name in sorted(raw_df['classifier'].astype(str).unique()):
    pairwise_rows.extend(pairwise_vs_reference_for_classifier(raw_df, clf_name, methods, reference='GWO', metric='f1_macro'))
pairwise_df = pd.DataFrame(pairwise_rows)
display(pairwise_df)

print('Global significance for feature-selection time (fs_time_s)')
sig_df_time = pd.DataFrame([global_significance_for_fs(fs_df, methods, metric='fs_time_s')])
display(sig_df_time)

print('Pairwise post-hoc vs GWO for feature-selection time (fs_time_s)')
pairwise_time_df = pd.DataFrame(pairwise_vs_reference_for_fs(fs_df, methods, reference='GWO', metric='fs_time_s'))
display(pairwise_time_df)

print('Global significance for number of selected features (n_selected)')
sig_df_n_selected = pd.DataFrame([global_significance_for_fs(fs_df, methods, metric='n_selected')])
display(sig_df_n_selected)

print('Pairwise post-hoc vs GWO for number of selected features (n_selected)')
pairwise_n_selected_df = pd.DataFrame(pairwise_vs_reference_for_fs(fs_df, methods, reference='GWO', metric='n_selected'))
display(pairwise_n_selected_df)

print('Stability summary (mean pairwise Jaccard across runs)')
display(stability_df)

Global significance for performance (f1_macro)

,Classifier,metric,test,p_value,methods,n_runs
0,DecisionTree,f1_macro,Friedman,0.000020,"[GWO, BA, LightGBM, Boruta]",10
1,GaussianNB,f1_macro,Friedman,0.000295,"[GWO, BA, LightGBM, Boruta]",10
2,HistGradientBoosting,f1_macro,Friedman,0.000033,"[GWO, BA, LightGBM, Boruta]",10
3,LogisticRegression,f1_macro,Friedman,0.000187,"[GWO, BA, LightGBM, Boruta]",10
4,MLP,f1_macro,Friedman,0.000024,"[GWO, BA, LightGBM, Boruta]",10
5,RandomForest,f1_macro,Friedman,0.000050,"[GWO, BA, LightGBM, Boruta]",10

Pairwise post-hoc vs GWO for performance (f1_macro)

,Classifier,metric,reference,comparison,n_runs,mean_ref,mean_cmp,wins_ref,ties,wins_cmp,test,p_value,p_holm,better_by_mean
0,DecisionTree,f1_macro,GWO,BA,10,0.853773,0.817526,10,0,0,Wilcoxon,0.001953,0.005859,GWO
1,DecisionTree,f1_macro,GWO,LightGBM,10,0.853773,0.814544,10,0,0,Wilcoxon,0.001953,0.005859,GWO
2,DecisionTree,f1_macro,GWO,Boruta,10,0.853773,0.860484,3,0,7,Wilcoxon,0.048828,0.048828,Boruta
3,GaussianNB,f1_macro,GWO,BA,10,0.288460,0.225077,8,0,2,Wilcoxon,0.064453,0.128906,GWO
4,GaussianNB,f1_macro,GWO,LightGBM,10,0.288460,0.270112,8,0,2,Wilcoxon,0.105469,0.128906,GWO
5,GaussianNB,f1_macro,GWO,Boruta,10,0.288460,0.348131,0,0,10,Wilcoxon,0.001953,0.005859,Boruta
6,HistGradientBoosting,f1_macro,GWO,BA,10,0.880769,0.836850,10,0,0,Wilcoxon,0.001953,0.005859,GWO
7,HistGradientBoosting,f1_macro,GWO,LightGBM,10,0.880769,0.836775,10,0,0,Wilcoxon,0.001953,0.005859,GWO
8,HistGradientBoosting,f1_macro,GWO,Boruta,10,0.880769,0.875071,8,0,2,Wilcoxon,0.037109,0.037109,GWO
9,LogisticRegression,f1_macro,GWO,BA,10,0.561587,0.436126,9,0,1,Wilcoxon,0.003906,0.007812,GWO
10,LogisticRegression,f1_macro,GWO,LightGBM,10,0.561587,0.524669,9,0,1,Wilcoxon,0.003906,0.007812,GWO
11,LogisticRegression,f1_macro,GWO,Boruta,10,0.561587,0.476894,10,0,0,Wilcoxon,0.001953,0.005859,GWO
12,MLP,f1_macro,GWO,BA,10,0.858363,0.809373,10,0,0,Wilcoxon,0.001953,0.005859,GWO
13,MLP,f1_macro,GWO,LightGBM,10,0.858363,0.815806,10,0,0,Wilcoxon,0.001953,0.005859,GWO
14,MLP,f1_macro,GWO,Boruta,10,0.858363,0.858498,6,0,4,Wilcoxon,0.769531,0.769531,Boruta
15,RandomForest,f1_macro,GWO,BA,10,0.864774,0.832101,8,0,2,Wilcoxon,0.009766,0.011719,GWO
16,RandomForest,f1_macro,GWO,LightGBM,10,0.864774,0.828431,10,0,0,Wilcoxon,0.001953,0.005859,GWO
17,RandomForest,f1_macro,GWO,Boruta,10,0.864774,0.873506,1,0,9,Wilcoxon,0.005859,0.011719,Boruta

Global significance for feature-selection time (fs_time_s)

      metric      test   p_value                      methods  n_runs
0  fs_time_s  Friedman  0.000007  [GWO, BA, LightGBM, Boruta]      10

Pairwise post-hoc vs GWO for feature-selection time (fs_time_s)

,metric,reference,comparison,n_runs,mean_ref,mean_cmp,wins_ref,ties,wins_cmp,test,p_value,p_holm,faster_by_mean
0,fs_time_s,GWO,BA,10,145.713449,182.031650,9,0,1,Wilcoxon,0.003906,0.007812,GWO
1,fs_time_s,GWO,LightGBM,10,145.713449,114.733429,2,0,8,Wilcoxon,0.027344,0.027344,LightGBM
2,fs_time_s,GWO,Boruta,10,145.713449,8.746015,0,0,10,Wilcoxon,0.001953,0.005859,Boruta

Global significance for number of selected features (n_selected)

       metric      test   p_value                      methods  n_runs
0  n_selected  Friedman  0.029291  [GWO, BA, LightGBM, Boruta]      10

Pairwise post-hoc vs GWO for number of selected features (n_selected)

,metric,reference,comparison,n_runs,mean_ref,mean_cmp,wins_ref,ties,wins_cmp,test,p_value,p_holm,faster_by_mean
0,n_selected,GWO,BA,10,10.0,10.0,0,10,0,Wilcoxon,1.00,1.00,GWO
1,n_selected,GWO,LightGBM,10,10.0,10.0,0,10,0,Wilcoxon,1.00,1.00,GWO
2,n_selected,GWO,Boruta,10,10.0,9.6,0,7,3,Wilcoxon,0.25,0.75,Boruta

Stability summary (mean pairwise Jaccard across runs)

     method  mean_pairwise_jaccard  std_pairwise_jaccard  n_pairs
0  LightGBM               1.000000              0.000000       45
1    Boruta               0.932840              0.073291       45
2       GWO               0.585193              0.100605       45
3        BA               0.360625              0.100359       45

## Without FS

In [ ]:
import random
import time
import tracemalloc
from itertools import combinations
from sklearn.base import clone
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, f1_score, matthews_corrcoef, precision_score, recall_score
from sklearn.model_selection import StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

N_RUNS = 10
RUN_SEEDS = list(range(N_RUNS))
K_SUP = 10
N_FEATURES_TOTAL = int(X.shape[1])

FS_MAX_SAMPLES = 50000
FS_EPOCHS = 30
FS_POP_SIZE = 10
FS_CV_FOLDS = 3

FS_FITNESS_MODEL = 'DecisionTree'
FS_FITNESS_SCORING = 'f1_macro'

EVAL_CV_FOLDS = 3

def _subsample_for_fs_local(X_in: np.ndarray, y_in: np.ndarray, max_samples: int, seed: int):
    if (max_samples is None) or (X_in.shape[0] <= int(max_samples)):
        return X_in, y_in
    rng = np.random.default_rng(int(seed))
    idx = rng.choice(X_in.shape[0], size=int(max_samples), replace=False)
    return X_in[idx], y_in[idx]

def evaluate_cv_eff(clf, X_sub: np.ndarray, y_sub: np.ndarray, cv_folds: int, seed: int):
    cvk = StratifiedKFold(n_splits=int(cv_folds), shuffle=True, random_state=int(seed))

    accs, precs, recs, f1s, mccs = [], [], [], [], []
    train_time_s = 0.0
    infer_time_ms = 0.0

    tracemalloc.start()
    for tr, te in cvk.split(X_sub, y_sub):
        model = Pipeline([
            ('imputer', SimpleImputer(strategy='median')),
            ('scaler', StandardScaler(with_mean=True)),
            ('clf', clone(clf))
        ])

        t0 = time.perf_counter()
        model.fit(X_sub[tr], y_sub[tr])
        train_time_s += (time.perf_counter() - t0)

        t1 = time.perf_counter()
        p = model.predict(X_sub[te])
        infer_time_ms += (time.perf_counter() - t1) * 1000.0

        accs.append(accuracy_score(y_sub[te], p))
        precs.append(precision_score(y_sub[te], p, average='macro', zero_division=0))
        recs.append(recall_score(y_sub[te], p, average='macro', zero_division=0))
        f1s.append(f1_score(y_sub[te], p, average='macro', zero_division=0))
        mccs.append(matthews_corrcoef(y_sub[te], p))

    current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    return {
        'accuracy': float(np.mean(accs)),
        'precision_macro': float(np.mean(precs)),
        'recall_macro': float(np.mean(recs)),
        'f1_macro': float(np.mean(f1s)),
        'mcc': float(np.mean(mccs)),
        'train_time_s': float(train_time_s),
        'inference_time_ms': float(infer_time_ms),
        'peak_mem_mb': float(peak) / (1024.0 * 1024.0)
    }

methods = ['Without FS']

clf_factories = {
    'RandomForest': lambda s: RandomForestClassifier(
        n_estimators=800,
        max_depth=30,
        min_samples_split=3,
        min_samples_leaf=1,
        max_features='sqrt',
        class_weight='balanced',
        max_samples=0.8,
        n_jobs=-1,
        random_state=42
    ),
    'DecisionTree': lambda s: DecisionTreeClassifier(random_state=int(s), class_weight='balanced'),
    'LogisticRegression': lambda s: LogisticRegression(max_iter=1000, class_weight='balanced', random_state=int(s)),
    'GaussianNB': lambda s: GaussianNB(),
    'HistGradientBoosting': lambda s: HistGradientBoostingClassifier(random_state=int(s), learning_rate=0.1),
    'MLP': lambda s: MLPClassifier(
        random_state=int(s),
        hidden_layer_sizes=(128, 64),
        max_iter=200,
        early_stopping=True,
        n_iter_no_change=10,
        validation_fraction=0.1
    )
}

fs_cache = {}

def make_fs_base(seed: int):
    if str(FS_FITNESS_MODEL).lower() in ['rf', 'randomforest', 'random_forest']:
        return RandomForestClassifier(
            n_estimators=120,
            max_depth=18,
            min_samples_split=4,
            min_samples_leaf=2,
            max_features='sqrt',
            bootstrap=True,
            max_samples=0.7,
            class_weight='balanced_subsample',
            n_jobs=-1,
            random_state=int(seed)
        )
    return DecisionTreeClassifier(random_state=int(seed), class_weight='balanced')

def _serialize_idx(idx):
    return ','.join(str(int(i)) for i in idx)

def _mean_pairwise_jaccard(index_sets):
    sets = [set(int(i) for i in s) for s in index_sets if len(s) > 0]
    if len(sets) < 2:
        return np.nan, np.nan, 0
    vals = []
    for a, b in combinations(sets, 2):
        union = len(a | b)
        vals.append(len(a & b) / union if union else 1.0)
    return float(np.mean(vals)), float(np.std(vals)), int(len(vals))

def get_idx_and_time(seed: int, method: str, X_fs: np.ndarray, y_fs: np.ndarray):
    key = (int(seed), str(method))
    if key in fs_cache:
        return fs_cache[key]

    random.seed(int(seed))
    np.random.seed(int(seed))

    base = make_fs_base(int(seed))
    t0 = time.perf_counter()
    if str(method) == 'Without FS':
        idx, _ = select_features_without_fs(X_fs, y_fs, clf=base, cv=FS_CV_FOLDS, scoring=str(FS_FITNESS_SCORING))
    else:
        raise ValueError(f'Unknown method: {method}')

    fs_time_s = float(time.perf_counter() - t0)
    fs_cache[key] = (idx, fs_time_s)
    return idx, fs_time_s

rows = []
for seed in RUN_SEEDS:
    X_fs, y_fs = _subsample_for_fs_local(X, y, FS_MAX_SAMPLES, seed)
    for method in methods:
        idx, fs_time_s = get_idx_and_time(seed, method, X_fs, y_fs)
        X_sub = X[:, idx]
        for clf_name, make_clf in clf_factories.items():
            m = evaluate_cv_eff(make_clf(seed), X_sub, y, cv_folds=EVAL_CV_FOLDS, seed=seed)
            rows.append({
                'seed': int(seed),
                'method': str(method),
                'classifier': str(clf_name),
                'k_target': int(K_SUP) if method in [] else np.nan,
                'n_selected': int(len(idx)),
                'selected_features': _serialize_idx(idx),
                'fs_time_s': float(fs_time_s),
                **m
            })

fs_rows = []
for (s, m), (idx, fs_time_s) in fs_cache.items():
    fs_rows.append({
        'seed': int(s),
        'method': str(m),
        'k_target': int(K_SUP) if str(m) in [] else np.nan,
        'n_selected': int(len(idx)),
        'selected_features': _serialize_idx(idx),
        'fs_time_s': float(fs_time_s)
    })
fs_df = pd.DataFrame(fs_rows)
fs_df = fs_df.sort_values(['seed', 'method']).reset_index(drop=True)
display(fs_df)
display(fs_df.groupby('method', as_index=False)[['fs_time_s', 'n_selected']].agg(['mean', 'std']).reset_index())

stability_rows = []
for method_name, sub_df in fs_df.groupby('method'):
    sets = []
    for txt in sub_df['selected_features'].astype(str):
        sets.append([int(x) for x in txt.split(',') if str(x).strip() != ''])
    mean_j, std_j, n_pairs = _mean_pairwise_jaccard(sets)
    stability_rows.append({
        'method': str(method_name),
        'mean_pairwise_jaccard': mean_j,
        'std_pairwise_jaccard': std_j,
        'n_pairs': n_pairs
    })
stability_df = pd.DataFrame(stability_rows).sort_values('mean_pairwise_jaccard', ascending=False).reset_index(drop=True)
print('Feature-selection stability across runs')
display(stability_df)

raw_df = pd.DataFrame(rows)
display(raw_df)
print('Rows:', len(raw_df))

metrics_cols = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro', 'mcc', 'fs_time_s', 'train_time_s', 'inference_time_ms', 'peak_mem_mb', 'n_selected']

means = raw_df.groupby(['method', 'classifier'])[metrics_cols].mean().reset_index()
means = means.rename(columns={
    'method': 'Algorithm',
    'classifier': 'Classifier',
    'accuracy': 'Accuracy',
    'precision_macro': 'Precision',
    'recall_macro': 'Recall',
    'f1_macro': 'F1_macro',
    'mcc': 'MCC',
    'n_selected': 'N_Selected'
})

eval_df = means[['Algorithm', 'Classifier', 'Accuracy', 'Precision', 'Recall', 'F1_macro', 'MCC', 'N_Selected', 'fs_time_s', 'train_time_s', 'inference_time_ms', 'peak_mem_mb']].copy()
eval_df = eval_df.sort_values(['F1_macro', 'MCC', 'Accuracy'], ascending=[False, False, False]).reset_index(drop=True)
display(eval_df)

print('Deployment-oriented summary (lower downstream cost is better)')
deployment_df = eval_df[['Algorithm', 'Classifier', 'N_Selected', 'train_time_s', 'inference_time_ms', 'peak_mem_mb']].copy()
deployment_df = deployment_df.sort_values(['N_Selected', 'peak_mem_mb', 'inference_time_ms', 'train_time_s'], ascending=[True, True, True, True]).reset_index(drop=True)
display(deployment_df)

agg = raw_df.groupby(['method', 'classifier'])[metrics_cols].agg(['mean', 'std'])
agg.columns = [f"{m}_{s}" for (m, s) in agg.columns]
agg = agg.reset_index()

def fmt_pair(m, s, is_time=False):
    if pd.isna(m):
        return ''
    if pd.isna(s):
        return f"{m:.4f}" if not is_time else f"{m:.3f}"
    return (f"{m:.4f} +- {s:.4f}" if not is_time else f"{m:.3f} +- {s:.3f}")

final_table = pd.DataFrame({
    'Method': agg['method'].astype(str),
    'Classifier': agg['classifier'].astype(str),
})

for src, dst in {
    'accuracy': 'accuracy',
    'precision_macro': 'precision_macro',
    'recall_macro': 'recall_macro',
    'f1_macro': 'f1_macro',
    'mcc': 'mcc',
    'n_selected': 'n_selected',
    'fs_time_s': 'fs_time_s',
    'train_time_s': 'train_time_s',
    'inference_time_ms': 'inference_time_ms',
    'peak_mem_mb': 'peak_mem_mb'
}.items():
    mcol = f"{src}_mean"
    scol = f"{src}_std"
    is_time = src in ['fs_time_s', 'train_time_s', 'inference_time_ms', 'peak_mem_mb']
    final_table[dst] = [fmt_pair(m, s, is_time=is_time) for m, s in zip(agg[mcol], agg[scol])]

final_table = final_table.sort_values(['Classifier', 'Method']).reset_index(drop=True)
display(final_table)

,seed,method,k_target,n_selected,selected_features,fs_time_s
0,0,Without FS,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",1.063728
1,1,Without FS,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.824218
2,2,Without FS,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.829466
3,3,Without FS,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.868167
4,4,Without FS,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.955720
5,5,Without FS,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.831754
6,6,Without FS,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.879789
7,7,Without FS,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.849581
8,8,Without FS,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.910403
9,9,Without FS,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.940571

  index      method fs_time_s           n_selected
                         mean       std       mean  std
0     0  Without FS   0.89534  0.075121       24.0  0.0

Feature-selection stability across runs

       method  mean_pairwise_jaccard  std_pairwise_jaccard  n_pairs
0  Without FS                    1.0                   0.0       45

,seed,method,classifier,k_target,n_selected,selected_features,fs_time_s,accuracy,precision_macro,recall_macro,f1_macro,mcc,train_time_s,inference_time_ms,peak_mem_mb
0,0,Without FS,RandomForest,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",1.063728,0.906542,0.865420,0.911031,0.874474,0.897188,86.835590,8231.948087,57.149384
1,0,Without FS,DecisionTree,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",1.063728,0.891802,0.851988,0.898156,0.861778,0.880793,1.866413,55.395085,57.076730
2,0,Without FS,LogisticRegression,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",1.063728,0.683807,0.649636,0.719981,0.666868,0.652384,68.531575,127.975835,57.076025
3,0,Without FS,GaussianNB,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",1.063728,0.236240,0.288249,0.318651,0.239624,0.180903,0.709744,143.007287,57.069308
4,0,Without FS,HistGradientBoosting,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",1.063728,0.905020,0.882390,0.906516,0.881641,0.895524,224.778933,4825.372909,57.138994
5,0,Without FS,MLP,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",1.063728,0.890760,0.886985,0.879658,0.868961,0.879861,195.720208,271.333835,57.078880
6,1,Without FS,RandomForest,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.824218,0.906038,0.855208,0.912110,0.869122,0.896673,76.201139,7910.878290,57.122377
7,1,Without FS,DecisionTree,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.824218,0.891670,0.841971,0.899505,0.856719,0.880677,1.601930,61.623360,57.078476
8,1,Without FS,LogisticRegression,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.824218,0.683052,0.642381,0.720726,0.662284,0.651627,75.215775,100.618156,57.075308
9,1,Without FS,GaussianNB,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.824218,0.231663,0.304126,0.314701,0.235643,0.175140,0.535495,147.161208,57.070086
10,1,Without FS,HistGradientBoosting,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.824218,0.909394,0.885729,0.912048,0.886415,0.900385,222.147287,7935.505451,57.135096
11,1,Without FS,MLP,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.824218,0.894115,0.888156,0.883053,0.872351,0.883349,249.619065,267.834588,57.077990
12,2,Without FS,RandomForest,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.829466,0.904540,0.850310,0.911358,0.864068,0.895083,94.254860,11273.181615,57.134714
13,2,Without FS,DecisionTree,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.829466,0.888363,0.835562,0.897211,0.850090,0.877104,1.661305,47.829642,57.076873
14,2,Without FS,LogisticRegression,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.829466,0.681518,0.638608,0.720053,0.657844,0.650066,78.542126,92.834884,57.074258
15,2,Without FS,GaussianNB,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.829466,0.238038,0.311724,0.319849,0.243208,0.182859,0.624047,145.877384,57.069483
16,2,Without FS,HistGradientBoosting,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.829466,0.909993,0.886985,0.910288,0.885967,0.901042,266.226463,4244.306127,57.133109
17,2,Without FS,MLP,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.829466,0.893384,0.889212,0.881766,0.870995,0.882745,247.862485,131.990035,57.080281
18,3,Without FS,RandomForest,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.868167,0.904493,0.850307,0.911133,0.863975,0.895027,86.931065,9448.500284,57.135124
19,3,Without FS,DecisionTree,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.868167,0.889358,0.836546,0.897905,0.850929,0.878201,1.532179,48.880646,57.074285
20,3,Without FS,LogisticRegression,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.868167,0.681458,0.638348,0.719837,0.657510,0.650025,65.829887,95.434187,57.074930
21,3,Without FS,GaussianNB,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.868167,0.239032,0.310012,0.320711,0.243641,0.184197,0.586441,169.247699,57.070661
22,3,Without FS,HistGradientBoosting,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.868167,0.909825,0.885016,0.910498,0.885161,0.900858,198.970490,4986.671811,57.134862
23,3,Without FS,MLP,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.868167,0.889873,0.899267,0.861780,0.864889,0.878727,139.542773,291.153571,57.084291
24,4,Without FS,RandomForest,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.955720,0.905283,0.854369,0.911264,0.868348,0.895826,78.161777,11030.713556,57.124471
25,4,Without FS,DecisionTree,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.955720,0.890364,0.840833,0.898267,0.855521,0.879237,1.706511,45.662763,57.074687
26,4,Without FS,LogisticRegression,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.955720,0.683076,0.642551,0.720659,0.662344,0.651657,61.593512,107.651379,57.075331
27,4,Without FS,GaussianNB,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.955720,0.239464,0.299364,0.320989,0.244017,0.184726,0.590483,146.397151,57.070169
28,4,Without FS,HistGradientBoosting,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.955720,0.910616,0.889250,0.913349,0.888807,0.901706,142.085323,1530.746035,57.129883
29,4,Without FS,MLP,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.955720,0.893144,0.874882,0.898190,0.873842,0.882455,225.304230,105.052523,57.079008
30,5,Without FS,RandomForest,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.831754,0.905212,0.854362,0.911399,0.868419,0.895743,77.588270,8269.060697,57.139209
31,5,Without FS,DecisionTree,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.831754,0.891023,0.841545,0.898978,0.856227,0.879966,1.539009,46.172632,57.084182
32,5,Without FS,LogisticRegression,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.831754,0.683004,0.642542,0.720784,0.662372,0.651576,76.659798,85.314921,57.084521
33,5,Without FS,GaussianNB,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.831754,0.223478,0.273668,0.307579,0.224390,0.164816,0.549131,152.955617,57.071321
34,5,Without FS,HistGradientBoosting,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.831754,0.897758,0.877049,0.899123,0.875212,0.887522,188.724257,3150.000379,57.135104
35,5,Without FS,MLP,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.831754,0.890352,0.899327,0.862847,0.865760,0.879264,180.011975,159.048820,57.099271
36,6,Without FS,RandomForest,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.879789,0.904157,0.860572,0.909664,0.868961,0.894635,76.748009,7185.919223,57.122084
37,6,Without FS,DecisionTree,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.879789,0.890005,0.847676,0.897253,0.856751,0.878890,1.494965,45.864976,57.075638
38,6,Without FS,LogisticRegression,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.879789,0.683747,0.650673,0.719916,0.667095,0.652354,55.563724,101.949919,57.074326
39,6,Without FS,GaussianNB,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.879789,0.236168,0.284948,0.318520,0.238793,0.180866,0.511657,142.546345,57.069861
40,6,Without FS,HistGradientBoosting,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.879789,0.910101,0.888966,0.912906,0.888350,0.901154,223.557362,3308.264177,57.140829
41,6,Without FS,MLP,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.879789,0.891143,0.873350,0.896600,0.872039,0.880301,146.073506,138.925566,57.091695
42,7,Without FS,RandomForest,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.849581,0.905056,0.854316,0.911253,0.868250,0.895588,82.265222,7589.638369,57.141061
43,7,Without FS,DecisionTree,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.849581,0.891179,0.841390,0.899123,0.856220,0.880134,1.639258,49.607549,57.078155
44,7,Without FS,LogisticRegression,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.849581,0.682800,0.642076,0.720522,0.662005,0.651353,63.886293,97.573581,57.078465
45,7,Without FS,GaussianNB,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.849581,0.223370,0.270757,0.307474,0.224282,0.164720,0.566134,169.918438,57.071280
46,7,Without FS,HistGradientBoosting,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.849581,0.909693,0.888641,0.912553,0.888006,0.900703,180.824633,6660.966757,57.141983
47,7,Without FS,MLP,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.849581,0.888770,0.871799,0.894304,0.870049,0.877682,128.295759,107.442231,57.086586
48,8,Without FS,RandomForest,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.910403,0.905427,0.854581,0.911588,0.868594,0.895989,78.438752,8080.943245,57.138796
49,8,Without FS,DecisionTree,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.910403,0.891155,0.841479,0.899115,0.856298,0.880105,1.603215,54.455089,57.077311
50,8,Without FS,LogisticRegression,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.910403,0.683292,0.642720,0.720936,0.662525,0.651877,74.000038,87.430565,57.074499
51,8,Without FS,GaussianNB,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.910403,0.226402,0.290779,0.309885,0.228411,0.168043,0.518792,147.752376,57.069217
52,8,Without FS,HistGradientBoosting,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.910403,0.910688,0.889569,0.913363,0.888961,0.901783,281.618356,2670.177252,57.139853
53,8,Without FS,MLP,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.910403,0.891754,0.887053,0.879918,0.868540,0.880929,200.902011,202.924654,57.080767
54,9,Without FS,RandomForest,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.940571,0.905080,0.854235,0.911271,0.868281,0.895602,81.373295,8015.170462,57.141665
55,9,Without FS,DecisionTree,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.940571,0.890616,0.841060,0.898597,0.855801,0.879514,1.807455,71.871024,57.074854
56,9,Without FS,LogisticRegression,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.940571,0.683112,0.642362,0.720977,0.662315,0.651705,58.380193,85.148947,57.076238
57,9,Without FS,GaussianNB,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.940571,0.223274,0.271173,0.307459,0.224216,0.164536,0.506774,144.453761,57.071056
58,9,Without FS,HistGradientBoosting,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.940571,0.909034,0.880628,0.911308,0.883345,0.899993,126.792109,1375.663216,57.140137
59,9,Without FS,MLP,NaN,24,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23",0.940571,0.893803,0.875999,0.898776,0.874308,0.883266,226.162425,131.313867,57.081739

Rows: 60

,Algorithm,Classifier,Accuracy,Precision,Recall,F1_macro,MCC,N_Selected,fs_time_s,train_time_s,inference_time_ms,peak_mem_mb
0,Without FS,HistGradientBoosting,0.908212,0.885422,0.910195,0.885186,0.899067,24.0,0.89534,205.572521,4068.767411,57.136985
1,Without FS,MLP,0.891710,0.884603,0.883689,0.870174,0.880858,24.0,0.89534,193.949444,180.701969,57.084051
2,Without FS,RandomForest,0.905183,0.855368,0.911207,0.868249,0.895735,24.0,0.89534,81.879798,8703.595383,57.134888
3,Without FS,DecisionTree,0.890554,0.842005,0.898411,0.855633,0.879462,24.0,0.89534,1.645224,52.736277,57.077119
4,Without FS,LogisticRegression,0.682887,0.643190,0.720439,0.662316,0.651462,24.0,0.89534,67.820292,98.193237,57.076390
5,Without FS,GaussianNB,0.231713,0.290480,0.314582,0.234623,0.175081,24.0,0.89534,0.569870,150.931727,57.070244

Deployment-oriented summary (lower downstream cost is better)

,Algorithm,Classifier,N_Selected,train_time_s,inference_time_ms,peak_mem_mb
0,Without FS,GaussianNB,24.0,0.569870,150.931727,57.070244
1,Without FS,LogisticRegression,24.0,67.820292,98.193237,57.076390
2,Without FS,DecisionTree,24.0,1.645224,52.736277,57.077119
3,Without FS,MLP,24.0,193.949444,180.701969,57.084051
4,Without FS,RandomForest,24.0,81.879798,8703.595383,57.134888
5,Without FS,HistGradientBoosting,24.0,205.572521,4068.767411,57.136985

,Method,Classifier,accuracy,precision_macro,recall_macro,f1_macro,mcc,n_selected,fs_time_s,train_time_s,inference_time_ms,peak_mem_mb
0,Without FS,DecisionTree,0.8906 +- 0.0011,0.8420 +- 0.0048,0.8984 +- 0.0008,0.8556 +- 0.0032,0.8795 +- 0.0011,24.0000 +- 0.0000,0.895 +- 0.075,1.645 +- 0.120,52.736 +- 8.460,57.077 +- 0.003
1,Without FS,GaussianNB,0.2317 +- 0.0069,0.2905 +- 0.0156,0.3146 +- 0.0059,0.2346 +- 0.0085,0.1751 +- 0.0087,24.0000 +- 0.0000,0.895 +- 0.075,0.570 +- 0.062,150.932 +- 10.250,57.070 +- 0.001
2,Without FS,HistGradientBoosting,0.9082 +- 0.0040,0.8854 +- 0.0042,0.9102 +- 0.0044,0.8852 +- 0.0043,0.8991 +- 0.0044,24.0000 +- 0.0000,0.895 +- 0.075,205.573 +- 48.996,4068.767 +- 2113.183,57.137 +- 0.004
3,Without FS,LogisticRegression,0.6829 +- 0.0008,0.6432 +- 0.0040,0.7204 +- 0.0004,0.6623 +- 0.0031,0.6515 +- 0.0008,24.0000 +- 0.0000,0.895 +- 0.075,67.820 +- 8.056,98.193 +- 12.845,57.076 +- 0.003
4,Without FS,MLP,0.8917 +- 0.0018,0.8846 +- 0.0102,0.8837 +- 0.0136,0.8702 +- 0.0032,0.8809 +- 0.0020,24.0000 +- 0.0000,0.895 +- 0.075,193.949 +- 44.516,180.702 +- 71.969,57.084 +- 0.007
5,Without FS,RandomForest,0.9052 +- 0.0007,0.8554 +- 0.0045,0.9112 +- 0.0006,0.8682 +- 0.0029,0.8957 +- 0.0008,24.0000 +- 0.0000,0.895 +- 0.075,81.880 +- 5.834,8703.595 +- 1414.947,57.135 +- 0.009